### ISSUE TITLE
Text size formatting not working

### ISSUE THREAD

**Issue by daylark** [leatrix/leatrix-plus#10]
Hiya! Thanks so much for this. This addon's been a lifesaver.

Unfortunately, one of the aspects of the addon that's been most helpful to me has been broken for a couple of months now - potentially since the prepatch, perhaps? 

I have spectacularly poor vision, and the quest/mailbox text size changing was a MASSIVE accessibility tool for me. Unfortunately, both settings now don't do anything. Do you have any idea why that might be - and whether it's fixable?

Thank you so much. I'm so sorry to be a pain!

**Comment by leatrix** [comment]
It's not broken as far as I know.  It's working fine for me.  You have either another addon or custom fonts installed preventing Leatrix Plus from changing the quest and mail text size.  Disable other addons and try again.  If it works, enable other addons gradually until you find the addon causing the problem.
