### ISSUE TITLE
Dragonflight 9.2.38 - Vendor Error

### ISSUE THREAD

**Issue by Aideenwolf** [leatrix/leatrix-plus#100]
Getting an error when talking to a vendor

12x Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:3334: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "@Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua"]:3334: in function <Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:3326>

Locals:
SoldCount = 0
Rarity = 0
ItemPrice = 0
CurrentItemLink = nil
void = nil
(for index) = 0
(for limit) = 4
(for step) = 1
BagID = 0
(*temporary) = 1
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to call global 'GetContainerNumSlots' (a nil value)"
whiteList = <table> {
 11944 = "Dark Iron Baby Booties"
 3670 = "Large Slimy Bone"
 62072 = "Robbles Wobbly Staff"
 6150 = "A Frayed Knot"
 36812 = "Ground Gear"
 67410 = "Very Unlucky Rock"
 3300 = "Rabbits Foot"
 25402 = "The Stoppable Force"
 11406 = "Rotting Bear Carcass"
}
SellJunkTicker = <userdata>
IterationCount = 500
totalPrice = 0
mBagID = -1
mBagSlot = -1
StopSelling = <function> defined @Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:3143
LeaPlusLC = <table> {
 LeaPlusNav9 = Button {
 }
 WidgetTopR = "TOP"
 BuffFrameX = -205
 LockItem = <function> defined @Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:80
 BuffFrameY = -13
 TimerY = -96
 LeaPlusNav2.s = Texture {
 }
 RecentChatSize = 170
 MakeFT = <function> defined @Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:326
 BordersAlpha = 0
 MinimapR = "TOPRIGHT"
 WidgetPowerY = 305
 TipCursorX = 0
 Page0 = Frame {
 }
 DressupItemButtons = "On"
 InviteFromWhisper = "Off"
 WidgetPowerX = 0
 MuteZeppelins = "Off"
 PowerBarR = "BOTTOM"
 MakeCB = <function> defined @Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:14524
 BuffFrameScale = 1
 LoadVarAnc = <function> defined @Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:230
 AcceptPartyFriends = "Off"
 LockOption = <function> defined @Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:522
 RestoreChatMessages = "Off"
 MinimapModder = "Off"
 MakeSL = <function> defined @Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:14470
 Page4 = Frame {
 }
 ShowDropTip = <function> defined @Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:266
 ReloadCheck = <function> defined @Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:582
 NoPartyInvites = "Off"
 NumberOfPages = 9
 PowerBarX = 0
 TipHideShiftOverride = "On"
 HideZoneText = "Off"
 TimerX = -5
 EnhanceDressup = "Off"
 MoreFontSizes = "Off"
 SetDim = <function> defined @Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:541
 HideMiniAddonButtons = "On"
 LeaPlusQuestFontSize = 12
 TipShowTarget = "On"
 FilterChatMessages = "Off"
 DF = true
 ShowErrorsFlag = 1
 NoDuelRequests = "On"
 CooldownsOnPlayer = "Off"
 QuestFontChange = "Off"
 NoRaidRestrictions = "Off"
 MuteAirships = "Off"
 TipOffsetX = -13
 AutoQuestKeyMenuTable = <table> {
 }
 MuteSoulEaters = "Off"
 HideCleanupBtns = "Off"
 BordersTop = 0
 Page9 = Frame {
 }
 ZygorToggle = <function> defined @Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:338
 TipNoHealthBar = "Off"
 NoStickyEditbox = "Off"
 TooltipAnchorMenu = 1
 ShowRaidToggle = "Off"
 MinimapNoScale = "Off"
 ShowVoiceButtons = "Off"
 IsPlusShowing = <function> defined @Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:434
 BlockDrunkenSpam = "Off"
 AutoReleaseNoAshran = "Off"
 MuteMechsuits = "Off"
 MakePage = <function> defined @Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:17176
 ShowWowheadLinks = "Off"
 HideMiniClock = "Off"
 PowerBarY = 115
 AutoQuestCompleted = "On"
 Page7 = Frame {
 }
 NoBagsMicro = "Off"
 CfgBtn = <function> defined @Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:304
 LeaPlusMailFontSize = 15
 NoFriendRequests = "Off"
 AutoRepairShowSummary = "On"
 AutoReleaseNoTolBarad = "Off"
 transTable = <table> {
 }
 MuteMechSteps = "Off"
 WidgetTopScale = 1
 NoCombatLogTab = "Off"
 muteTable = <table> {
 }
 LeaPlusNav2 = Button {
 }
 MoveChatEditBoxToTop = "On"
 MuteSniffing = "Off"
 MinimapY = -22
 MakeWD = <function> defined @Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:14461
 LeaPlusNav4 = Button {
 }
 NoScreenGlow = "Off"
 Page1 = Frame {
 }
 LeaPlusChatFontSize = 20
 LeaPlusNav0 = Button {
 }
 MailFontChange = "Off"
 LeaPlusNav3 = Button {
 }
 ShowBorders = "Off"
 MainPanelA = "CENTER"
 BordersLeft = 0
 BuffFrameR = "TOPRIGHT"
 MuteSunflower = "Off"
 AutoSellJunk = "On"
 AutoRepairGear = "On"
 EditPlayerFrameScale = 1
 ManageTimer = "Off"
 WidgetPowerScale = 1
 CreateDropDown = <function> defined @Interface/

**Comment by leatrix** [comment]
Many thanks for your report.  Blizzard changed some game functions in Dragonflight Beta which caused 'Sell junk automatically' to show Lua errors.  This is fixed in 9.2.39.
