### ISSUE TITLE
Feature Request: Add pet Pierre to be muted option

### ISSUE THREAD

**Issue by KoForm** [leatrix/leatrix-plus#101]
Leatrix Plus is the best addon for QoL. Thank you for the great work.

I hope there is an option for pet Pierre to be able to be muted  besides Singing Sunflower.
Since  Pierre is a great substitute for Cooking Fire  but making noises very annoying

Cheers.

**Comment by leatrix** [comment]
Good idea.  In 9.2.42.alpha.5, you can make Pierre quieter.
