### ISSUE TITLE
Feature Request: Add spell / item ID to tooltip

### ISSUE THREAD

**Issue by Petrol30** [leatrix/leatrix-plus#102]
Dropping ElvUI for Dragonflight and would be a nice QoL addition

**Comment by leatrix** [comment]
This is already in the addon.  It's called Show web link.

If you haven't setup web link yet, go into the game key bindings panel, click Leatrix Plus and assign a hotkey for Show web link. Now hover your pointer over any item, spell, buff or debuff, NPC, mount, pet - pretty much anything that has a tooltip - and press your web link hotkey.  A web link window will show up which will contain the ID of whatever your pointer is over (if known) and a Wowhead link for it.

For Shadowlands and Dragonflight, you can also use web link on player characters to get a Battle.net armory link (make sure your pointer is over the character or a frame showing them such as your target frame when you press your web link hotkey).

If web link isn't able to determine what your pointer is over, the link shown will be a generic Wowhead search to point you in the right direction.  So if you see a world object in The Maw or something and don't know what it's for, use web link on it and go to the link shown.  Got an item in your bag and don't know what it's for?  Use web link on the item.  Need to know a buff ID, item ID or spell ID?  Use web link on the icons.  Web link is very useful.

**Comment by leatrix** [comment]
Probably not going to add an option like idTip.  Web link was actually added as a on-demand, performance-friendly alternative to addons that display IDs for everything all the time (though it's primary purpose is the web link obviously rather than the ID).

**Comment by Petrol30** [comment]
Apologies for taking this long to respond.

When I wrote the request, I was thinking more along the lines of how Zink described it but also was not aware of the web link feature already built in.  After reading your post on everything it interacts with, I can appreciate your decision in going with the "on-demand, performance-friendly alternative" method (one of the mains reasons I'm dropping ElvUI).

Thanks for the responses

Also, I love this addon - keep up the great work!
