### ISSUE TITLE
[BUG] Hide Talking Frame Doesn't Work in Latest Dragonflight Beta Build

### ISSUE THREAD

**Issue by Calesta** [leatrix/leatrix-plus#103]
Using the latest version of Leatrix Plus (9.2.41), the 'Hide talking frame' option doesn't work in the latest build.  

I've gone to a few different world quests and have seen the talking head frame show up each time.  Maybe they changed something in the latest build?  It was working fine before.

![Hide Talking Head Option Selected](https://user-images.githubusercontent.com/13042214/196012160-fc4a5098-eb17-4810-be5f-c267df169795.PNG)

![Talking Head Frame](https://user-images.githubusercontent.com/13042214/196012171-d1cbb4c2-6947-4f6b-8c0b-6fc8067e2b95.jpg)

Hope it's an easy fix!

**Comment by leatrix** [comment]
Thanks for the report.  Should be fixed in 9.2.42.

**Comment by Calesta** [comment]
I tested the latest build, 9.2.44, and this is working once again! Thanks!

I'm not sure if you typically close the issue once resolved or you wait to hear for feedback from the reporter.

**Comment by leatrix** [comment]
I will typically wait a few days for feedback and then close the issue. Or you can close it when you have confirmed that it works ok. It doesn't really matter.
