### ISSUE TITLE
[BUG?] Can't Move Chat Window to the Left Most Screen Border w/Unclamp Chat Frame in Dragonflight Beta

### ISSUE THREAD

**Issue by Calesta** [leatrix/leatrix-plus#104]
I have Leatrix Plus 9.2.42 installed.

A few beta builds ago if I selected

- Hide chat buttons
- Hide social button, and
- Unclamp Chat Frame

then I was able to move the chat window all the way to the left border of the screen.

![LPlus Chat Frame](https://user-images.githubusercontent.com/13042214/196077048-2d922731-7d8f-4237-b573-56e39e937788.PNG)

In recent builds, it hasn't worked the same.  It's like the client still thinks the buttons are there and they can't go off the screen.

![Can't Move It Any More](https://user-images.githubusercontent.com/13042214/196077169-a76b23b7-dcca-4f2f-92e7-3dbd513caa85.PNG)

Perhaps it's not possible given changes to the Blizzard custom UI interface now, but I thought I'd put a ticket in just in case.

**Comment by leatrix** [comment]
Thanks for the report.  Should be fixed in 9.2.43.

**Comment by Calesta** [comment]
I tested the latest build, 9.2.44, and this is working once again!  Thanks! 

I'm not sure if you typically close the issue once resolved or you wait to hear for feedback from the reporter.

**Comment by leatrix** [comment]
I will typically wait a few days for feedback and then close the issue.  Or you can close it when you have confirmed that it works ok.  It doesn't really matter.
