### ISSUE TITLE
Feature Request: Enhance Tooltip Additions

### ISSUE THREAD

**Issue by Calesta** [leatrix/leatrix-plus#105]
Add 'Remove Server Name' and 'Remove Title' options to the Enhance Tooltip configuration panel.

**Comment by drum84** [comment]
+1

And a way to anchor the tooltip somewhere else would be awesome.

**Comment by Brian853** [comment]
+1
And show ilvl of char on tooltip

**Comment by leatrix** [comment]
Suggestions appreciated (use Edit Mode to move the tooltip).
