### ISSUE TITLE
Easy Mount Special option missing in recent updates

### ISSUE THREAD

**Issue by Hobskins** [leatrix/leatrix-plus#106]
Hello!

As title says it seems that in recent updates within the last week or two i've noticed the Easy Mount Special option missing from the "System" Menu of LTP. I sometimes use the option whenever im bored or soking around with friends etc. I use it quite frequently and it was nice to have. Might we see it's return sometime soon? :)

**Comment by leatrix** [comment]
> 9.2.42 - 16th October 2022
> - You can now assign a keybind for /mountspecial in the game key bindings menu.  The 'Easy mount special' option has been removed.
