### ISSUE TITLE
Tooltip Cursor Anchor not working 

### ISSUE THREAD

**Issue by reconops** [leatrix/leatrix-plus#107]
On Dragonflight Beta with LTP Version 10.0.00.
No other addons enabled.

Tooltop will not anchor to cursor on any option.

**Comment by leatrix** [comment]
It seems to be working fine for me.  What tooltips are you trying to anchor to the cursor?  The cursor anchor will only work with units in the game world (same as before).  UI tooltips won't be affected (use Edit Mode to move UI tooltips).

**Comment by siven80** [comment]
Is there anyway to have ability tooltips show up at cursor, and everything else at normal position?

**Comment by leatrix** [comment]
No.  Leatrix Plus only processes unit tooltips (player, party, target, etc).  Non-unit tooltips are not touched at all.
