### ISSUE TITLE
Feature Request: Shorten chat channel names

### ISSUE THREAD

**Issue by Joffis** [leatrix/leatrix-plus#108]
Option to shorten chat channel names such as [Guild] to [G] or [1. General] to [1] in default chat would be nice additions especially since there are few long ones like LookingForGroup on classic that take unnecessary space. There's few addons that do this but they're usually massive overhauls such as ElvUI.

**Comment by Brian853** [comment]
need customized options. freeyly setting replace "[Guild]" to "[G]" or "g", and so on.

**Comment by leatrix** [comment]
Feedback appreciated.
