### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by nxvash** [leatrix/leatrix-plus#111]
Running the newest game client, and tried both the release version and the newest alpha version of leatrix but am getting this error.  

2x [ADDON_ACTION_FORBIDDEN] AddOn 'Leatrix_Plus' tried to call the protected function 'ClearTarget()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `ClearTarget'
[string "@Interface/FrameXML/EditModeManager.lua"]:1496: in function `ResetTargetAndFocus'
[string "@Interface/FrameXML/EditModeManager.lua"]:1531: in function `RefreshTargetAndFocus'
[string "@Interface/FrameXML/EditModeManager.lua"]:1462: in function `OnEditModeEnter'
[string "@Interface/FrameXML/EditModeManager.lua"]:171: in function `EnterEditMode'
[string "@Interface/FrameXML/EditModeManager.lua"]:193: in function <Interface/FrameXML/EditModeManager.lua:191>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/UIParent.lua"]:2844: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2648: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2552: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3150: in function `ShowUIPanel'
[string "*GameMenuFrame.xml:94_OnClick"]:2: in function <[string "*GameMenuFrame.xml:94_OnClick"]:1>

**Comment by leatrix** [comment]
- Is this for live Wow or PTR/BETA?
- How often do you see this?
- What were you doing when the error occurred?
- Did the error appear when you exited Edit Mode?
- Can you paste your Leatrix_Plus.lua saved settings file here?  You can find it in Wow > WTF > Account > AccountID > SavedVariables > Leatrix_Plus.lua.
- What other addons do you use?

**Comment by nxvash** [comment]
Live
only when entering and exiting edit mode it seems. 
entering and exiting edit mode
yes
badboy, blizzmove, bugsack, details!, handynotes, hearthroulette, hekili, leatrix, pawn, simulationcraft, tomcat's tours, tomtom, bagnon  is what I have currently enabled. 


`
LeaPlusDB = {
	["WidgetTopR"] = "TOP",
	["BuffFrameX"] = -205,
	["SetFieldOfView"] = "Off",
	["BuffFrameY"] = -13,
	["TimerY"] = -96,
	["MusicContinent"] = "Zones",
	["MuteRazorwings"] = "Off",
	["minimapPos"] = 136.6504651360956,
	["DurabilityX"] = 0,
	["MinimapR"] = "TOPRIGHT",
	["WidgetPowerY"] = 305,
	["TipCursorX"] = 0,
	["AutoQuestWeekly"] = "On",
	["MainPanelR"] = "CENTER",
	["MuteBalls"] = "Off",
	["DurabilityScale"] = 1,
	["MuteZeppelins"] = "Off",
	["TransHallowed"] = "Off",
	["ManageWidgetPower"] = "Off",
	["BuffFrameScale"] = 1,
	["ManageDurability"] = "Off",
	["AcceptPartyFriends"] = "Off",
	["RestoreChatMessages"] = "Off",
	["MinimapModder"] = "Off",
	["NoPartyInvites"] = "Off",
	["PowerBarX"] = 0,
	["TipHideShiftOverride"] = "On",
	["HideZoneText"] = "Off",
	["TimerX"] = -5,
	["WidgetTopA"] = "TOP",
	["MoreFontSizes"] = "Off",
	["HideMiniAddonButtons"] = "On",
	["LeaPlusQuestFontSize"] = 12,
	["TipShowTarget"] = "On",
	["FilterChatMessages"] = "Off",
	["FocusR"] = "CENTER",
	["MuteChimes"] = "Off",
	["NoDuelRequests"] = "On",
	["CooldownsOnPlayer"] = "Off",
	["QuestFontChange"] = "Off",
	["NoRaidRestrictions"] = "Off",
	["MuteAirships"] = "Off",
	["TipOffsetX"] = -13,
	["MuteSoulEaters"] = "Off",
	["HideCleanupBtns"] = "Off",
	["AutoRepairGuildFunds"] = "On",
	["TipNoHealthBar"] = "Off",
	["NoStickyEditbox"] = "Off",
	["TooltipAnchorMenu"] = 1,
	["ShowRaidToggle"] = "Off",
	["MinimapNoScale"] = "Off",
	["ShowVoiceButtons"] = "Off",
	["MovieSkipInstance"] = "Off",
	["BlockDrunkenSpam"] = "Off",
	["AutoReleaseNoAshran"] = "Off",
	["MuteMechsuits"] = "Off",
	["MuteUnicorns"] = "Off",
	["HideMiniClock"] = "Off",
	["PowerBarY"] = 115,
	["AutoQuestCompleted"] = "On",
	["NoBagsMicro"] = "Off",
	["LeaPlusMailFontSize"] = 15,
	["NoFriendRequests"] = "Off",
	["AutoRepairShowSummary"] = "On",
	["AutoReleaseNoTolBarad"] = "Off",
	["MuteMechSteps"] = "Off",
	["WidgetTopScale"] = 1,
	["TipShowRank"] = "On",
	["PlusPanelAlpha"] = 0,
	["MoveChatEditBoxToTop"] = "Off",
	["MuteSniffing"] = "Off",
	["MinimapY"] = -22,
	["MuteRockets"] = "Off",
	["NoScreenGlow"] = "Off",
	["VehicleY"] = -192,
	["DurabilityR"] = "TOPRIGHT",
	["ShowCooldowns"] = "Off",
	["DurabilityA"] = "TOPRIGHT",
	["MailFontChange"] = "Off",
	["ShowBorders"] = "Off",
	["MainPanelA"] = "CENTER",
	["BordersLeft"] = 0,
	["HideActionButtonText"] = "Off",
	["BuffFrameR"] = "TOPRIGHT",
	["EnableHotkey"] = "Off",
	["MuteSunflower"] = "Off",
	["MuteGameSounds"] = "Off",
	["AutoRepairGear"] = "On",
	["EditPlayerFrameScale"] = 1,
	["ManageTimer"] = "Off",
	["WidgetPowerScale"] = 1,
	["HideTalkingFrame"] = "Off",
	["AutomateGossip"] = "On",
	["WidgetTopX"] = 0,
	["AutoQuestKeyMenu"] = 1,
	["NewCovenantButton"] = "Off",
	["RecentChatWindow"] = "Off",
	["hide"] = true,
	["NoTransforms"] = "Off",
	["NoSharedQuests"] = "Off",
	["AutoReleaseNoAlterac"] = "Off",
	["TimerA"] = "TOP",
	["MuteAerials"] = "Off",
	["InviteFriendsOnly"] = "Off",
	["EditModeScales"] = "Off",
	["BordersBottom"] = 0,
	["TransLantern"] = "Off",
	["HideMiniZoomBtns"] = "Off",
	["MiniShowBugSack"] = "Off",
	["ManageFocus"] = "Off",
	["VehicleScale"] = 1,
	["ShowVolume"] = "Off",
	["SetWeatherDensity"] = "Off",
	["ClassColPlayer"] = "On",
	["MuteHovercraft"] = "Off",
	["EasyItemDestroy"] = "Off",
	["InvKey"] = "inv",
	["CombineAddonButtons"] = "Off",
	["SaveProfFilters"] = "Off",
	["WidgetPowerR"] = "BOTTOM",
	["WidgetTopY"] = -15,
	["MinimapSize"] = 140,
	["FrmEnabled"] = "Off",
	["HideErrorMessages"] = "Off",
	["MuteSoulseekers"] = "Off",
	["MuteArena"] = "Off",
	["PowerBarScale"] = 1,
	["LeaStartPage"] = 0,
	["FriendlyGuild"] = "On",
	["MinimapScale"] = 1,
	["TimerScale"] = 1,
	["AutoReleasePvP"] = "Off",
	["HideMacroText"] = "Off",
	["NoPetAutomation"] = "Off",
	["AutoResNoCombat"] = "On",
	["WowheadLinkComments"] = "Off",
	["TipHideInCombat"] = "Off",
	["UseArrowKeysInChat"] = "Off",
	["EditBuffFrameScale"] = 1,
	["ShowTrainAllButton"] = "Off",
	["NoCommandBar"] = "Off",
	["FirstRunMessageSeen"] = true,
	["NoCooldownDuration"] = "On",
	["LeaPlusChatFontSize"] = 20,
	["SquareMinimap"] = "Off",
	["DurabilityY"] = -192,
	["NoRestedEmotes"] = "On",
	["CombatPlates"] = "Off",
	["FocusX"] = 0,
	["HideEventToasts"] = "Off",
	["TipBackSimple"] = "Off",
	["ControlR"] = "CENTER",
	["MuteReady"] = "Off",
	["EditDebuffFrameScale"] = 1,
	["ControlY"] = 0,
	["ShowWhoPinged"] = "On",
	["InviteFromWhisper"] = "Off",
	["UseEasyChatResizing"] = "Off",
	["NoAlerts"] = "Off",
	["ShowChatMenuButton"] = "Off",
	["AutoReleaseNoWintergsp"] = "Off",
	["BuffFrameA"] = "TOPRIGHT",
	["NoPetDuels"] = "Off",
	["BlockDuelSpam"] = "Off",
	["VehicleX"] = -100,
	["AutoAcceptRes"] = "Off",
	["FasterLooting"] = "On",
	["WidgetPowerA"] = "BOTTOM",
	["ManageBuffs"] = "Off",
	["ManagePowerBar"] = "Off",
	["BordersAlpha"] = 0,
	["PowerBarR"] = "BOTTOM",
	["NoChatFade"] = "Off",
	["DressupAnimControl"] = "On",
	["NoClassBar"] = "Off",
	["SetChatFontSize"] = "Off",
	["MaxCameraZoom"] = "Off",
	["MuteAnima"] = "Off",
	["NoScreenEffects"] = "Off",
	["NoGryphons"] = "On",
	["MuteTravelers"] = "Off",
	["HideBodyguard"] = "Off",
	["AutoSellExcludeList"] = "",
	["ManageControl"] = "Off",
	["NoBagAutomation"] = "Off",
	["ShowWowheadLinks"] = "On",
	["MutePierre"] = "Off",
	["VehicleR"] = "TOPRIGHT",
	["ShowMinimapIcon"] = "Off",
	["FovLevel"] = 90,
	["TransWitch"] = "Off",
	["UnclampChat"] = "Off",
	["AutoQuestShift"] = "Off",
	["TimerR"] = "TOP",
	["EnhanceDressup"] = "Off",
	["NoConfirmLoot"] = "Off",
	["FocusY"] = 0,
	["LockoutSharing"] = "Off",
	["NoStickyChat"] = "Off",
	["MuteTrains"] = "Off",
	["HideKeybindText"] = "Off",
	["RecentChatSize"] = 170,
	["NoCombatLogTab"] = "Off",
	["ClassColTarget"] = "On",
	["ShowCooldownID"] = "On",
	["ShowVolumeInFrame"] = "Off",
	["AutoQuestRegular"] = "On",
	["DurabilityStatus"] = "Off",
	["NoChatButtons"] = "On",
	["ControlX"] = 0,
	["BordersRight"] = 0,
	["WeatherLevel"] = 3,
	["NoSocialButton"] = "Off",
	["TipOffsetY"] = 94,
	["SyncFromFriends"] = "Off",
	["PlayerChainMenu"] = 2,
	["BordersTop"] = 0,
	["MuteStriders"] = "Off",
	["MinimapA"] = "TOPRIGHT",
	["MuteInterface"] = "Off",
	["MiniExcludeList"] = "",
	["MuteBrooms"] = "Off",
	["ManageVehicle"] = "Off",
	["MuteBattleShouts"] = "Off",
	["MuteGyrocopters"] = "Off",
	["EasyMountSpecial"] = "Off",
	["AutoAcceptSummon"] = "Off",
	["TipCursorY"] = 0,
	["AutoSellShowSummary"] = "On",
	["ShowPetSaveBtn"] = "Off",
	["AutomateQuests"] = "On",
	["MainPanelX"] = 104.1664123535156,
	["HideMiniZoneText"] = "Off",
	["MaxChatHstory"] = "On",
	["DressupFasterZoom"] = 3,
	["FasterMovieSkip"] = "On",
	["EditTargetFrameScale"] = 1,
	["VehicleA"] = "TOPRIGHT",
	["ManageWidgetTop"] = "Off",
	["AutoConfirmRole"] = "Off",
	["AutoQuestDaily"] = "On",
	["TipModEnable"] = "On",
	["MuteEvents"] = "Off",
	["ShowPlayerChain"] = "Off",
	["MiniClusterScale"] = 1,
	["PlusPanelScale"] = 1,
	["MinimapX"] = -17,
	["WidgetPowerX"] = 0,
	["MuteBanLu"] = "Off",
	["ControlA"] = "CENTER",
	["MuteFurlines"] = "Off",
	["HideBossBanner"] = "Off",
	["ShowReadyTimer"] = "Off",
	["UnivGroupColor"] = "Off",
	["ClassColFrames"] = "On",
	["ControlScale"] = 1,
	["PowerBarA"] = "BOTTOM",
	["LeaPlusTipSize"] = 1,
	["BlockSpellLinks"] = "Off",
	["AutoSellJunk"] = "On",
	["FriendlyCommunities"] = "Off",
	["FocusA"] = "CENTER",
	["MainPanelY"] = 85.00009155273438,
	["TipShowOtherRank"] = "Off",
	["NoHitIndicators"] = "Off",
	["MuteVaults"] = "Off",
	["CharAddonList"] = "Off",
	["MuteFizzle"] = "Off",
	["FocusScale"] = 1,
	["AutoReleaseDelay"] = 0,
	["MuteBikes"] = "Off",
	["EditFocusFrameScale"] = 1,
	["DressupItemButtons"] = "On",
	["AutoSellNoKeeperTahult"] = "On",
}
`

**Comment by nxvash** [comment]
the formatting on that got seriously messed up, I uploaded it to google drive.  https://drive.google.com/file/d/1vj3rmyAU5R9R9JXhrErfVYIhgYTR8RL5/view?usp=sharing

**Comment by leatrix** [comment]
Thank you.  I can't reproduce it with only LTP enabled.  I did see a few errors sometimes and one of them mentioned LTP but I only saw the error when I had other addons enabled.  With only LTP enabled, the error doesn't show.

- If you reload your UI (/reload), do you see the error every time you open and close Edit Mode?
- If you disable LTP, do you still see the error?
- If you disable all other addons except LTP, do you still see the error?

**Comment by nxvash** [comment]
I will check that as soon as I can.  Have a afternoon of conference calls.  :p

**Comment by leatrix** [comment]
I did see a taint popup with Hekili addon.

- Disable all addons except hekili.
- Logout of the game and return to the character select screen.
- Delete the saved settings file for hekili.  It's in WTF > Account > AccountID > SavedVariables > Hekili.lua and Hekili.bak.  This must be done while you are at the character select screen otherwise the game will recreate the files automatically.
- Login to the game.
- Enter Edit Mode and a taint popup will show.
- Exit Edit Mode and another taint popup will show.

The problem with taint errors (the type of error you are seeing) is they often blame the wrong addons.  So I really need a way to reproduce the error.

**Comment by nxvash** [comment]
I wasn't able to get on yesterday due to the emergency maintenance.  I was able to get a few mins of testing in this morning before the server shutdowns, and with the updated addon the issue seems resolved.  Once I can get some more time in game I will confirm this. Thanks for everything you do, I love this addon and if I had to choose only one this would be it. 

Aaron

**Comment by nxvash** [comment]
Original issue seems resolved, but I am seeing this in bugsack:

2x Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:4246: attempt to concatenate local 'realm' (a nil value)
[string "@Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua"]:4246: in function <Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:4243>

Locals:
self = Frame {
 0 = <userdata>
}
event = "PLAYER_LOGOUT"
name = "Mickdagger"
realm = nil
(*temporary) = <table> {
 WidgetTopR = "TOP"
 BuffFrameX = -205
 SetFieldOfView = "Off"
 BuffFrameY = -13
 TimerY = -96
 MusicContinent = "Search"
 MuteRazorwings = "Off"
 minimapPos = 136.650465
 DurabilityX = 0
 MinimapR = "TOPRIGHT"
 WidgetPowerY = 305
 TipCursorX = 0
 AutoQuestWeekly = "On"
 MainPanelR = "CENTER"
 MuteBalls = "Off"
 DurabilityScale = 1
 MuteZeppelins = "Off"
 TransHallowed = "Off"
 ManageWidgetPower = "Off"
 BuffFrameScale = 1
 ManageDurability = "Off"
 AcceptPartyFriends = "On"
 RestoreChatMessages = "On"
 MinimapModder = "Off"
 ChatTemp4 = <table> {
 }
 NoPartyInvites = "Off"
 PowerBarX = 0
 TipHideShiftOverride = "On"
 HideZoneText = "Off"
 TimerX = -5
 WidgetTopA = "TOP"
 MoreFontSizes = "Off"
 HideMiniAddonButtons = "On"
 LeaPlusQuestFontSize = 12
 TipShowTarget = "On"
 FilterChatMessages = "Off"
 FocusR = "CENTER"
 MuteChimes = "Off"
 NoDuelRequests = "On"
 CooldownsOnPlayer = "Off"
 QuestFontChange = "Off"
 NoRaidRestrictions = "Off"
 MuteAirships = "Off"
 TipOffsetX = -13
 MuteSoulEaters = "Off"
 HideCleanupBtns = "Off"
 AutoRepairGuildFunds = "On"
 TipNoHealthBar = "Off"
 NoStickyEditbox = "Off"
 TooltipAnchorMenu = 1
 ShowRaidToggle = "Off"
 MinimapNoScale = "Off"
 ShowVoiceButtons = "Off"
 MovieSkipInstance = "Off"
 BlockDrunkenSpam = "Off"
 AutoReleaseNoAshran = "Off"
 MuteMechsuits = "Off"
 MuteUnicorns = "Off"
 HideMiniClock = "Off"
 PowerBarY = 115
 AutoQuestCompleted = "On"
 NoBagsMicro = "Off"
 LeaPlusMailFontSize = 15
 NoFriendRequests = "Off"
 AutoRepairShowSummary = "On"
 AutoReleaseNoTolBarad = "Off"
 MuteMechSteps = "Off"
 WidgetTopScale = 1
 TipShowRank = "On"
 PlusPanelAlpha = 0
 MoveChatEditBoxToTop = "Off"
 MuteSniffing = "Off"
 MinimapY = -22
 MuteRockets = "Off"
 NoScreenGlow = "Off"
 VehicleY = -192
 DurabilityR = "TOPRIGHT"
 ShowCooldowns = "Off"
 DurabilityA = "TOPRIGHT"
 MailFontChange = "Off"
 ShowBorders = "Off"
 MainPanelA = "CENTER"
 BordersLeft = 0
 HideActionButtonText = "Off"
 BuffFrameR = "TOPRIGHT"
 EnableHotkey = "Off"
 MuteSunflower = "Off"
 MuteGameSounds = "Off"
 AutoRepairGear = "On"
 EditPlayerFrameScale = 1
 ManageTimer = "Off"
 WidgetPowerScale = 1
 HideTalkingFrame = "Off"
 AutomateGossip = "On"
 WidgetTopX = 0
 AutoQuestKeyMenu = 1
 NewCovenantButton = "Off"
 RecentChatWindow = "Off"
 hide = false
 NoTransforms = "Off"
 NoSharedQuests = "Off"
 AutoReleaseNoAlterac = "Off"
 TimerA = "TOP"
 MuteAerials = "Off"
 InviteFriendsOnly = "On"
 EditModeScales = "Off"
 BordersBottom = 0
 TransLantern = "Off"
 HideMiniZoomBtns = "Off"
 MiniShowBugSack = "Off"
 ManageFocus = "Off"
 VehicleScale = 1
 SetWeatherDensity = "Off"
 ClassColPlayer = "On"
 MuteHovercraft = "Off"
 EasyItemDestroy = "Off"
 InvKey = "inv"
 SaveProfFilters = "Off"
 MinimapSize = 140
 HideMiniAddonMenu = "On"
 HideErrorMessages = "Off"
 MuteSoulseekers = "Off"
 PowerBarScale = 1
 LeaStartPage = 5
 FriendlyGuild = "On"
 MinimapScale = 1
 TimerScale = 1
 AutoReleasePvP = "Off"
 HideMacroText = "Off"
 HideBossBanner = "Off"
 AutoResNoCombat = "On"
 WowheadLinkComments = "Off"
 TipHideInCombat = "Off"
 UseArrowKeysInChat = "Off"
 EditBuffFrameScale = 1
 ShowTrainAllButton = "On"
 FirstRunMessageSeen = true
 NoCooldownDuration = "On"
 SquareMinimap = "Off"
 WidgetTopY = -15
 NoRestedEmotes = "On"
 CombatPlates = "Off"
 ManageVehicle = "Off"
 MinimapA = "TOPRIGHT"
 TipBackSimple = "Off"
 ControlR = "CENTER"
 MuteReady = "Off"
 ControlY = 0
 ShowWhoPinged = "On"
 UseEasyChatResizing = "Off"
 NoAlerts = "Off"
 AutoQuestShift = "Off"
 AutoReleaseNoWintergsp = "Off"
 BuffFrameA = "TOPRIGHT"
 NoPetDuels = "Off"
 FasterLooting = "On"
 WidgetPowerA = "BOTTOM"
 ManagePowerBar = "Off"
 DressupAnimControl = "On"
 NoClassBar = "Off"
 SetChatFontSize = "Off"
 MaxCameraZoom = "Off"
 NoScreenEffects = "Off"
 MuteTravelers = "Off"
 HideBodyguard = "Off"
 AutoSellExcludeList = ""
 LockoutSharing = "Off"
 NoChatFade = "Off"
 TipCursorY = 0
 MuteBikes = "Off"
 AutoSellNoKeeperTahult = "On"
 FocusScale = 1
 ShowChatMenuButton =

**Comment by leatrix** [comment]
For the original Lua error, there appears to be a bug in the game code with the slash command system.  Entering any addon related slash command (from any addon) may cause a block taint error when entering and/or exiting Edit Mode.  This may explain your original issue.  The only workaround at the moment is to not enter any addon related slash commands (use the minimap button, keybind or macro).

The second issue is for 'Restore chat messages'.  Do you see this error every time you reload?

**Comment by leatrix** [comment]
The latest release includes a fix for the Lua error with 'Restore chat messages'.  The slash command taint is up to Blizzard to fix.
