### ISSUE TITLE
Chat window bugged

### ISSUE THREAD

**Issue by ToxxicApe** [leatrix/leatrix-plus#112]
this addon causing a UI error - chat bar is moved to the right

![grafik](https://user-images.githubusercontent.com/79103902/198071537-eba6b19e-9c08-4a43-bf16-2c2a20c139ae.png)

**Comment by ToxxicApe** [comment]
Version 10.0.00 - Retail

**Comment by leatrix** [comment]
Disable all other addons.  How does it look then?

**Comment by ToxxicApe** [comment]
looks still bugged

**Comment by leatrix** [comment]
Have a screenshot with only LTP enabled?

**Comment by ToxxicApe** [comment]
![grafik](https://user-images.githubusercontent.com/79103902/198076301-1b9dbaf8-ac86-4b5b-9c81-4f5fe8066ea7.png)
![grafik](https://user-images.githubusercontent.com/79103902/198076355-d820b22f-5c2d-45e4-8bbd-86efe17ee069.png)
https://i.imgur.com/0pmW6cM.jpeg
https://i.imgur.com/pVvrGkE.jpeg
![grafik](https://user-images.githubusercontent.com/79103902/198076536-50a9497b-9a33-47eb-ae2c-51e2ae6527e6.png)
![grafik](https://user-images.githubusercontent.com/79103902/198076595-4e07b768-19b4-4358-b893-7dfcc113dc77.png)
https://i.imgur.com/JXZNd3r.jpeg
https://i.imgur.com/XnVkGv5.jpeg
![grafik](https://user-images.githubusercontent.com/79103902/198076732-c4bfafe0-622c-457f-b279-5105299706ea.png)
![grafik](https://user-images.githubusercontent.com/79103902/198076785-25ba196c-aa4b-4816-8f26-4e8fc2b2251d.png)
![grafik](https://user-images.githubusercontent.com/79103902/198076832-47749938-65cb-4d8e-bf6d-440a24a6e1f5.png)

**Comment by ToxxicApe** [comment]
FYI . Bug is still there

**Comment by ToxxicApe** [comment]
https://i.imgur.com/kZoK0Z4.png

**Comment by leatrix** [comment]
Yes, it's noted.  Thank you for your report.
