### ISSUE TITLE
Feature Request: Allow Map Scaling Below 100%

### ISSUE THREAD

**Issue by EvanMichaels** [leatrix/leatrix-plus#114]
Current default map size is very large and the current UI editor doesn't allow scaling.

Leatrix Plus does, however by default only allows the slider to go between 100% and 200%.

Seems reasonable to support smaller numbers (probably down to 0.5 as the lower bound of the variable) to allow better customization. I have quickly changed MiniClusterScale locally for the time being and for my own personal UI I need a scale factor of around 0.7 just to get the map to be roughly the same size as the old default.

Thanks!

**Comment by leatrix** [comment]
In 10.0.01.alpha.5, the minimum cluster scale is now 50%.

**Comment by EvanMichaels** [comment]
Thank you very much!
