### ISSUE TITLE
Minimap button can't be disabled

### ISSUE THREAD

**Issue by Kryptaria** [leatrix/leatrix-plus#115]
On live, with no other addons enabled, there's a tiny "1" on the minimap. If you click it, it brings up a pop-up with "Leatrix Plus" and a lightning bolt, with a checkbox. Clicking this brings up the Leatrix Plus settings window. I have "Show minimap button" unchecked.

**Comment by leatrix** [comment]
https://github.com/leatrix/leatrix-plus/issues/110
