### ISSUE TITLE
New feature: Manage reputation frame

### ISSUE THREAD

**Issue by CMcFadyen** [leatrix/leatrix-plus#119]
It can't be moved with Blizz's edit mode (for now anyway), and it's right in the way of good information panel addons

**Comment by leatrix** [comment]
Feedback appreciated.  [Bartender](https://www.curseforge.com/wow/addons/bartender4) is a very good addon.  It features a movable XP/reputation bar (in Bartender, it's called the Status Tracking bar) and the addon is significantly better than Edit Mode.  Give it a go.
