### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by YWI** [leatrix/leatrix-plus#121]
When we scroll through the chat upwards to see a specific message I forget to click the button to drop it to the button. A feature that would scroll the c hat down the latest message after idle would be nice.
maybe if after 30 seconds of not scrolling the chat goes back down.

**Comment by Spiderkeg** [comment]
How are you dropping back down to the bottom?  I usually see an optional button that drops to the bottom of a scrolled chatbox, this isn't added by default and I don't see this as an option in Leatrix Plus... unless I'm missing something?

**Comment by leatrix** [comment]
Suggestions appreciated.

@Spiderkeg If you enable 'Hide chat buttons', the bottom button is hidden and you can click the chat tabs to scroll to the end of chat messages.
