### ISSUE TITLE
Request: Removing combat glow.

### ISSUE THREAD

**Issue by Natlyz** [leatrix/leatrix-plus#126]
**Hello!**

I'd like to ask or maybe even beg to add an option to remove all the new Blizzard's pulsing/flashing/glowing red combat effects from the Player/Target/Focus frames.

![rt56](https://user-images.githubusercontent.com/60573947/198707032-d56f5bdd-73a7-4310-b336-e47a9a4b3038.png)

It makes the game for me literally unplayable: not only that distracts me from the actual gameplay, but it also makes me dizzy. I want the frames in combat to look exactly like they do out of combat.

Please, consider adding such an option, if that's possible.

**Thanks 😊**

**Comment by leatrix** [comment]
You can use this:

`/run SetCVar("threatWarning", 0)`

0 disables the red glow.
1 shows the red glow only in dungeons.
2 shows the red glow only in party/raid.
3 shows the red glow always (default setting).

The game will save your choice automatically so don't forget that you have set this.  To go back to default, just enter:

`/run SetCVar("threatWarning", 3)`

**Comment by leatrix** [comment]
I don't know what you mean by pulse.

**Comment by Natlyz** [comment]
> I don't know what you mean by pulse.

Hello! Sorry, couldn't reply earlier.

https://user-images.githubusercontent.com/60573947/199298506-de666e56-5b02-4182-8da1-4aa1419453dc.mp4

That's how it looks during combat or when I right click an enemy NPC.

**Comment by Natlyz** [comment]
Hello! Sorry, couldn't reply earlier.

https://user-images.githubusercontent.com/60573947/199299245-378831cc-9e51-4bee-91f1-cb3a3a941f51.mp4

That's how it looks in combat or when I right click on an enemy NPC.

**Comment by leatrix** [comment]
You can use something like this:

`hooksecurefunc(PlayerFrame.PlayerFrameContent.PlayerFrameContentMain.StatusTexture, "Show", PlayerFrame.PlayerFrameContent.PlayerFrameContentMain.StatusTexture.Hide)`

Paste it into https://addon.bool.no/, add a title and you have your own red pulse remover addon.

**Comment by Natlyz** [comment]
> You can use something like this:
> 
> `hooksecurefunc(PlayerFrame.PlayerFrameContent.PlayerFrameContentMain.StatusTexture, "Show", PlayerFrame.PlayerFrameContent.PlayerFrameContentMain.StatusTexture.Hide)`
> 
> Paste it into https://addon.bool.no/, add a title and you have your own red pulse remover addon.

Thanks a lot! I guess I'm an addon author too now 😅
