### ISSUE TITLE
[Pull Request] Silver dragon for Self Portrait.

### ISSUE THREAD

**Issue by G1ZMO** [leatrix/leatrix-plus#127]
[UI-HUD-UnitFrame-Target-PortraitOn-SilverDragon.zip](https://github.com/leatrix/leatrix-plus/files/9890949/UI-HUD-UnitFrame-Target-PortraitOn-SilverDragon.zip)
![image](https://user-images.githubusercontent.com/757483/198707617-b14482d6-eaa8-4900-bbbd-cc475f7b7a44.png)
![image](https://user-images.githubusercontent.com/757483/198707680-18d12e28-337f-464b-89fd-7bd1364846f4.png)
![image](https://user-images.githubusercontent.com/757483/198707863-d4ad623c-3713-45d1-b8e6-8567916c679d.png)

**Comment by leatrix** [comment]
Suggestions appreciated.

**Comment by leatrix** [comment]
In 10.0.12.alpha.2, you can choose a rare (silver) chain in the configuration panel dropdown menu.

**Comment by G1ZMO** [comment]
<3

**Comment by G1ZMO** [comment]
> In 10.0.12.alpha.2, you can choose a rare (silver) chain in the configuration panel dropdown menu.

Why is there no winged version of this icon? You used to have a Winged Silver Elite.
![image](https://user-images.githubusercontent.com/757483/202825567-e009ed8c-09e5-4644-a453-e5ee262fb66e.png)
