### ISSUE TITLE
Loot error with faster loot option turned on.

### ISSUE THREAD

**Issue by Hybrid2177** [leatrix/leatrix-plus#128]
Hi All, There seems to be a problem with the faster loot option, if you turn it on it will use the default loot location (even with the "open loot window at mouse") and once the loot is gone the loot window will remain on until you hit escape. Turning off the addon or turning off faster loot seems to solve the issue.

However I also tried it with just leatrix running and not other addons, and while the loot window went away with faster looting enabled, it still seemed to ignore the "open loot window at mouse" feature.

Something seems to be up with it?

Thanks

**Comment by Greybaine** [comment]
Can confirm. Experienced this on my end as well.

**Comment by leatrix** [comment]
https://github.com/leatrix/leatrix-plus/issues/113

https://us.forums.blizzard.com/en/wow/t/no-quality-loot-nil-error/1380801/7
