### ISSUE TITLE
Player and Target Frame size

### ISSUE THREAD

**Issue by chrischtili** [leatrix/leatrix-plus#13]
...are always reset to a smaller value after login. I do have to "/reload ui" manually.
Then it is ok
![After login](https://user-images.githubusercontent.com/4641474/106236676-a6eb7100-61fd-11eb-831c-e7e657318f32.png)
![After reload ui](https://user-images.githubusercontent.com/4641474/106236691-ad79e880-61fd-11eb-85b5-7a5fc5e59444.png)

**Comment by leatrix** [comment]
Disable other addons.  It should work.  Enable other addons gradually to find the addon causing the problem.
