### ISSUE TITLE
[Question] Green Health Bar Color to Class Color 

### ISSUE THREAD

**Issue by G1ZMO** [leatrix/leatrix-plus#132]
Is it possible to add another function paint over the green color health bar, to the color of the class?

![image](https://user-images.githubusercontent.com/757483/198901288-2e2f79f1-8613-41bc-b16e-13fceed1f8a9.png)

Like This:
![image](https://user-images.githubusercontent.com/757483/198901278-6eaf949c-af3e-4de8-8644-972c38764938.png)
![image](https://user-images.githubusercontent.com/757483/198901313-354476fc-03fc-4aea-923f-2bd224aa11a5.png)

**Comment by KiloViktor** [comment]
Yes please, currently using a second addon to get this function. Would be great to have that option.

**Comment by leatrix** [comment]
Suggestions appreciated.
