### ISSUE TITLE
Idea for Leatrix

### ISSUE THREAD

**Issue by xapollyon** [leatrix/leatrix-plus#133]
I couldn't find a page where we had an idea for this great addon, so I am typing it here.

Is it possible to add an option to auto hide/close the quest objectives window on combat?

Then have it auto open when out of combat, or manually open it?

Like this addon: www.curseforge.com/wow/addons/kobjectiveshide

The reason I ask is that addon has not been updated for some time, and if the option can be added into Leatrix then it is also 1 less addon to run in memory

Thanks

**Comment by leatrix** [comment]
Feedback appreciated.
