### ISSUE TITLE
Request: "Automate Gossip" w/o needing a modifier

### ISSUE THREAD

**Issue by BBQSalad** [leatrix/leatrix-plus#134]
I appreciate you having the 'automate gossip' feature, however would it be possible to extend its capabilities a bit to where the automation is the default, while the modifier is only needed to 'disable' automation?  

I can understand while others may like the default/current implementation, so a 'toggle' may be in order.

Thank you...

**Comment by leatrix** [comment]
Suggestions appreciated but there does need to be a key requirement.

**Comment by BBQSalad** [comment]
Ahh.. that's a shame.  I'm guessing this must be a Dragonflight change?  I used an app back in Shadowlands (Auto Gossip by SunfyreBlazing) and the modifier wasn't required.  I was hoping the same would be true in DF.

Oh well, I appreciate your time.  Thank you for all that you do.
