### ISSUE TITLE
Feature Request - More information on 'Automation' page 

### ISSUE THREAD

**Issue by jsaue003** [leatrix/leatrix-plus#136]
Please add more detail on the automation page, shown below. it's unclear how it will handle quest rewards, i.e. if there's mail, leather, gun, staff, rifle. Does it simply choose most expensive, does it not choose at all? No info included in addon settings at all :-(

![image](https://user-images.githubusercontent.com/32148757/199032792-8f265666-bfac-42fd-b140-2dc2cf807733.png)
![image](https://user-images.githubusercontent.com/32148757/199032828-a76e01ef-5a5e-47a0-8ef2-ef202e696124.png)

**Comment by leatrix** [comment]
It turns in quests automatically.  As in, it clicks the buttons for you so you don't have to.  But it doesn't choose quest rewards for you.  You choose your own quest rewards just like always.
