### ISSUE TITLE
Chat frame bug?

### ISSUE THREAD

**Issue by Feper24** [leatrix/leatrix-plus#138]
Hi, right away after logging in I'm experiencing the following LUA error which prevents chat from working:

7x Interface/FrameXML/FloatingChatFrame.lua:1262: attempt to perform arithmetic on a nil value
[string "@Interface/FrameXML/FloatingChatFrame.lua"]:1262: in function `FCF_SavePositionAndDimensions'
[string "@Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua"]:3927: in function <Interface/AddOns/Leatrix_Plus/Leatrix_Plus.lua:3924>

A simple /reload fixes the issue, but I was told this isn't a tainted error but a leatrix "pure" one. These are my settings:

![image](https://user-images.githubusercontent.com/60163442/199358363-6a045ac2-ba4d-4b37-a383-254a87920d64.png)

Thanks for your work & time.

**Comment by leatrix** [comment]
Thanks for your report.  It's caused by 'Hide chat buttons' as a result of changes made to the game code in Dragonflight.  Please try 10.0.06.alpha.4.  In this update, for now at least, the bottom button will no longer be hidden.
