### ISSUE TITLE
Feature Request: Toggle to Auto-Collapse the Player Buffs frame.

### ISSUE THREAD

**Issue by ZINK-ZINK** [leatrix/leatrix-plus#143]
This seems like the kind of feature you might be willing to implement. The default UI Player Buffs frame forgets that it should be collapsed after every reload. I'm just asking for a LTP option that sets the default behavior to "collapsed" or forces the frame to remember the last state after reloading. 
Pictures of the frame I mean.
![WoW Buff Collapse 1](https://user-images.githubusercontent.com/96964163/200130854-4e44f979-4ea0-4ba5-9b87-f930c45efad1.jpg)
![WoW Buff Collapse 2](https://user-images.githubusercontent.com/96964163/200130861-da6c5c95-31c3-4cc2-bd2e-181c0bba4ff9.jpg)

**Comment by leatrix** [comment]
It's not something I planned to add but I did look at advising you how to do it yourself.  Unfortunately, setting that button state through code upsets Edit Mode and taints the UI (which then causes errors).

**Comment by ZINK-ZINK** [comment]
I appreciate you checking into it. Sounds like Blizz spaghetti'd it good. 
That means the only realistic option to change the behavior is to completely replace the Aura Frame with an Addon like Raven right? It can't be controlled directly, only hidden and replaced.

Even though I use a ton of addons I really wanted to like the new default UI, but man every nice feature they added seems to come with a catch. It's like they just scooped up all the UI code and dumped it into one big messy bucket together, like sure it's all in one place now but I gotta knock everything over just to get to what I'm looking for lol

Back to Raven then I suppose. You're doing a great job btw, I've been following your battle vs the Loot Frame in the patch notes heh
