### ISSUE TITLE
Faster loot.

### ISSUE THREAD

**Issue by Natlyz** [leatrix/leatrix-plus#144]
**Hello!**

It seems the recent update has broken the faster loot, getting these again:

_NO QUALITY LOOT nil, currencyIDnil, quantitynil, slotIndex2, isCoinnil
NO QUALITY LOOT nil, currencyIDnil, quantitynil, slotIndex3, isCoinnil
NO QUALITY LOOT nil, currencyIDnil, quantitynil, slotIndex4, isCoinnil_

**Help 😰**

**Comment by leatrix** [comment]
> 10.0.08 - 7th November 2022
> - The 'Fix Blizzard's NO QUALITY LOOT spam' setting (part of 'Faster auto loot') is now disabled by default.  If you use this setting, you will need to enable it again after installing this update.  If you use XLoot, the setting will now be locked out.  As a reminder (and this is noted in the setting tooltip), if you use a loot frame replacement addon, you may need to disable the 'Fix Blizzard's NO QUALITY LOOT spam' setting.

Whenever something changes, it will be listed in the change log.

Some people use loot frame replacement addons where the 'Fix Blizzard's NO QUALITY LOOT spam' setting probably won't work or might cause issues.  So the setting is now disabled by default and in 10.0.8, you will need to enable it again to continue using it.

It's ironic that in the expansion where you can supposedly play with fewer addons, you need an addon to fix something as pointless as this.

**Comment by Natlyz** [comment]
Aha, thanks! My bad, didn't check the changelog.

> I'm still hopeful that this fix is only temporary because it's ironic that in the expansion where you can supposedly play with fewer addons, you need an addon to fix something as pointless as this.

True, I need like 4 addons and a script you gave me only to make the Player/Target/Focus frames look and work how I want them to, and they still look like default UI.

https://user-images.githubusercontent.com/60573947/200531509-78d8d0b7-9639-43eb-9b3d-bee303da706e.mp4

Removed threat + removed combat glow + remvoed buffs/debuffs + replaced buff frame with Raven addon + moved castbars to a fixed position + trying to remove the misalligned and outdated shield icon for protected casts...

![657756576h](https://user-images.githubusercontent.com/60573947/200532231-e4f6cdd7-1a79-4d60-983c-d053b4d65a94.png)

**Comment by leatrix** [comment]
Your character appears to be [sleeping](https://www.grammarly.com/blog/zzz-meaning/#:~:text=Zzz%20is%20an%20onomatopoeic%20representation,Zs%2C%20which%20means%20to%20sleep.).  You can use 'Hide rested sleep' ('System') to wake her up if you like.  You will still get the rested glow.  Just not the sleeping zzz.

**Comment by Natlyz** [comment]
> Your character appears to be [sleeping](https://www.grammarly.com/blog/zzz-meaning/#:~:text=Zzz%20is%20an%20onomatopoeic%20representation,Zs%2C%20which%20means%20to%20sleep.). You can use 'Hide rested sleep' ('System') to wake her up if you like. You will still get the rested glow. Just not the sleeping zzz.

Thanks, that's because I'm in the Covenant hall that is a rested area. Btw, combat glow and rested glow seem to share "code". If I disable the combat glow I also lose the rested glow. In the test video above the combat glow is actually enabled but you can't see it behind the rested glow.

**Comment by leatrix** [comment]
Yes, but zzz means sleeping, not resting.

If you want to hide the combat glow but keep the rested glow, you can use something like this:

```
hooksecurefunc("PlayerFrame_UpdateStatus", function()
	if (IsResting()) then
		PlayerFrame.PlayerFrameContent.PlayerFrameContentMain.StatusTexture:Show() -- Show glow when resting
	elseif (PlayerFrame.inCombat) then
		PlayerFrame.PlayerFrameContent.PlayerFrameContentMain.StatusTexture:Hide() -- Hide glow when in combat
	end
end)
```

**Comment by Natlyz** [comment]
> 
Aha thanks! That works perfectly 😊

I'm currently trying to get rid of the protected cast shield with the help of google, but it's not going great. I'm not a programmer. Like at all.
```
hooksecurefunc('CastingBarMixin',SetUnit, ShieldGoner);
if unit == focus and unit == target then
self.showShield = false;
end
end;
```
Maybe you could tell me what I'm doing wrong? But it's fine if you don't have time for it!

**Comment by leatrix** [comment]
You can just remove the texture:
```
TargetFrameSpellBar.BorderShield:SetTexture("")
FocusFrameSpellBar.BorderShield:SetTexture("")
```

**Comment by Natlyz** [comment]
> TargetFrameSpellBar.BorderShield:SetTexture("")
> FocusFrameSpellBar.BorderShield:SetTexture("")

Thanks a lot! You've just saved me from several days of suffering 😅

**Comment by leatrix** [comment]
I'm happy to report that Blizzard have finally removed their NO QUALITY LOOT spam code from game version 10.0.2.46702 so the LTP setting to disable the spam has been removed in the latest alpha (currently 10.0.12.alpha.2).

**Comment by Natlyz** [comment]
> I'm happy to report that Blizzard have finally removed their NO QUALITY LOOT spam code from game version 10.0.2.46702 so the LTP setting to disable the spam has been removed in the latest alpha (currently 10.0.12.alpha.2).

Thanks for info! Why would they even add something like that? aha.

**Comment by leatrix** [comment]
Who knows?  Probably to deter people from using fast loot so that they can promote their own loot frame (which has been redesigned in Dragonflight but is still as slow as it ever was).  Blizzard can be very devious and sneaky at times.
