### ISSUE TITLE
Durability status not showing

### ISSUE THREAD

**Issue by nanrector** [leatrix/leatrix-plus#146]
Hello!
Once I close the leatrix UI after selecting Durability Status and moving the green block, the status never shows up.   
Nancy Ü

![SC - 662 2022 11 09](https://user-images.githubusercontent.com/13437068/200979926-ead2f947-7a31-4b19-9d75-778ad360f398.jpg)

**Comment by leatrix** [comment]
It seems to work fine for me.  Does your character have red armor?  If so, and you reload your UI, does the armored man show up?  If not, does it show up after you disable other addons?

**Comment by nanrector** [comment]
No matter what my armor status is the armored man does not show up. I disabled all other addons and still nothing. Thanks!

**Comment by nanrector** [comment]
Does it only show up if one of my pieces is in the red? I'm at 77% and still nothing shows. I have used another durability addon for years which just shows my percentage even if it was 100%.   I was hoping to replace the other one with your addon.

**Comment by leatrix** [comment]
When one of your item slot pieces is yellow or red in durability, that item slot piece (and only that item slot piece) will show in the armored man.  This is how the default UI works and LTP doesn't change that behavour.  The 'Manage durability' option only lets you move the armored man frame.  It doesn't change how it works.  All of the 'Manage' options in the 'Frames' menu of LTP let you move frames which are only shown some of the time just like the armored man.

If you want to see a percentage of your durability, enable 'Show durability status' ('Interface').  Now when you open your character frame (C), put your pointer over the arrow in the bottom-right corner and you will see an itemised, color-coded percentage in the tooltip.  An overall durability percentage will also be shown in chat after your character dies.

**Comment by nanrector** [comment]
Thanks so much for clarifying that. I've used an addon for durability for years, so I forgot how it was supposed to work.  Ü
