### ISSUE TITLE
[Feature Request] Auto-Sell options: ilvl, unusable

### ISSUE THREAD

**Issue by Avijah** [leatrix/leatrix-plus#147]
Only reason I still use Scrap is the option to auto-sell (or destroy) items that have a low itemlevel compared to the stuff my char wears or has in the inventory. 
would be great to have it with a configurable slider to set the value of what is considered low itemlevel. Like „25 level lower“.

Unusable items should be sold/auto destroyed.

Special items that are low itemlevel and I want to keep can be added to the whitelist.

PS: love the addon, the best qol AND lightweight addons. Keep up the great work

**Comment by leatrix** [comment]
Suggestions appreciated.
