### ISSUE TITLE
Can't open menu

### ISSUE THREAD

**Issue by kingreboot** [leatrix/leatrix-plus#148]
I use a macro to open menu. /ltp is not working to open the menu.

**Comment by leatrix** [comment]
> 10.0.09 - 8th November 2022
> - Due to problems with Blizzard's code in Dragonflight, the '/ltp' slash command has been removed for the time being.  As a workaround, you can enter '/run leaplus()' to open Leatrix Plus.  If you want to pass a parameter, enter it in quotes between the brackets.  Example: /run leaplus("wipe").  This (hopefully temporary) change is necessary because of a bug in the game code with the slash command system.  Entering any addon related slash command will taint the UI and cause errors to show at some point.  Blizzard are aware of the bug.  When they fix it, the /ltp slash command will return.  You can assign a hotkey to open Leatrix Plus in the game keybindings panel and you can open Leatrix Plus using the minimap button if it's enabled in the Leatrix Plus settings menu so there are plenty of options.
>

**Comment by kingreboot** [comment]
thanks for the update, I tried that command but was not working. Found out I used Run instead or run and now works.

**Comment by leatrix** [comment]
The command is also shown in the built-in game interface settings panel so you can always refer to that.
