### ISSUE TITLE
Feature request: Mail rake (summary of total gold received in the mail)

### ISSUE THREAD

**Issue by UnaffiliatedGamer** [leatrix/leatrix-plus#150]
Looking around, I can see this feature in some of the mail addons out there, but I don't want everything else that comes with them. All I want is a summary in the chat window of gold looted from the mailbox. A peace of mind and awareness feature for when I just open up and click 'loot all' for my meagre AH postings or sending gold back to my bank alt. No idea why this isn't displayed in the default UI tbh...

**Comment by leatrix** [comment]
Suggestions appreciated.
