### ISSUE TITLE
Restore Chat function issue

### ISSUE THREAD

**Issue by nwferreri** [leatrix/leatrix-plus#152]
I'm having a problem with the restore chat option.  It doesn't seem to be working, but I know it's related to one of my other addons, because it works fine with just Leatrix active.

I went through my addons, enabling one at a time, but the restore chat option continued to work with all of them.  This leads me to believe that it's the interaction of multiple addons that is causing the restore option not to work.

I'm not sure how best to help track down this issue.  I have a ton of addons and there are so many combinations to try.

**Comment by leatrix** [comment]
List your addons.  Also remember that restore chat only works from a UI reload where your UI returns to you within 10 seconds.  So if you /reload and it takes longer than 10 seconds for your UI to appear, the chat messages will not be restored.  It's possible that if you have a very large number of addons, your UI could be taking longer than that to appear.

**Comment by nwferreri** [comment]
I wasn't aware of the 10 second time limit.  I timed a reload and it was about 20 seconds.  Guess that's the issue.

**Comment by leatrix** [comment]
I can do something with the timer.
