### ISSUE TITLE
Tooltip - show unit's target displaying multiple targets

### ISSUE THREAD

**Issue by Nillx** [leatrix/leatrix-plus#153]
I started seeing this today after 10.0.2, do you think its caused by LTP? 
![image](https://user-images.githubusercontent.com/34476875/202183516-1eb7ebc6-d365-4334-b211-fff8470d0a20.png)

**Comment by leatrix** [comment]
It seems to work fine for me so disable other addons and enable them again gradually to see if you have an addon that is causing this.  Let me know what the addon is so I can look into it.

**Comment by Nillx** [comment]
Alright ill take a look, it was happening in dungeons only.

**Comment by leatrix** [comment]
Did a dungeon earlier, target line seemed to work fine for me.

**Comment by Nillx** [comment]
Im confident to say that its causing when combined with Threat Plates. Was happening when i was using this addons:

LTP
Threat Plates
BugSack
BugGrabber

**Comment by Nillx** [comment]
It seems to happen when there is an active nameplate. Managed to get it happen when im inside an instance, (not in combat) targeting myself and turning my char around so nameplates pop up and disapear: 
![image](https://user-images.githubusercontent.com/34476875/202311102-b626d5b6-d3bf-4a84-9e0e-5caddb74e1b1.png)

**Comment by Nillx** [comment]
Got this as well, im not sure whats going on. Is it LTP or Threat plates bugging out the tooltip 

![image](https://user-images.githubusercontent.com/34476875/202316616-208cf367-3f20-4fb0-afce-51cca3aa6c23.png)

**Comment by leatrix** [comment]
The Rarity issue can be reproduced without LTP so it's not caused by LTP.  Maybe ask about this issue with ThreatPlates.

**Comment by Nillx** [comment]
Yeah i will do that.

**Comment by Nillx** [comment]
[Backupiseasy](https://github.com/Backupiseasy) is working on a fix for this.
