### ISSUE TITLE
class icons in portrait

### ISSUE THREAD

**Issue by Huf12** [leatrix/leatrix-plus#155]
i think this was once possible to do with this addon, would appreciate if it made a return. cheers

**Comment by Nelythia** [comment]
Seconding this, I have used classportraitsfinal in the past but it's code is from MoP so heavily outdated and causes lots of errors.
Since Leatrix already includes the class color frame option, I believe class icons should be possible too

**Comment by leatrix** [comment]
Suggestions appreciated.
