### ISSUE TITLE
How to disable the translation?

### ISSUE THREAD

**Issue by JulienGmd** [leatrix/leatrix-plus#157]
The french translation is not that great... A lot of parameters texts are too long to fit in their frame, so they doesn't give much information on their own, we have to hover the parameter to see the full description. Plus some translations makes no sense. How can I come back to the english version of the mod?
![Capture d’écran 2022-11-19 055715](https://user-images.githubusercontent.com/55960869/202834958-e11eea1d-febf-4984-9692-5dc8ba2b7255.png)

**Comment by leatrix** [comment]
This isn't currently supported but there is a workaround.  To use this workaround, make sure your Leatrix addons are up-to-date.

- Create a folder in your addons folder called **Leatrix_enUS**.
- Go [here](https://github.com/leatrix/leatrix-enus), click the green Code button and click Download Zip.
- Look inside the folder in the downloaded zip and you will see a few files.  Extract these files to your new Leatrix_enUS folder.  Don't extract the folder - only the files.
- You should now have a folder in your addons folder called Leatrix_enUS and inside there you should have a bunch of files.
- Fire up Wow (or **/reload** if you're currently logged into Wow).  You should see Leatrix_enUS in your addon listing and it should be enabled.  Log into Wow and all Leatrix addons should be in English regardless of your game locale.
- All games are supported (Dragonflight, Wrath, Classic Era).
