### ISSUE TITLE
[Feature Request] Move LFG Eye

### ISSUE THREAD

**Issue by fearkite** [leatrix/leatrix-plus#161]
Hey Leatrix!

First of all, awesome, aweeesome addon! LTP is the first addon I always download next to LTM.

The feature that I'd absolutely love that's currently missing is the ability to move the LFG eye. 
The current position in the bottom right of the screen is infuriating. I have no idea what Blizzard was thinking there!

I'd love to move it back near the minimap - or somewhere akin to that. 

Once again, thanks for developing LTP/LTM. You're doing gods work. :D

Thanks heaps!

**Comment by leatrix** [comment]
Suggestions appreciated.
