### ISSUE TITLE
Feature request: Minimap flush with edge

### ISSUE THREAD

**Issue by Crusherix** [leatrix/leatrix-plus#165]
I could move minimap flush with edge just a few week(s) ago.
Possible to get it back? Trying to move it within a pixel with edge but in picture you see how far it goes.
This is my corner down to the left, not able to drag it further to the edges.
![image](https://user-images.githubusercontent.com/117254919/203674218-2aa7acb7-436f-47fd-9b7c-2af7fd765f72.png)

**Comment by leatrix** [comment]
In 10.0.16.alpha.1, there is a new setting in the 'Enhance minimap' configuration panel to unclamp the minimap cluster.

**Comment by Crusherix** [comment]
Look at that, beautiful flush perfect with edge as all things should be. Thanks again!
![image](https://user-images.githubusercontent.com/117254919/203924765-e82102a0-a83d-482e-b470-536c4c64dcdf.png)

**Comment by leatrix** [comment]
It's working as you wished for?

**Comment by Crusherix** [comment]
Yes. :)
