### ISSUE TITLE
Feature update request: transforms removal options for dragonflight profession gear visueal buffs

### ISSUE THREAD

**Issue by MaloDrex** [leatrix/leatrix-plus#166]
Hello,

Thanks a not for this NEAT addon :D

The dragonflight professsion gear trigger a buff anytime we use profession skills.
Like this one: https://www.wowhead.com/beta/spell=394006/rockin-mining-gear

I would be nice to add those buffs to auto transforms removal options.
Thanks in advance for considering my request.

Best regards.

**Comment by leatrix** [comment]
In 10.0.16.alpha.3, there is a new setting called 'Professions' to remove Dragonflight profession buff transforms.  Currently it only supports Rockin' Mining Gear so let me know if it works ok for that and what other profession buffs should be included.

**Comment by MaloDrex** [comment]
Thanks for your fast answer.
Just tested on mining and it works! :D

**Comment by MaloDrex** [comment]
TYSM :D

**Comment by DaBear78** [comment]
Works great for me. More profession buffs:

https://www.wowhead.com/spell=394005/a-cultivators-colors
https://www.wowhead.com/spell=394007/ready-to-build
https://www.wowhead.com/spell=394008/a-lookers-charm
https://www.wowhead.com/spell=394009/fishing-for-attention
https://www.wowhead.com/spell=394011/dressed-to-kill

**Comment by leatrix** [comment]
Many thanks.  All added to 10.0.17.alpha.1.

**Comment by DaBear78** [comment]
https://www.wowhead.com/spell=391775/whats-cookin-good-lookin

But there is a problem with fishing... Removing the buff stopps the fishing instantly.

**Comment by leatrix** [comment]
In 10.0.18.alpha.3, the 'Professions' setting will no longer apply to fishing.  What about the other professions.  Are they ok with the buff being removed?

**Comment by DaBear78** [comment]
Skinning and leatherworking is fine, even with the buff removed. Did not try anything else yet.

**Comment by Calesta** [comment]
Using the latest version 10.0.21, the buff 'Spark of Madness' (Dressed in Alchemy Equipment) isn't removed with the 'Remove Transforms' -> 'Professions' option selected.

**Comment by Calesta** [comment]
^. Same with 'What's Cookin', Good Lookin'? (Dressed in Cooking Equipment).

**Comment by leatrix** [comment]
In 10.0.22, the 'Professions' setting should apply to all professions except fishing.  For crafting, that's blacksmithing, jewelcrafting, tailoring, engineering, enchanting, alchemy, inscription and leatherworking.  For gathering, that's herbalism, mining and skinning.  For secondary, that's cooking.

**Comment by Calesta** [comment]
Thanks Leatrix!  I thought you had already put all of that in based on the above.
