### ISSUE TITLE
Tooltip Target Issue

### ISSUE THREAD

**Issue by jsphglmr** [leatrix/leatrix-plus#167]
![image](https://user-images.githubusercontent.com/98359662/204109312-252260d7-0b7f-4e15-aaaf-59e5167938d2.png)

It does not produce a LUA error, but I've noticed it produces this type of spammed text occasionally.

**Comment by leatrix** [comment]
Are you using a nameplate addon such as ThreatPlates?

If you are using ThreatPlates, the author suggested trying the version linked here:
https://github.com/Backupiseasy/ThreatPlates/issues/368#issuecomment-1320207277
