### ISSUE TITLE
[Feature Request] Add Archdruid's Lunarwing Form screeches to mute mount sounds

### ISSUE THREAD

**Issue by fearkite** [leatrix/leatrix-plus#168]
Hey Leatrix!

The Lunarwing Form (class mount) of Druid's has a very annoying screeching sound, is it possible to add this to the features please? :D

Thanks heaps!

**Comment by leatrix** [comment]
Added to 10.0.28.alpha.1 (better late than never).  To switch to alpha releases, right-click the addon in your CurseForge App addon listing and change the release type to alpha.  You can change it back to release anytime.

**Comment by fearkite** [comment]
Works like a charm! Thanks so much... now I can actually use the form! YES! :D
