### ISSUE TITLE
Block Duel not working

### ISSUE THREAD

**Issue by blecaplol** [leatrix/leatrix-plus#169]
I have it check but people can still duel me for some reason.

**Comment by leatrix** [comment]
Are they in your friends list?  Friends are excluded from the duel block.
If you have the Guild checkbox checked (in the Social page), or the Communities checkbox checked, guild members and/or members of your communities count as friends too.

**Comment by blecaplol** [comment]
That's it. My bad. Didn't notice the Guild was checked. Thx!
