### ISSUE TITLE
Sell Junk auto - gold gained print no longer needed

### ISSUE THREAD

**Issue by Nillx** [leatrix/leatrix-plus#17]
Blizzard added a chat msg that shows how much gold you gained after selling stuff from your inventory and closing it. 
![dawdawadwawad](https://user-images.githubusercontent.com/34476875/110644634-fab68600-81bd-11eb-8f3a-498ee6672565.JPG)

**Comment by Sluimerstand** [comment]
Heh, I came here to report this too. Agree on this one!

**Comment by Natlyz** [comment]
Or maybe we need an option to hide blizzard's message.

**Comment by cybern4ut** [comment]
The gained by blizzard is not just junk, it's everything GAINED after you open your inventory and so on. I would say make an option to enable/disable junk message that way people who like the gained by blizzard can play with it and for those of us who don't really care about it then we can just have your option enable if it's possible that is.

**Comment by leatrix** [comment]
As cybern4ut highlighted, Blizzard's receipt message is not the same as Leatrix Plus sell junk message.  They exist for different reasons.

**Comment by Sluimerstand** [comment]
> As cybern4ut highlighted, Blizzard's receipt message is not the same as Leatrix Plus sell junk message. They exist for different reasons.

That is fair enough, however an option to disable those messages would be nice to have then.
