### ISSUE TITLE
Minimap tracking button missing. 

### ISSUE THREAD

**Issue by Oddwin** [leatrix/leatrix-plus#171]
Seems that the Minimap tracking button is missing, and there is NO option to toggle it in the settings. 

https://i.imgur.com/72JYBv3.png

**Comment by leatrix** [comment]
Show a screenshot of your minimap cluster (the entire thing including the header).

**Comment by Oddwin** [comment]
![WoWScrnShot_112822_180538](https://user-images.githubusercontent.com/17445787/204420694-2022ae12-b9a2-45c7-a4ed-e8a617f3a97e.jpg)

I don't even have a cluster... really.

**Comment by leatrix** [comment]
This is how it should look:

![image](https://user-images.githubusercontent.com/58888415/204421059-d47b2315-9d6e-4f46-8091-a3837a62252d.png)

The little button on the top-left is the tracking button.  The one on the top-right is the achievements button.  The zone text bar and the clock in the middle are both clickable.

You have an addon installed that is removing most of the minimap header.  If you're not sure which addon it is, disable all other addons and enable them gradually until you find the cause.

**Comment by Oddwin** [comment]
Ok.. after some trial and error.. Its a conflict with SUI. Checking now to see what in SUI is causing this issue.
