### ISSUE TITLE
Feature Request: Add Khadin to block auto turn in Ohn'ahran Plains

### ISSUE THREAD

**Issue by jfernandes93** [leatrix/leatrix-plus#173]
Hello.

I am writing this issue to request the addition of Khadin < Master Artisan > in Ohn'ahran Plains to the list of npcs to ignore auto turn in due to the possibility of selection of wrong quest to increase knowledge points for a specific profession.

I have done a test locally and the adition of line "or npcID == "193110"    -- Khadin (Ohn'ahran Plains)" to the function isNpcBlocked is working to block leatrix plus quest automation as intended.

Thank you for your time.

**Comment by leatrix** [comment]
Many thanks.  In 10.0.17.alpha.2, quests from Khadin <Master Artisan> will not be selected, accepted or turned-in automatically.  With any quest, if a quest requires gold, currency or a crafting reagent, the quest won't be turned-in automatically.
