### ISSUE TITLE
[Feature Request] Automatically turn in all quests, except with gear choices

### ISSUE THREAD

**Issue by TinySnowkitty** [leatrix/leatrix-plus#174]
Hi!

It could be really awesome if I could turn in all quests automatically, unless I need to make a choice. Kind of like the AutoTurnin mod.
Thanks!

**Comment by leatrix** [comment]
That's what 'Automate quests' does.  It turns in all completed quests automatically unless you need to make a choice.

**Comment by TinySnowkitty** [comment]
That's odd, because for some reason it doesn't do that for me, and in the description it also says it doesn't turn in quests that reward gold, rep and so on.

**Comment by leatrix** [comment]
It works fine.  If it's not working for you, disable other addons and test.

Make sure 'Turn-in completed quests automatically' is checked in the configuration panel and make sure 'Require override key for quest automation is not checked.


![image](https://user-images.githubusercontent.com/58888415/205189339-ee6f47ac-8dde-4b0c-9d71-b04cee53c181.png)

> in the description it also says it doesn't turn in quests that reward gold, rep and so on.

No it doesn't say that.  This is the option tooltip:

![image](https://user-images.githubusercontent.com/58888415/205189691-3ad07c0c-c059-40fb-a75c-42c26dfee9fc.png)


It won't turn-in quests that require gold, currency or a crafting reagent.  So if a quest requires you to spend gold, that won't be turned-in automatically.  If a quest requires you to give ore or herbs, that won't be turned in automatically.

**Comment by TinySnowkitty** [comment]
Oh okay, I misunderstood then! I'll test it again, thank you - and sorry 😅
