### ISSUE TITLE
Faster loot.

### ISSUE THREAD

**Issue by Natlyz** [leatrix/leatrix-plus#176]
**Hello!**

I have the latest version of LTP and it seems the faster loot isn't working, or at least it looks like the normal loot.
There are no errors I can share. It just doesn't seem to be working.

**Thanks 😊**

**Comment by leatrix** [comment]
It works fine for me.  Tested in Stockade.  Pull small numbers of mobs at a time and loot as you go.  There is a massive difference with faster auto loot enabled.

Two things you can try.

- Make sure you aren't using another faster looting addon at the same time.  
- Install the latest 10.0.18.alpha.x, click the cogwheel next to 'Faster auto loot' and reduce the delay (try setting the delay to 0.0) and let me know how that goes.  To switch CurseForge App to the alpha channel, right-click Leatrix Plus in your addon listing and change the release type to alpha.  You can change it back to release anytime you like.

**Comment by Natlyz** [comment]
Thanks! The alpa version works for me 😉
