### ISSUE TITLE
Feature Request - empty icon disable for first panel

### ISSUE THREAD

**Issue by born2slip** [leatrix/leatrix-plus#177]
Hello
Can you add a small feature for the default UI? There is a problem in the first action bar - no option to show/hide empty buttons. 
And other panels have.

![no_butto1n](https://user-images.githubusercontent.com/45132595/205449287-138ab71a-c883-41ab-983f-abca85ba54b0.png)

**Comment by leatrix** [comment]
This is something that Blizzard should fix with their Edit Mode system.
