### ISSUE TITLE
Feature Request: Dragonriding talents for alts

### ISSUE THREAD

**Issue by zeenk** [leatrix/leatrix-plus#178]
Since the dragonriding talents are not selected for alts by default could we possible get an option to auto select all talents when u open the dragonriding UI or a button that auto fills them in? (just minor annoyance :p)

My friend tried to help me doing it with a macro but it requires 7 clicks to fill up all but not sure if you can make it select all with addon code instead

/run local c=C_Traits.GetConfigIDBySystemID(1) for i,n in ipairs(C_Traits.GetTreeNodes(672)) do local f=C_Traits.GetNodeInfo(c, n) if #f.entryIDs<2 then C_Traits.PurchaseRank(c, n) else C_Traits.SetSelection(c, n, f.entryIDs[1]) end end

**Comment by leatrix** [comment]
Suggestions appreciated.

**Comment by shot1330** [comment]
> 

is that macro works?

**Comment by zeenk** [comment]
> > 
> 
> is that macro works?

Yeah just open the dragonriding talents ui and copy paste the macro 7 times

**Comment by zeenk** [comment]
Nevermind actually, the macro doesn't seem to save the selected talents 🤔

**Comment by shot1330** [comment]
> Nevermind actually, the macro doesn't seem to save the selected talents 🤔

Hello Sir

Could you figure out One Macro that Press Starter Build when i'm leveling?

**Comment by shot1330** [comment]
> 
You can Save Talent by this

/run local c=C_Traits.GetConfigIDBySystemID(1) for i,n in ipairs(C_Traits.GetTreeNodes(672)) do local f=C_Traits.GetNodeInfo(c, n) if #f.entryIDs<2 then C_Traits.PurchaseRank(c, n) else C_Traits.CommitConfig(c) end end

**Comment by leatrix** [comment]
I am not able to test this so let me know what happens:

- Right-click Leatrix Plus in CurseForge App and change the release type to alpha.  You can change it back to release anytime you like.
- Update the addon to 10.0.25.alpha.7 or higher and **/reload** your UI.
- Open the dragonriding traits UI and enter **/run leaplus("traits")**.

**Comment by zeenk** [comment]
Doesn't work :/

**Comment by leatrix** [comment]
Is the traits window open when you enter the command?  If the traits window isn't open, the command won't do anything but it will show you a message in chat to tell you to open the traits window.  The command will only work if the traits window is open.

Something else you can try.  Open the traits window and look for the traits that have two choices (because those are the traits that I can test).  For those traits, choose the right-side trait.  Now, with the dragonriding traits window still open, enter the command.  For those traits that have two choices, the command should choose and save the left-side traits.  For me, that works.  Does it for you?

**Comment by zeenk** [comment]
https://user-images.githubusercontent.com/68170439/209588748-b96b103a-be17-4c82-9dcc-532af516c843.mp4

I selected the first choice talent (right one) and when I ran the command after that I changed it to the left one. but it didn't change anything else.

**Comment by zeenk** [comment]
Would it be possible to add some sort of auto "/click StaticPopup1Button1" only when this frame is open so we don't have to confirm the talents when we click them?

![2023-01-15_02-02-09](https://user-images.githubusercontent.com/68170439/212503860-888747fd-c843-4cc3-9010-42281eef4ab0.png)

**Comment by leatrix** [comment]
I was able to test this finally.  Install 10.0.30.alpha.4 (or later), reload, open the traits window and enter **/run leaplus("traits")**.  It should select all traits instantly providing you have the currency.  Where there is a choice of two traits, it will select the second one.  Tested it and it seems to work fine.

If you run the command on a traits window that is already filled in, it will only change the rows that have two trait choices (if needed).

In 10.05, it's likely that the **/ltp** command will return so the command should be **/ltp traits** when that happens.

**Comment by zeenk** [comment]
![2023-01-15_03-43-07](https://user-images.githubusercontent.com/68170439/212520215-1226fd4c-c88c-4c81-a0c4-99663f7018ff.png)

Upload still being processed? I don't see alpha version

**Comment by leatrix** [comment]
Looks like CurseForge packager is having problems right now.  All files released in the last few hours are still processing.  Just have to try it again later.

**Comment by zeenk** [comment]
Yeah found it on github instead, tried it and it works! awesome thank u so much :)
1 minor thing, would it also be possible to add a button somewhere on the frame that runs the command when you click it making it a bit easier, also for new users that maybe don't know about the command :) if not that's fine too, thx again ^^

Something like that (pro paint skills)
![2023-01-15_03-53-18](https://user-images.githubusercontent.com/68170439/212520585-2256281e-97df-4b43-a155-d1d208ec947f.png)

**Comment by leatrix** [comment]
It's likely to stay as a slash command because then it's completely optional.  The problem with adding an interface element is that would then make it a UI change so it would require an option in the configuration panel to toggle it.  It's not worth it for something that only needs to be done once per character.

**Comment by zeenk** [comment]
Yeah understandable, no problem 👍

**Comment by zeenk** [comment]
Made a clickable weakaura when the frame is open that runs the command when u click it, problem solved 😌 
![2023-01-15_09-56-13](https://user-images.githubusercontent.com/68170439/212532010-f916e8a0-a3c9-44ec-a3f6-9fab73d42b43.png)

```
!WA:2!nA1ZVXnXx8gfqimQOUPLOI03dMvIOejuinq7HkvbR3SBt63TzdEDibvQ2DS9ZRhI9mUZmEZp4cKdOEdP9gx3ZCApWzuoJ(kRvFv5E)lafjUZBgVBslvfHpypZ7hZ7959RXZ1CH0fcxi8PlnIgWzD45Ia4)Cf3aEcx8G5XhXXTJIKGAZp3F)QxbFgtybXCXoCkt5xVX2EnCNeW5jH8dzDoKMb9oB22gH9Hybjqr5m5DCLkIqz5hrzuzSLd(rT0WqE3GCPIN2ZV87rZ9t0iBgxztYfKUaBWQbj0Gdi(jqtbjfSvXaZYgFs4bKeBH99Uuub0hnMH7Rt97zxxaev5ULR6KRuCw1pYUAD0lZtHliiqADGGCbuZaHsgEqAwcQE1vSTTawOL1RXq3TdOQLKycuYLx5FumLsq9ZvO7Oood0otkjqWR(61YfbQubIMCrDnh5YvBbrQsFCdm4J6A9V0MgBPGJuOHF0JS(yroZobizj54PQeeQsIN2JF8kNIQ0VpiKV7sIPlFMJ2JlU6ZL5(WaGP6KhfrpAC361641TJxnxVXLj2UX0qWvrtHqxJK(BcKev8fAUJaqnD7StJwTCYXQdFmqFmik5kZU2U7SrnVgD3DRU7T1g3VH3PYmijzRqP1mtO9fFSotLlDdIHGdkwS4QzPr5mtgeZc6kdS(6(ade0apn4klliSWxL6D3s2jgdMlVYLvD6hbOYfmBLihm001bMAb8XLHkkTgfc(yOWd9iXMnATtZDBnmNnnQzLvr3wma8k3)qEi8Zx5CSsbemsYxIHy0D)2ZpaGSAikduUeeaXdLqsKPIQ4nrdirGkWAX4rym01u6lFWIfvMGB9jbh0xWZzHp9gzlOZUDLXeSTC)Yg65YEFdrZRiUiLGcmDHdJZGHxWoRslGGWLKKyRijLjJx4eRBMwm3CZn)ZlPoZjDQTRx7SRBisYXeecIG9OHQyNA42ZlTn9ii0q87NuoB5RM6HNz4)nyQLgDmcySifbRhs0z72B3OOIaXPwMrgbVCO1WPGIPYUwtb9e7ViNeIbkITN3lflMzPjgAhYfH7jizNU30fLoWaQKIDo9MI5xy(3zT3fh)11PTNx7ho5cJ2HEc8btXY(VKf0CnveOIT2A7gpBs)e(HnfWtYbwWX78gRT663UexAgNLlH7NmnahFQMKw7j(MU82dab2GmstUfW6RIFVX61Za1W(Zu1eum8M5oo6nXgR7fJJgyGuoVrHo4mvOCzlksUI58DWiciIJg7Bw0vIqC(Ikd1fAgkNnLrWL1ctPml8ntvaVviRsNNKteGDZCSMAVyQcbvjBEPd6hd0(XkWjHtc)LjyGOBgO8jkvcepwV9eSgf7975xwsUOBAEIIA5gKqKYflaRtNjvSJ2DxYxsz9tGI1qEMdCaGqpb2LIcG9yADgPPhWtrdfB0xRzpXuB5S(TU16(sZTK(00mUalWkZZMXfMxzvELXiJkVwsN7C03ZoKWO6Ebo7ofVDZZaIe6OeMu4BvuPyTjH62AKTzGMqcOoHYt1YPpJI1CsjuwZIdnsxCuXXfNGFT(7ugtzLn04rT4yCza0WmlnEK(ePMlMTMGTMicANvUnBbe31NEfooycN8a9CoHZt38Z(TL)ZZ(XV(dxpNgoUHQHQ2)vwlkD)rkEWGYzw3CUFyuvAy213qq6ZzU0qmO7vo0WLKKftMFCKoMGagBiFNZFHWNgB(DQ72OX2UhQhia(OBgr7BjOm95J)nXrt)DKF94X)(3H)osrEVXHuP(MITqHVzZ)3FC6S))Ox2nMTup0ydQuFdyy8cs3BV6NS6NUWG))()1p``` 

If anyone else also wants this and sees this thread ^^
