### ISSUE TITLE
Manage power bar/ frames = Not working

### ISSUE THREAD

**Issue by MIKBT** [leatrix/leatrix-plus#18]
I love the addon and the fact you can make bigger the frames and size. But when I try to move the power bar down and make it bigger it does not do anything. The bar remains the same and in the same place. I would like to move it down and make it a big bigger so the combat text does not covered. Many thanks!

**Comment by leatrix** [comment]
Disable all other addons.  Does that fix the problem?  Enable other addons again gradually until you find the addon preventing Leatrix Plus from modifying the power bar.

**Comment by MIKBT** [comment]
I have just deactivate all the addons and only turn on leatrix. It does not fix it. I can not change location or size. On the photo i try to move it to another location and it does not react. Same with the size, I have it to 140% and still looks the same.
![image](https://user-images.githubusercontent.com/80466302/110820888-6fa1c280-8287-11eb-8944-d8f6ea6d0ae5.png)

Thanks for responding.

**Comment by leatrix** [comment]
That looks like the Personal Resource Display (in the 'Names' menu of interface options).  The 'Manage power bar' doesn't modify that.  It modifies the Alternate Power Bar which is a situational bar that appears for certain encounters.

Example, the power bar appears here for The Stone Guard in Mogu'shan Vaults.
![stoneguard](https://user-images.githubusercontent.com/58888415/110856338-6d535e80-82af-11eb-95c8-bc91280c6eb1.jpg)

**Comment by MIKBT** [comment]
Alright, sorry. I thought was that... Is there any chance that leatrix addon could add that feature in the future as well as one for the focus frame? 

Thank you very much and sorry about the mistake

**Comment by leatrix** [comment]
An option for the focus frame is in the latest alpha (at least 9.0.21.alpha.2).
https://www.curseforge.com/wow/addons/leatrix-plus/files/all
