### ISSUE TITLE
Accept Resurrection makes you release.

### ISSUE THREAD

**Issue by gotex007** [leatrix/leatrix-plus#180]
"Accept Resurrection" makes you release (and end up at the start of the dungeon) in dungeon content that isn't M+ or Raid. Could there at least be an option so I don't auto release the instant I die in a normal, heroic, or mythic dungeon? I don't want to have to turn the option on and off depending on the content I'm running.

**Comment by leatrix** [comment]
'Accept resurrection' only accepts resurrection requests automatically.  It doesn't release your spirit.  If someone resurrects you, the resurrection request will be accepted automatically.  That's all.

'Release in PvP' does release your spirit but it only works in battlegrounds (with additional settings for it to work in Alterac Valley, Wintergrasp, Tol Barad (PvP) and Ashran).  It doesn't release your spirit in any other location.

**Comment by gotex007** [comment]
It does though. In a normal, heroic, or mythic (non-key) dungeon it instantly releases my spirit on death. In M+ and raid it doesn't and properly waits for a healer's resurrection to trigger.

**Comment by leatrix** [comment]
It works fine for me.  My character just died in mythic Ruby Life Pools (M0) and there was no automatic release.  Disable all other addons and test it again.

**Comment by gotex007** [comment]
You're right. It's a Weakaura.
