### ISSUE TITLE
Hotkey

### ISSUE THREAD

**Issue by Dzahboss** [leatrix/leatrix-plus#181]
Hello, the hide hotkey is not working

**Comment by leatrix** [comment]
Do you mean 'Hide keybind text' and 'Hide macro text'?  Both work fine for me with the default UI action bars.

If you are using an addon to replace the action bars (such as Bartender), you need to check the settings of that addon to hide keybind and macro text.

**Comment by Dzahboss** [comment]
I use the default UI and doesnt work since 5 days :/

**Comment by Dzahboss** [comment]
I have the addon in french is maybe this the problem ?

**Comment by Dzahboss** [comment]
i find is Bindpad the addon :(

**Comment by leatrix** [comment]
BindPad has its own hotkey text setting.  Open /bindpad and uncheck Show Hotkeys.
