### ISSUE TITLE
Disconnects since latest update

### ISSUE THREAD

**Issue by Neischa** [leatrix/leatrix-plus#184]
Hi, it seems like your addon is causing disconnects (at least for me) since today. When I log into game, i got dc in about 5-10s and if I disable leatrix plus, its all fine... No error message. Could you please look at that? Thanks!

**Comment by V1P3R** [comment]
Same issue here

**Comment by Neischa** [comment]
Errr, sorry for false information, on the end it seems issue was wow itself, todays update fucked up something and you have to do Scan and repair of your wow to fix it. LTP has nothing to do with that, it was just biiiig coincidence so sorry for that:)
