### ISSUE TITLE
annoying sound 

### ISSUE THREAD

**Issue by blecaplol** [leatrix/leatrix-plus#188]
hi there is this duck sound "quacking" throughout DF zone randomly as u are near them. 1 example is over in the bank at valdrekken.
https://www.wowhead.com/npc=188844/humduck-livingsworth-the-third
https://www.wowhead.com/sound=200485/mon-duck-pissed-01-200485
maybe u can find it faster and easier than me and add those sound under "Mute game sound"

second set of sound comes from the 500 achievement mount probably on your list not sure.
https://www.wowhead.com/beta/spell=376912/otterworldly-ottuk-carrier#sounds
https://www.wowhead.com/beta/sound=201519/filedata-4631768

**Comment by leatrix** [comment]
> 10.0.24.alpha.1 - 17th December 2022
> - For 'Mute game sounds' ('System'), you can now make ottuks quieter.

Untested so let me know if you have any issues with it.

**Comment by leatrix** [comment]
> 10.0.34.alpha.3 - 30th January 2023
> - For 'Mute game sounds' ('System'), you can now mute duck greetings.  Use this if you would like to do your Valdrakken banking in peace.
