### ISSUE TITLE
Tavio is stealing my nets

### ISSUE THREAD

**Issue by GitMestra** [leatrix/leatrix-plus#189]
After completing the first tier of Iskaaran nets, the next one requires 6 of the same mat: Battered Imbu-made Net. But the crafting NPC has also now got a repeatable turn-in to get rid of these nets and Leatrix auto-completes them.

I know I can use the modifier to prevent this, but I can easily either forget or click him in passing. 

Is it possible to flag him to require player confirmation of the turn-in - and probably others he will have in future?

The specfic quests are the "Contribute Supplies: ..." listed at:
https://www.wowhead.com/npc=195935/tavio#starts

**Comment by leatrix** [comment]
> 10.0.23.alpha.3 - 14th December 2022
> - For 'Automate quests' ('Automation'), quests which require Blizzard account-bound items (and currently exist in the game at this moment in time) will no longer be automated.

In CurseForge App, you can switch to the alpha channel by right-clicking the addon in your addon listing and changing the release type.  If you come across any future requests like this which require Battle.net account-bound items, let me know and I can add them in.

**Comment by GitMestra** [comment]
Thanks for the update. I have alpha3 installed, but I'm not sure how to check function. I don't have any of the nets at the moment, He still auto-starts the quest ... it makes me nervous. The nets take ~100 casts to get. 

Is the automation set for BoA items like for cash or old order resource ones where it would go through but not hit the Complete?

**Comment by leatrix** [comment]
Sorry I should have clarified.  Yes, it works the same way as gold/currency/crafting reagent.  When turning in the quest, it checks to see if the item required for the quest is a BoA item (that the addon is aware of).  If it is, it stops the automation.  It doesn't interfere with accepting the quest so that will still be automated.

**Comment by GitMestra** [comment]
Excellent. Sounds like how I imagined. 

I am not sure why this turn-in quest exists prior to the items having no use - or even exists at all. Maybe it shouldn't. Previous items like this have just stopped dropping - like many of the mount rare proto-synthesis items in ZM - and the player could just vendor them if they had spare. Implementing these quests seems like a lot of development effort for vague purpose.

Anyhow, thank you again for your attention to this and many thanks for the QoL that your addon gives!

**Comment by leatrix** [comment]
The code was changed in the final release of 10.0.23.  Item IDs are no longer used.  Instead, LTP will check quest requirements for any Blizzard account-bound item (including items that Blizzard will add in future).  The tooltip for 'Automate quests' has been updated to highlight this.  If you notice any issues, you can still add to this ticket even though it will be closed (I will still get notifications).
