### ISSUE TITLE
Show cooldowns above the player frame

### ISSUE THREAD

**Issue by Natlyz** [leatrix/leatrix-plus#19]
**Hello!**

Please add an option to place 5 important cooldowns above the player frame instead of the target frame.

![465645](https://user-images.githubusercontent.com/60573947/111456269-d7448b80-8727-11eb-8681-6d128ba0a3c8.png)

I have my frames like this, so placing cooldowns above target won't work for me. An option do adjust position would be nice too.

**Thanks 😊**

**Comment by Sluimerstand** [comment]
That sounds to me like a feature more at home in an addon that revolves around combat and/or buffs. WeakAuras and TellMeWhen for example could do what you want.

**Comment by Natlyz** [comment]
> That sounds to me like a feature more at home in an addon that revolves around combat and/or buffs. WeakAuras and TellMeWhen for example could do what you want.

Leatrix already does that, but places cooldowns over the target frame. I'd like just an extra option added to place them above player's frame.

**Comment by leatrix** [comment]
Added to the latest alpha (at least 9.0.21.alpha.1).
https://www.curseforge.com/wow/addons/leatrix-plus/files/all

If you're using CurseForge app and prefer to install it from there, you need to change the release type to Alpha for Leatrix Plus.

**Comment by Natlyz** [comment]
Thanks! Didn't expect it to be added so fast.. or at all 😅
