### ISSUE TITLE
No Autocomplete Renown Quest

### ISSUE THREAD

**Issue by Yasinahh** [leatrix/leatrix-plus#191]
since the last update, the addon no longer gives the renown quests completely. You have to click once more each time

**Comment by leatrix** [comment]
Do you have an example quest name or link?

**Comment by Yasinahh** [comment]
Yes :)
https://www.wowhead.com/quest=70929/more-hunting-trophies > the 5 and 20 piece Quest dont complete automatically

https://www.wowhead.com/quest=72876/multiple-dragon-isles-artifacts > Same here....

**Comment by Yasinahh** [comment]
https://www.wowhead.com/quest=70841/more-titan-relics 
this Quest works fine

**Comment by leatrix** [comment]
The hunting trophies quest and the dragon isles artifacts quest both seem to work fine for me.  Which part does it get stuck on?  The Continue window or the Complete window or both (or something else)?  If you /reload your UI just before interacting with the NPC to turn in the quest, does that make any difference?

**Comment by Yasinahh** [comment]
Both stuck at the continue Window

**Comment by Yasinahh** [comment]
I have test it now with no other Addons. Dont work. 
I use the German client

**Comment by leatrix** [comment]
Tested the trophies quest on German client and it seems to work fine.  Do you see any errors?  I imagine when you tested it with no addons, you disabled addons and that quest was the first one you tried to turn-in?

**Comment by Yasinahh** [comment]
Dont see any errors.
Yes, this was the first quest after i disabled all addons

**Comment by leatrix** [comment]
The only real change made in the last update is that when you interact with a quest turn-in, LTP checks to see if the the quest requires an account-bound item.  If it does, it doesn't turn in the quest and it halts at the Continue and Complete windows.  But the required items in the quests you listed are not account-bound items.

If you want to help investigate the reason for this, please go here:
https://github.com/leatrix/leatrix-plus/find/main

Right-click Leatrix_Plus.lua in the file listing and click Save link as.  Save the file to your Leatrix_Plus folder in your addons folder (replacing the file that is already there).  Then reload your UI, open up Leatrix Plus in-game and you should see the version number shown top-left is 10.0.24.alpha.3.  If it is, try to turn in the quest and let me know what it reports in the chat log (when the Continue window is shown, it should report some messages in the chat log).  If you prefer to attach a screenshot, you can copy and paste it directly into the message here.

The link above is only temporary.  After testing, you should reinstall Leatrix Plus using your addon manager (right-click Leatrix Plus in your addon listing and click reinstall).

**Comment by Yasinahh** [comment]
Now i dont have a Leatrix Plus button. 
1x Interface\FrameXML\Bindings.xml:1 Leatrix_Plus/Leatrix_Plus.lua:1 Leatrix_Plus/Leatrix_Plus.lua:8: unexpected symbol near '<'

1x Leatrix_Plus/Leatrix_Plus.lua:1 Leatrix_Plus/Leatrix_Plus.lua:8: unexpected symbol near '<'

1x Leatrix_Plus/Leatrix_Plus.lua:8: unexpected symbol near '<'


Locals:

**Comment by Yasinahh** [comment]
try to /run leatrixplus or /run leatrixplus ()

1x [string "leatrixplus"]:1: '=' expected near '<eof>'
[string "=[C]"]: in function `RunScript'
[string "@FrameXML/ChatFrame.lua"]:2170: in function `?'
[string "@FrameXML/ChatFrame.lua"]:5224: in function <FrameXML/ChatFrame.lua:5170>
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4888: in function `ChatEdit_SendText'
[string "@FrameXML/ChatFrame.lua"]:4924: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>

Locals:
(*temporary) = "leatrixplus"

1x [string "leatrixplus()"]:1: attempt to call global 'leatrixplus' (a nil value)
[string "leatrixplus()"]:1: in main chunk
[string "=[C]"]: in function `RunScript'
[string "@FrameXML/ChatFrame.lua"]:2170: in function `?'
[string "@FrameXML/ChatFrame.lua"]:5224: in function <FrameXML/ChatFrame.lua:5170>
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4888: in function `ChatEdit_SendText'
[string "@FrameXML/ChatFrame.lua"]:4924: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>

Locals:
(*temporary) = nil
(*temporary) = "attempt to call global 'leatrixplus' (a nil value)"

**Comment by leatrix** [comment]
/run leaplus()
Or you can go into the game keybindings menu and assign a keybind to toggle the panel.

**Comment by leatrix** [comment]
My mistake.  Send me an email and I will email you the file.
The email address is on https://www.leatrix.com/ (look under the Support section).

**Comment by leatrix** [comment]
Thank you for the information that you emailed.

So the quests that you linked require items which are available as both Bind-on-Pickup and Bind-on-Account.  Quests that require BoP items will be turned-in automatically.  Quests that require BoA items will not be turned-in automatically.  This is because you may want to send the BoA items to your alts so it would not be a good experience to casually interact with an NPC and have all your BoA items disappear.

The 'Automate quests' option won't turn-in a quest automatically if it requires gold, a currency, a crafting reagent or a Blizzard account-bound item.

**Comment by Yasinahh** [comment]
Ok thank you for your help. Sorry i was sleeped... it was very late. 🙂
________________________________
Von: leatrix ***@***.***>
Gesendet: Sonntag, 18. Dezember 2022 03:45
An: leatrix/leatrix-plus ***@***.***>
Cc: Yasinahh ***@***.***>; Author ***@***.***>
Betreff: Re: [leatrix/leatrix-plus] No Autocomplete Renown Quest (Issue #191)


Thank you for the information that you emailed.

So the quests that you linked require items which are available as both Bind-on-Pickup and Bind-on-Account. Quests that require BoP items will be turned-in automatically. Quests that require BoA items will not be turned-in automatically. This is because you may want to send the BoA items to your alts so it would not be a good experience to casually interact with an NPC and have all your BoA items disappear.

The 'Automate quests' option won't turn-in a quest automatically if it requires gold, a currency, a crafting reagent or a Blizzard account-bound item.
