### ISSUE TITLE
[Feature Request] diff. positions for 'rightclick-addon-button-menu'

### ISSUE THREAD

**Issue by Kimab** [leatrix/leatrix-plus#193]
hey there, great addon! it would be so cool if it would be possible to anchor that menu on different corners of the minimap. right now the menu sits behind some other ui elements :/

thank you!

**Comment by leatrix** [comment]
In 10.0.24.alpha.4, the button frame appears on top of frames such as the player frame, target frame, vehicle seat frame, action bars, etc, while frames such as the bag frames, world map frame, etc, will appear over the top of the button frame when opened.  Please try it out.  In CurseForge App, you can switch to the alpha channel by right-clicking Leatrix Plus in your addon listing and changing the release type to alpha.

**Comment by Kimab** [comment]
thanks for the fast response! now it works almost perfectly. while the button frame IS on top of 2 of the 3 bars, its still below the main action bar so a part of the frame is still hard to see.
I should have provided more details, apologies. i placed the minimap on the left side of the actionbars, bottom side of screen. 
shall I send you a screenshot with the version 10.0.24.alpha.4?

**Comment by leatrix** [comment]
Try 10.0.24.alpha.5.  Seems to work fine for me.
