### ISSUE TITLE
[Feature Request] Add /ltp back as an option from settings.

### ISSUE THREAD

**Issue by dgouk** [leatrix/leatrix-plus#195]
Please add a setting to add /ltp back as an option from settings.

**Comment by leatrix** [comment]
The /ltp command will return as soon as Blizzard fix the bug with their slash command system.  Until then, [there are alternatives](https://github.com/leatrix/leatrix-plus/issues/192#issuecomment-1356493742) to using the /ltp command.

**Comment by dgouk** [comment]
Noted thanks for the update. I couldn't find any information on why it had changed and figured it was an inter-mod issue.

**Comment by leatrix** [comment]
**For Dragonflight**
> 10.0.09 - 8th November 2022
> - Due to problems with Blizzard's code in Dragonflight, the '/ltp' slash command has been removed for the time being.

**For Wrath of the Lich King Classic**

> 3.0.60 - 23rd November 2022
> - In 3.4.1, Blizzard's slash command system causes errors (just like retail) so /ltp has been replaced with /run leaplus() (just like retail).  When Blizzard fixes their slash command system, the /ltp slash command will return.

Classic Era is not affected.
