### ISSUE TITLE
guild group icon 

### ISSUE THREAD

**Issue by matton300** [leatrix/leatrix-plus#196]
Hi is there a way to move the heroic/mythic/guild group icon on minimap.

![image](https://user-images.githubusercontent.com/63061167/209057204-cd4ddfea-c6e0-484c-90f9-0735c68c37a3.png)

**Comment by leatrix** [comment]
If you use the 'Square minimap' setting, the instance difficulty badge is shown in the top-right.  If you use the default (round) minimap, the instance difficulty badge is in it's default position too.
