### ISSUE TITLE
[Enhancement Request] Add Malicia as Mute Game Sounds option

### ISSUE THREAD

**Issue by mb62994** [leatrix/leatrix-plus#198]
I don't mind talking heads. I actually like them.

But, I hate how loud and ear piercingly shrill Malicia's voice is. If you use War Mode you know exactly what I mean.

Can you mute only a specific talking head? There's two lines, one for a War Crate dropping and one for a new Bounty.

**Comment by leatrix** [comment]
What are the exact phrases word for word?

**Comment by mb62994** [comment]
Lines:
`Think you're so strong and mighty, eh? Come and prove it!`
`There's a killer on the loose! You should let them know what it feels like, get them!`
`Looks like you could all use some resources. Hmm, there's a saying for this-- survival of the fittest.`

**Comment by leatrix** [comment]
The file IDs you want are:

- 4621458
- 4621450
- 4621461

(same order as you posted the lines)

For now, you will need another addon to mute the sounds using those IDs.  Maybe a custom sound option should be added to Leatrix Plus.

**Comment by mb62994** [comment]
Appreciate the guidance!

I can understand not wanting to bloat the addon, but custom sounds would be awesome. I imagine I'm not the first (or last) to bug you on this.

**Comment by leatrix** [comment]
In 10.0.26.alpha.1, there is a new option called 'Mute custom sounds' ('System').  It's a simple option that's just there if you want to use it to avoid having to use another addon.

Enable the option, click the configuration button, enter sound file IDs into the editbox (separated by comma) then click the Mute button.

If you wish, you can prefix (or suffix if you prefer) each sound file ID with a note.  Try to keep the note under 10 characters as this will provide enough space to mute up to around 100 sounds.

For example, you can enter **DevAura 569679, RetAura 568744** to mute Devotion Aura and Retribution Aura.

To unmute sounds, you need to have the sound file listed in the editbox and then press Unmute.  The game always starts up (full client restart, not a reload) with no sounds muted then addons are loaded after that.

Read the editbox tooltip for more details.

To install the alpha, right-click the addon in CurseForge App and change the release type to alpha.  You can change it back to release anytime.

**Comment by mb62994** [comment]
🐐

**Comment by mb62994** [comment]
GitHub has no PM feature and you have no obviously available link: do you have a donation option? Been living off your addons (+ the OG LatencyFix) for well over a decade.

**Comment by leatrix** [comment]
I'm glad you like Leatrix addons.  There's no donation option but if you want to show support, there are free ways.  Let others know about Leatrix addons (such as in-game, Wow forum and Reddit, etc), report any issues you find and follow/subscribe to Leatrix where available (such as CurseForge and GitHub).

**Comment by mb62994** [comment]
👍

I just updated and used the new custom feature. It works! 

Feedback: 
The 'Mute' and 'Unmute' buttons have no feedback when pressing. Makes me want to continue clicking as an end user. Maybe keep a button depressed, print a message, etc.?

Can the hint/instruction appear only when mousing over the informational 'i' icon? Right now it appears while moused over any part of the edit box

**Comment by leatrix** [comment]
The editbox tooltip is only temporary to make sure that users read it as the option is still new.  The tooltip will be restricted to the help button in an update soon.

The mute button can't really be locked (like the way the reload button works) but I can add some sort of confirmation message to show how many sounds were muted or something like that.
