### ISSUE TITLE
Automate gossip on vendor NPCs

### ISSUE THREAD

**Issue by Deusdictum** [leatrix/leatrix-plus#199]
The automate gossip doesn't work if the NPC is a vendor.

**Comment by leatrix** [comment]
It seems to work fine for me.  If the NPC has more than one gossip option or a quest option is available then the gossip won't be automated though.

Next time you have this issue, put your pointer over the NPC (or its unit frame) so the tooltip for the NPC appears and enter **/run leaplus("id")** (if you have assigned a key for web link in the game keybindings panel, you can just press that instead).  You will see a Wowhead link to the NPC.  Press CTRL/C to copy and paste it in a reply here.
