### ISSUE TITLE
Every new target

### ISSUE THREAD

**Issue by denisciumbargi** [leatrix/leatrix-plus#2]
Message: Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:4529: Usage: MirrorTimer1:SetPoint("point" [, region or nil] [, "relativePoint"] [, offsetX, offsetY])
Time: Sat Dec 19 22:22:39 2020
Count: 5
Stack: Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:4529: Usage: MirrorTimer1:SetPoint("point" [, region or nil] [, "relativePoint"] [, offsetX, offsetY])
[string "=[C]"]: in function `SetPoint'
[string "@Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua"]:4529: in function <Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:4520>
[string "@Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua"]:4543: in function <Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:4535>

Locals: (*temporary) = MirrorTimer1 {
 0 = <userdata>
 bar = MirrorTimer1StatusBar {
 }
}
(*temporary) = nil
(*temporary) = UIParent {
 0 = <userdata>
 firstTimeLoaded = 1
 variablesLoaded = true
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil

**Comment by denisciumbargi** [comment]
P.s. This is a very nice plugin and worked until recently. Maybe it has to do with some dependencies, i am not the best at this codes things :)

**Comment by leatrix** [comment]
Disable all other addons.  The issue should be fixed.  If it is, enable other addons gradually until you find the addon causing the issue.
