### ISSUE TITLE
Request stop button shifts underneath action bar when stance bar is hidden

### ISSUE THREAD

**Issue by jxosborne** [leatrix/leatrix-plus#20]
Just as it says; if you select "Hide Stance Bar" it will shift the Request Stop button to the center of the screen, underneath the action bars.  

Screen grab attached.

![screen](https://user-images.githubusercontent.com/1701076/112685679-4c604100-8e4b-11eb-806f-55ed9a5535f3.jpg)

**Comment by jxosborne** [comment]
Just to add, no other addons running, I have tried deleting my wtf, config and interface folders and relaunching the game.  However I do run a single console command upon logging in:

UIParent:SetScale(0.5333)

This is just to get pixel perfect scaling with 2560x1440 resolution, as blizzard does not allow scaling below 65%.

Come to think of it, that would be a wonderful option to add to LeatrixPlus, the ability to scale the interface below blizzards limits.

Cheers, and thianks for all the hard work.

**Comment by leatrix** [comment]
Thanks for the report.  Please try the latest alpha (at least 9.0.22.alpha.3):
https://www.curseforge.com/wow/addons/leatrix-plus/files/all

**Comment by jxosborne** [comment]
Confirmed fixed.

Thanks for the ludicrously quick response on that.
