### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by kingreboot** [leatrix/leatrix-plus#201]
20x Leatrix_Plus/Leatrix_Plus.lua:9281: attempt to index field '?' (a nil value)
[string "@Leatrix_Plus/Leatrix_Plus.lua"]:9281: in function <Leatrix_Plus/Leatrix_Plus.lua:9059>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=(tail call)"]: ?
[string "@InstanceAchievementTracker/GUI.lua"]:2499: in function `GetNameFromNpcIDCache'
[string "@InstanceAchievementTracker/AchievementTrackerCore.lua"]:115: in function <...nstanceAchievementTracker/AchievementTrackerCore.lua:113>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "3"
(*temporary) = "|cff33937f"
(*temporary) = "Evoker"
(*temporary) = 147.000006
(*temporary) = 127.000008
(*temporary) = "33937f"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
LT = <table> {
 GuildRank = "1st Officer"
 LevelLocale = "Level"
 NameColor = "|cff33937f"
 UnitLevel = 61
 Unit = "mouseover"
 GuildLine = 2
 ClassCol = <table> {
 }
 InfoLine = 3
 RealLevel = 61
 TipIsPlayer = true
 NameText = "Detalzin"
 PlayerControl = true
 InfoText = "Level 61 Dracthyr |cff33937fEvoker"
 LpTipClassColor = "|cff33937f"
 Class = "Evoker"
 Sex = 2
 Reaction = 5
 PlayerRace = "Dracthyr"
 ColorBlind = "0"
 GuildName = "Äsgard"
 UnitClass = "EVOKER"
 TipUnitName = "Detalzin"
}
LeaPlusLC = <table> {
 LeaPlusNav9 = Button {
 }
 WidgetTopR = "TOP"
 MuteCustomList = ""
 TimerY = -96
 TooltipAnchorMenuTable = <table> {
 }
 LeaPlusNav2.s = Texture {
 }
 RecentChatSize = 170
 MakeFT = <function> defined @Leatrix_Plus/Leatrix_Plus.lua:355
 BordersAlpha = 0
 MinimapR = "TOPRIGHT"
 TipCursorX = 0
 Page0 = Frame {
 }
 DressupItemButtons = "Off"
 InviteFromWhisper = "On"
 DurabilityScale = 1
 MuteZeppelins = "Off"
 TransHallowed = "Off"
 MakeCB = <function> defined @Leatrix_Plus/Leatrix_Plus.lua:11782
 MuteGyrocopters = "Off"
 ManageDurability = "Off"
 AcceptPartyFriends = "On"
 LockOption = <function> defined @Leatrix_Plus/Leatrix_Plus.lua:551
 RestoreChatMessages = "Off"
 MinimapModder = "Off"
 MakeSL = <function> defined @Leatrix_Plus/Leatrix_Plus.lua:11728
 Page4 = Frame {
 }
 ShowDropTip = <function> defined @Leatrix_Plus/Leatrix_Plus.lua:280
 ReloadCheck = <function> defined @Leatrix_Plus/Leatrix_Plus.lua:608
 NoPartyInvites = "Off"
 NumberOfPages = 9
 TipHideShiftOverride = "On"
 HideZoneText = "Off"
 TimerX = -5
 WidgetTopA = "TOP"
 SetTipScale = <function> defined @Leatrix_Plus/Leatrix_Plus.lua:8755
 SetDim = <function> defined @Leatrix_Plus/Leatrix_Plus.lua:570
 HideMiniAddonButtons = "On"
 LeaPlusQuestFontSize = 18
 TipShowTarget = "Off"
 AutoSellNoKeeperTahult = "On"
 ShowErrorsFlag = 1
 NoDuelRequests = "Off"
 Print = <function> defined @Leatrix_Plus/Leatrix_Plus.lua:89
 QuestFontChange = "Off"
 NoRaidRestrictions = "Off"
 MuteAirships = "Off"
 AutoQuestKeyMenuTable = <table> {
 }
 MuteSoulEaters = "Off"
 HideCleanupBtns = "Off"
 BordersTop = 0
 Page9 = Frame {
 }
 ZygorToggle = <function> defined @Leatrix_Plus/Leatrix_Plus.lua:367
 TipNoHealthBar = "Off"
 TooltipAnchorMenu = 1
 ShowRaidToggle = "Off"
 MinimapNoScale = "Off"
 ShowVoiceButtons = "Off"
 IsPlusShowing = <function> defined @Leatrix_Plus/Leatrix_Plus.lua:463
 MuteCustomSounds = "Off"
 BlockDrunkenSpam = "Off"
 LeaPlusNav5.s = Texture {
 }
 AutoReleaseNoAshran = "Off"
 MuteMechsuits = "Off"
 MakePage = <function> defined @Leatrix_Plus/Leatrix_Plus.lua:14294
 ShowWowheadLinks = "Off"
 AutoQuestCompleted = "On"
 Page7 = Frame {
 }
 CfgBtn = <function> defined @Leatrix_Plus/Leatrix_Plus.lua:318
 LeaPlusMailFontSize = 22
 NoFriendRequests = "Off"
 LeaPlusNav1 = Button {
 }
 AutoReleaseNoTolBarad = "Off"
 transTable = <table> {
 }
 MuteMechSteps = "Off"
 WidgetTopScale = 1
 NoCombatLogTab = "On"
 muteTable = <table> {
 }
 LeaPlusNav2 = Button {
 }
 MoveChatEditBoxToTop = "Off"
 MuteSniffing = "Off"
 MinimapY = -2
 MakeWD = <function> defined @Leatrix_Plus/Leatrix_Plus.lua:11719
 LeaPlusNav4 = Button {
 }
 NoScreenGlow = "Off"
 VehicleY = -192
 Page1 = Frame {
 }
 LeaPlusChatFontSize = 20
 LeaPlusNav0 = Button {
 }
 MailFontChange = "Off"
 LeaPlusNav3 = Button {
 }
 ShowBorders = "Off"
 MainPanelA = "CENTER"
 BordersLeft = 0
 MuteSunflower = "Off"
 AutoSellJunk = "On"
 AutoRepairGear = "On"
 ManageTimer = "Off"
 CreateDropDown = <function> defined @Leatrix_Plus/Leatrix_Plus.lua:11946
 HideTalkingFrame = "Off"
 AutomateGo

**Comment by leatrix** [comment]
This is to do with 'Enhance tooltip' ('Interface') and possibly related to Instance Achievement Tracker.  You saw this error when mousing over a player unit.

- How often do you see this error?
- Starting from a `/reload`, are you able to list some steps that will produce this error?
