### ISSUE TITLE
Fishing after Arena

### ISSUE THREAD

**Issue by Natlyz** [leatrix/leatrix-plus#202]
**Hello!**
 
After each arena I get a fishing equipment buff for no reason and the addon doesn't remove it.

**Thanks!**

**Comment by leatrix** [comment]
LTP doesn't remove the fishing buff because doing so cancels the fishing cast.

**Comment by Natlyz** [comment]
Guess we'll have to wait for Blizzard to fix that.

**Comment by leatrix** [comment]
Report it as a bug using the in-game bug report tool.  It seems that removing other buffs doesn't interrupt the fishing cast (including appearance change buffs from items and toys) so it's likely an oversight.
