### ISSUE TITLE
Option to hide hunter/lock/dk action pet bar during pet battles (Feature request)

### ISSUE THREAD

**Issue by cgsub** [leatrix/leatrix-plus#203]
It's pretty annoying to have the pet action bar showing over the pet battle abilities during pet battles. 
It seem to be a bug that blizzard is not in a hurry to fix...

At least I haven't found a way to get it fixed yet. 
There are a few threads about this issue since last October.

Would be great if you could add that option.

Thanks!

**Comment by leatrix** [comment]
Until Blizzard fix it, use Edit Mode to move the pet action bar a tiny amount - just a single pixel in any direction will do.  This will not hide the bar during a pet battle but it will ensure the bar doesn't cover the pet battle frame.  There's a realistic chance that Blizzard could fix this bug in 10.0.5 (expected in a few weeks).
