### ISSUE TITLE
fr: please add "modify bag automation" for dragonflight if possible

### ISSUE THREAD

**Issue by Belatar** [leatrix/leatrix-plus#204]
hi! quick thanks for an awesome addon!
i found it looking for a way to disable bags closing automatically. unfortunately it doesnt seem to do this for dragonflight.
would it be possible to re-implement that?
as i use elv as well best way for me would be to address the "closing" part separately for maximum granularity, as the opening part is already covered by elv.
cheers, bela

**Comment by leatrix** [comment]
[The API is still broken on live realms.
](https://github.com/Stanzilla/WoWUIBugs/issues/310)
Until Blizzard fix this, the only way around it is to use a bag replacement addon that uses its own bag frames and lets you control the automation for them.
