### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Rezy942** [leatrix/leatrix-plus#206]
Hello,

Some features I would love added to this addon:

0) Allow disabling automatic tooltip name-coloring of some units. I did not see an option for this in the tooltip settings. It seems to be doing this in the background for some reason.
With leatrix tooltip enabled: 
![image](https://user-images.githubusercontent.com/122007087/211146134-ae27c779-b54f-4834-b2b0-c0cef74ee6f7.png)
Leatrix tooltip disabled:
![image](https://user-images.githubusercontent.com/122007087/211146153-8a965e0b-ecca-4ee5-93ac-e6f817e28791.png)
1) Feature that lets you color the health bar (class color) in ADDITION to the current area around the name above the health bar.
User could toggle with part they want to enable, one specific or both.
2) Add option to color tooltip border based on unit class for player units + option to show their item level.
3) Add item level next to each equipment slot in character window. Preferably customizable in some way such as placement next to items or on top of the item icon with configurable scale even. Color matches equipment quality.
4) Add option to show additional stats hidden by blizzard such as mounted movement speed. (dejacharacterstats but simplified)
5) Add option to change spec in talent window without going to "specialization" tab. Something like quick hotkeys on the bottom bar with spec icons, clicking which activates respective spec.
6) Incorporate player frame fading functionality (optional settings) of addon called "Player Frame Smart Hide". The author is MIA but addon still works pretty good. It is incredible for immersive gameplay.
7) Add option to show BoE symbol, item level, and grey-out garbage items in default blizzard bags. There are 3 super light-weight addons that do the job, but Leatrix is more suited to do this all-in-one right? Addon names:
![image](https://user-images.githubusercontent.com/122007087/210745513-39c30527-1a73-4da4-8eee-f7d176e886db.png)
8) Option to customize status text on unitframes, such as player, target, party, pet, ToT, etc. Current blizzard iteration (for years now) has been absolutely horrible. Ideally i would like to be able to customize format of text manually, such as show % and current HP, current HP only, etc. Right now, default blizz party frames are unusable with status text. Health is just impossible to see behind the text!!! Something to help the horrible font shadow/outline too perhaps?
Example: 
![image](https://user-images.githubusercontent.com/122007087/210746553-59a7c083-2be9-47ee-93e2-ee15bd3109f1.png)
9)  Option to add a hotkey to inspect target (and mouseover too maybe). Instead of manually right clicking target frame, and clicking Inspect. A lot of the times the frames bug out.
10) Option to move dungeon finder queue icon from current blizzard default to the classic spot on the minimap. Anywhere where it makes sense and doesnt clash with anything else. Could also make it movable around a circle, the position being saved globally.
![image](https://user-images.githubusercontent.com/122007087/211141683-bf665b9e-2a11-49e1-a956-adb248b0f6c1.png)

I hope at least some of these interest you - thank you!

**Comment by tflo** [comment]
> 10. Option to move dungeon finder queue icon from current blizzard default to the classic spot on the minimap. Anywhere where it makes sense and doesnt clash with anything else. Could also make it movable around a circle, the position being saved globally.

I concur with this suggestion. Add an option to scale the icon to make it bigger.

I'm currently doing this using [MoveIt](https://www.curseforge.com/wow/addons/moveit) and it looks like this:

<img width="530" alt="WoWScrnShot_012123_160251" src="https://user-images.githubusercontent.com/1410282/213873014-1e2ce720-060d-4829-b62b-1abd80988715.png">

**Comment by leatrix** [comment]
Suggestions appreciated.
