### ISSUE TITLE
Auto repair and Master's Hammer

### ISSUE THREAD

**Issue by cremor** [leatrix/leatrix-plus#209]
Blacksmiths can repair some items for free with [Master's Hammer](https://www.wowhead.com/item=201366/masters-hammer). It would be great if that could be included in the addon.

A few ideas:

A) If possible, the hammer should be used automatically on all possible slots. Only after that is done the "normal" repair all should be triggered.

B) If A is not possible, maybe the possible hammer slots could be skipped? So instead of using "repair all", all other slots are repaired individually.

C) If B is also not possible, maybe just have a setting to only repair automatically when the possible hammer slots are at max durability.

For "possible slots": If it's not possible to auto-detect those it would also be OK to have it as a setting.

**Comment by leatrix** [comment]
Feedback appreciated.
