### ISSUE TITLE
Feature Request: disable spell auto add and scaling beyond Blizzard interface limits

### ISSUE THREAD

**Issue by jxosborne** [leatrix/leatrix-plus#21]
I have a couple small bits of LUA I maintain myself, mostly gathered from old addons that are no longer around.

I think they would fit very well into the leatrix-plus library if you're interested in integrating the code.

One just prevents the auto-add feature that automatically drops spells on your bars, and the other is just changing the scaling to match the pixel density of 1440p; I used the formulae described in this reddit post here:

https://www.reddit.com/r/wow/comments/95o2qn/how_to_pixel_perfect_ui/

I've attached the 2 LUA files.

Cheers.

[MyStuff.zip](https://github.com/leatrix/leatrix-plus/files/6215706/MyStuff.zip)

**Comment by leatrix** [comment]
Suggestions appreciated.
