### ISSUE TITLE
Feature suggestion: Option to disable default loot frame

### ISSUE THREAD

**Issue by tflo** [leatrix/leatrix-plus#211]
If you are using addons like [LS: Toasts](https://www.curseforge.com/wow/addons/ls-toasts) to selectively display your loot, the default loot frame (`LootFrame`) becomes rather redundant.

Or even without replacement addons, if you're auto-looting and just don't want to see that frame pop up. (The loot will still show up in chat).

It can easily be disabled by replacing its OnEvent function with a dummy function. Got the idea from [Hide Default loot Frame](https://www.curseforge.com/wow/addons/hide-default-loot-frame). This works great, but maybe there are other or better ways, IDK.

_If you do implement it,_ please do not make it dependent on your "Faster auto loot" feature, make it standalone. The reason for this is that if you use addons such as [SellableItemDrops](https://www.curseforge.com/wow/addons/sellableitemdrops) or [Gathering](https://www.curseforge.com/wow/addons/gathering), you cannot use Faster auto loot because it will cause those addons to miss ~50% of the loot.

I think this would be a good addition to your "Frames" category.

**Comment by leatrix** [comment]
Suggestions appreciated.
