### ISSUE TITLE
[Feature Request] Automate gossip by default / cogwheel for more options

### ISSUE THREAD

**Issue by jsaue003** [leatrix/leatrix-plus#213]
Love the automate gossip feature, but dislike having to hold alt repeatedly. Feel like I'm playing twister having to hold shift for some things, hold alt for this one, hold down CTRL for this. Can we please have feature to automate gossip by default? 

Example, I'm doing the Dragonflight questline on my 9th character. No, I don't need to see the gossip on every single NPC I will ever talk to in the entire game. I also don't want to spend 5+ hours holding down alt. 

Cogwheel with options like Quests automation would help immensely.

**Comment by leatrix** [comment]
The 'Automate gossip' option has to have a key requirement.
