### ISSUE TITLE
Run leaplus() option no longer works

### ISSUE THREAD

**Issue by jsaue003** [leatrix/leatrix-plus#214]
Using command /run leaplus() to configure options in game no longer works, and results in following error message. I understand that it's now /ltp, but it's very confusing because this command shouldn't even be enabled at all considering it's no longer valid. 

> _Message: [string "leaplus()"]:1: attempt to call global 'leaplus' (a nil value)
> Time: Thu Jan 26 11:35:38 2023
> Count: 1
> Stack: [string "leaplus()"]:1: attempt to call global 'leaplus' (a nil value)
> [string "leaplus()"]:1: in main chunk
> [string "=[C]"]: in function `RunScript'
> [string "@Interface/FrameXML/ChatFrame.lua"]:2175: in function `?'
> [string "@Interface/FrameXML/ChatFrame.lua"]:5229: in function `ChatEdit_ParseText'
> [string "@Interface/FrameXML/ChatFrame.lua"]:4893: in function `ChatEdit_SendText'
> [string "@Interface/FrameXML/ChatFrame.lua"]:4929: in function `ChatEdit_OnEnterPressed'
> [string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>
> 
> Locals: (*temporary) = nil
> (*temporary) = "attempt to call global 'leaplus' (a nil value)"__

**Comment by leatrix** [comment]
Since the release of 10.0.5, **/run leaplus()** is no longer in the addon at all.  The error message you are seeing is a generic message telling you that the function does not exist.  If you try **/run tomhanks()** you will get the same error message (other than it referring to tomhanks instead of leaplus).

```
1x [string "tomhanks()"]:1: attempt to call global 'tomhanks' (a nil value)
[string "tomhanks()"]:1: in main chunk
[string "=[C]"]: in function `RunScript'
[string "@FrameXML/ChatFrame.lua"]:2175: in function `?'
[string "@FrameXML/ChatFrame.lua"]:5229: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4893: in function `ChatEdit_SendText'
[string "@FrameXML/ChatFrame.lua"]:4929: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>

Locals:
(*temporary) = nil
(*temporary) = "attempt to call global 'tomhanks' (a nil value)"
```
