### ISSUE TITLE
[Feature Request] - Minimap Button Bag

### ISSUE THREAD

**Issue by gnicholsblvd** [leatrix/leatrix-plus#215]
Leatrix seems like a great addon to have a Minimap Button Bag, one less addon to download outside of Leatrix.

**Comment by leatrix** [comment]
It's already in the addon.  Enable 'Enhance minimap' ('Interface'), go into the configuration panel for that option and enable 'Combine addon buttons'.  Now you can right-click the minimap to see your addon buttons.

If you want any buttons to remain around the minimap at all times, you can do that too.  Click the Buttons button in the configuration panel, enter the names of the addons that you want to remain visible (the editbox tooltip will show you what you should enter) and reload.

'Enhance minimap' is a complete minimap replacement so you will need to make sure that any other addons which replace the minimap are disabled.

**Comment by Rezy942** [comment]
Been using this option and i love it. 
Is it possible to add option to show an icon that user can click to open addons list? Similar to MBB
I notice im constantly clicking either too far left or right on minimap and addon bag doesnt open. It would be nice to have a visual reference.
It would rotate around the map preferably, and saved globally across all characters. (so u dont have to re-move it on every single toon to exact pixel-perfect location D:  )
Thanks!!

**Comment by leatrix** [comment]
You can right-click **anywhere inside the minimap border** (the border that surrounds the actual map area) to open the button frame so that's quite a large clickable area.  Don't right-click outside of the map border as that may not always work.  It's designed to work by right-clicking anywhere inside the map border.

If right-clicking inside the map border doesn't work every time for you, try with other addons disabled to see if one of them is preventing the button frame from opening.

**Comment by Rezy942** [comment]
Thanks, it mustve been an addon at the time
I tried it now and clicking anywhere on the map opens it. Thats much easier
Before i could only click a few pixels to left or right of minimap ring. Nowhere else :)

**Comment by gnicholsblvd** [comment]
Thanks for the reply Leatrix, found it after you provided the direction. Perhaps an option under "Combine addon buttons" to toggle either on minimap right click, display as a single button on edge of map, or both.

**Comment by leatrix** [comment]
Is there any problem with right-clicking the minimap?

**Comment by gnicholsblvd** [comment]
Not a problem, just to have an additional way to display it.

**Comment by Rezy942** [comment]
The right click is wonderful, i agree it would be nice to have a "visual indicator" of some sort :)
Not a big deal at all, can easily live without it
