### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Trajin** [leatrix/leatrix-plus#216]
An old addon I used to have would set the character when you click the addons button instead of defaulting to ALL.   Would this be something you could add?   Thanks

**Comment by Rezy942** [comment]
Character-specific addon selections by default? Would be nice
I remember that addon too - blizzard UI still sucks for addon management

**Comment by leatrix** [comment]
It appears that Blizzard have fixed the issues with the Dragonflight code which prevented this option from working so it has returned.

> 10.0.35.alpha.1 - 1st February 2023
> - The 'Show character addons' ('System') option has returned.  If checked, the game addon list will show character addons by default.
