### ISSUE TITLE
Feature request: Wider transmog preview window.

### ISSUE THREAD

**Issue by Nillx** [leatrix/leatrix-plus#218]
Do you think adding an option that makes the transmog char preview window bigger? Maybe a round square and to be able to zoom out a bit more th an the default option. Currently on bigger races its quite difficult to fully see your character or the weapon.

**Comment by leatrix** [comment]
Try 10.0.35.alpha.2.  There is a new setting to make the transmogrifier character preview panel wider (it also lets you zoom out a bit more and it moves the weapon slots to the bottom-right so that you can see more of your character).

**Comment by Nillx** [comment]
Thanks alot

**Comment by Nillx** [comment]
Tried this today and it looks as i imagined it thanks!
