### ISSUE TITLE
Feature Request: Multiple Profiles

### ISSUE THREAD

**Issue by nichols-green** [leatrix/leatrix-plus#22]
Many addons today support multiple named profiles to enable one-click switching from an arena optimized setup to dungeon optimized and so on.  It would be amazing if Leatrix Plus could include the same support. I personally have a very tight and dense setup for arena, and a minimal spacious setup for pve content.

**Comment by nichols-green** [comment]
See [BigDebuffs](https://github.com/jordonwow/bigdebuffs) and [OmniBar](https://github.com/jordonwow/omnibar) for examples.

**Comment by leatrix** [comment]
Feedback appreciated.
