### ISSUE TITLE
Dragon sounds are back?

### ISSUE THREAD

**Issue by SiderealDay** [leatrix/leatrix-plus#220]
After some recent update (addon or game?), it seems the dragon sounds are back, even though I have ticked to mute them in the addon.

Previously, I was not hearing much dragon roars around Valdrakken, but it seems something is broken now as the roars will not stop.

I even tried to list some of the sounds in the custom sounds section to no avail. I found those on Wowhead for the 4 rideable dragons:
4633278, 4633280, 4633282, 4633284, 4633286, 4633288, 4633290,4633292, 4633294, 4633296, 4633298, 4633300, 4633302, 4633370, 4633372, 4633374, 4633376, 4633378, 4633380, 4633382, 4634009, 4634011, 4634013, 4634015, 4634017, 4634019, 4634021,

Any ideas?

**Comment by SiderealDay** [comment]
Not sure why, but the issue resolved itself today. Will revert back if I get any more info.

**Comment by leatrix** [comment]
I will close this then but you can still reply if you wish to.
