### ISSUE TITLE
Junk autosell exclusions list doesn't work in reagent bags

### ISSUE THREAD

**Issue by romdeau23** [leatrix/leatrix-plus#221]
I have Burly Bear Haunch (197748) on my exclusion list, but those items don't get automatically sold if they're in a reagent bag. If I move them into a regular bag they do get sold. This happens with all items on the exclusion list that also happen to go into a reagent bag.

**Comment by leatrix** [comment]
Many thanks.  This is fixed in 10.0.36.alpha.x.
