### ISSUE TITLE
Sticky Dressroom

### ISSUE THREAD

**Issue by Natlyz** [leatrix/leatrix-plus#223]
**Hello!**

https://user-images.githubusercontent.com/60573947/216838434-e1f6403d-e0e6-416d-9572-bb2ca9cdac1d.mp4

Not sure if this is an LTP problem. Could this be an enchanced dressup bug?
No errors caught with bugger.

**Thanks 😊**

**Comment by leatrix** [comment]
Disable all other addons and test.  It should work fine.
So enable other addons gradually until you find the addon that causes the problem.  If you tell me what that addon is, I can advise you further.

**Comment by Natlyz** [comment]
I've disabled all addons on an alt, and it worked fine, Then enabled all addons, even those I don't use anymore, and it worked fine. Then I logged back to Druid and everything worked fine again. Strangely I can't reproduce the bug anymore 🙉

**Comment by Natlyz** [comment]
At least I have a video evidence the bug occurred 😅

**Comment by leatrix** [comment]
Videos are very helpful but this isn't a bug at the moment.  It could be any number of things.  Leatrix Plus doesn't control the movement of the character model.  When you right-click and drag, that is the default UI.

If it happens again, reload your UI first of all to see if the issue persists.  If it does persist, disable all other addons and test as above.  You can still reply to a closed ticket.

**Comment by Natlyz** [comment]
Thanks!
