### ISSUE TITLE
Request: Remove completed quests automatically from tracked quests?

### ISSUE THREAD

**Issue by 40P3** [leatrix/leatrix-plus#224]
Hi,

I use Leatrix plus now as a go-to for replacing numerous other addons, you guys are awesome!

Is there a chance to add a function that I dearly miss(due to old addons not updated to Dragonflight)?

Specifically two requests:
-Allow automatically removing a tracked quests if its completed.
-Only track the quests that are in the given zone.

Pretty please? :)

**Comment by leatrix** [comment]
Feedback appreciated.
