### ISSUE TITLE
Use AceHook-3.0 instead please. Or even better, being an Ace-3.0 addon like other addons are doing.

### ISSUE THREAD

**Issue by trcrsired** [leatrix/leatrix-plus#225]
You hook Game Object with GameToolTip with hooksecurefunc causing my UI function to fail.

I love this addon, but please use AceHook-3.0 to hook functions, so we do not break other addons.

Just switching to Ace3 would be an even better idea, tbh.

I would argue entire settings in Leatrix-plus can be just replaced with AceConfig-3.0 and that would allow UI addons to custom the UI with your addon.

**Comment by trcrsired** [comment]
Message: Interface/AddOns/QUI_Tooltip/tooltip.lua:73: Usage: SecureHookScript(object, method, [handler]): You can only hook a script on a frame object
Time: Tue Feb 14 07:02:57 2023
Count: 1
Stack: Interface/AddOns/QUI_Tooltip/tooltip.lua:73: Usage: SecureHookScript(object, method, [handler]): You can only hook a script on a frame object
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua"]:143: in function <Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua"]:410: in function `SecureHookScript'
[string "@Interface/AddOns/QUI_Tooltip/tooltip.lua"]:73: in main chunk

Locals: (*temporary) = "Usage: SecureHookScript(object, method, [handler]): You can only hook a script on a frame object"

**Comment by leatrix** [comment]
Feedback appreciated.
