### ISSUE TITLE
Auto Gossip not working for Signal Lantern

### ISSUE THREAD

**Issue by Jokaleth** [leatrix/leatrix-plus#227]
As the title says, I have the "Automate Gossip" option turned on, but it doesn't work on the Signal Lantern at the beginning of Court of Stars

![image](https://user-images.githubusercontent.com/87456827/222821847-e5aa748c-82dc-487f-93d9-b47a9b6a9d37.png)

**Comment by leatrix** [comment]
Requires the alt key to be held down.
