### ISSUE TITLE
Recent Chat Window Truncates Sequence

### ISSUE THREAD

**Issue by samueldcorbin** [leatrix/leatrix-plus#23]
It appears that the Recent Chat Window truncates some sequences. It looks like some parts of the chat message aren't being treated as strings.

To replicate:

1. /dump "{uiMapID=1,position=(x=0.5,y=0.5}}"
2. ctrl+click the chat tab to open the Recent Chat Window

In my normal chat history I see:
Dump: value="{uiMapID=1,position=(x=0.5,y=0.5}}"
[1]="{uiMapID=1,position=(x=0.5,y=0.5}}"

But in the Recent Chat Window I see:
Dump: value="(})"
[1]="(})"

The colors are also wrong - seemingly inheriting the color from the previous message.

Probably not an issue for the average player, but being able to copy-paste from there while writing addons can be very handy, and depending on what is happening to the bits that are being excluded, might present a larger issue.

**Comment by leatrix** [comment]
Many thanks for the report.

Please try the latest alpha (at least 9.0.25.alpha.1):
https://www.curseforge.com/wow/addons/leatrix-plus/files/all

Ellipses and colors should now be copied to the recent chat window correctly.

Please let me know how you go on with it.

**Comment by samueldcorbin** [comment]
Looks like it's working now! 👍
