### ISSUE TITLE
Viewport issue (Classic Era)

### ISSUE THREAD

**Issue by TrusterX** [leatrix/leatrix-plus#231]
### Issue

no contact options for LTP Classic Era, the Google Forms doesn't work, as it won't accept any new answears.

Latest LTP Classic Era (1.15.64):
System / Viewport was moved to Interface / Borders. In this Window, The "reset Screen" is missing, so there is no way to re-calibrate the viewport in this new version. Downgraded to 1.15.63, which is working fine.

### Game version

Classic Era (including Hardcore and Season of Discovery)

**Comment by GeneralWaffle** [comment]
New Version won't even show up in Classic

**Comment by TheMcJuice** [comment]
> New Version won't even show up in Classic

I had this issue as well. Reinstalled and it is working now. FWIW both the initial (broken) install and reinstall were done through Curseforge. I did not manually uninstall, I just used the reinstall action.

**Comment by GeneralWaffle** [comment]
> > New Version won't even show up in Classic
> 
> I had this issue as well. Reinstalled and it is working now. FWIW both the initial (broken) install and reinstall were done through Curseforge. I did not manually uninstall, I just used the reinstall action.

I tried that before installing the old version again, but didn't work. So I wait now till Leatrix gives a thumbs up.

**Comment by TrusterX** [comment]
@leatrix it's good to see the new ltp with issue tracker here. I hope that the "reset screen" in the borders settings will come back. For now, i will stick on 1.15.63 as it is working perfectly - at least on hc realm ;-)

**Comment by apportunities** [comment]
I have also had to downgrade. Resizing the viewport was such a great feature of LTP..

**Comment by TrusterX** [comment]
why is this issue closed? It is still present.

**Comment by apportunities** [comment]
> why is this issue closed? It is still present.

Presumably because Leatrix has no intent on fixing it.
