### ISSUE TITLE
Leatrix Plus not loading on cata classic 

### ISSUE THREAD

**Issue by Khalimdk** [leatrix/leatrix-plus#234]
### Issue

not loading on cata classic 

### Game version

Cataclysm Classic

**Comment by leatrix** [comment]
It works fine.  Make sure you have the right version installed.  The code is not unified.  There are still separate releases for The War Within, Cataclysm Classic and Classic Era.  Remove the version you have and install the correct version.

**Comment by Khalimdk** [comment]
i installed the 1 with the bracket use this one cata version  twice via the curse client

**Comment by leatrix** [comment]
I'm using it in Cataclysm Classic right now (freshly installed from CurseForge App).  Check manually.  Open your addons folder in File Explorer, open the Leatrix_Plus folder and open Leatrix_Plus.lua in Notepad.  What does it say at the very top for addon version?  Also what game locale are you using?

**Comment by Khalimdk** [comment]
the curse forge app says the addon is corruptet

**Comment by leatrix** [comment]
Right-click it in your addon listing and reinstall.  If that doesn't help, tell me the information I asked you for.

**Comment by Khalimdk** [comment]
just tryed for the thried time to install it and now it is there on  in game addon thingy

**Comment by Dagarle** [comment]
I am having the exact same issue.  I deleted the old version and downloaded the new version on Cata Classic and Anniversary Classic. all through the Curseforge app.  The Curseforge app says it is installed.  However there is no folder in the Interface/Addons folder for it so it is not in the game Addons menus either of course.  I have deleted it and reinstalled twice in both games and restarted my computer.  It simply does not actually install in into the game files even though Curseforge says it is.  I am just going to try and install it manually now.
![image](https://github.com/user-attachments/assets/11d3021e-6fb1-43cd-a068-4ecad83de506)
![image](https://github.com/user-attachments/assets/a97f64ba-0feb-4e0c-939c-958c799b45e1)

**Comment by Dagarle** [comment]
Installing it manually worked so good enough for now.

**Comment by leatrix** [comment]
@Dagarle It works fine for me.  Make sure all the old addons are deleted from every addons folder.  Then install the new addons.  If they don't show up in your addons folder, open CurseForge App, right-click the addon and click Browse Folder.  Which folder does that take you to and is the addon folder there?  Make sure the correct game is showing in your game menu top-right of the app.  Do other addons get installed correctly to that folder?  To make sure addons are being installed to the correct folder, click the 3 dots (top-right of CurseForge App) and click Open instance settings then check the Game instance path.  You can still reply to closed tickets.
