### ISSUE TITLE
Feature Request: auto deposit anima

### ISSUE THREAD

**Issue by nichols-green** [leatrix/leatrix-plus#24]
Pretty self explanatory, but an auto deposit anima option in the automation would be handy.

**Comment by leatrix** [comment]
Thanks for your suggestion.  However, this cannot be done as the relevant game function is protected.
https://wowpedia.fandom.com/wiki/API_C_CovenantSanctumUI.DepositAnima

**Comment by nichols-green** [comment]
Ah, thanks for looking into it. Keep up the great work!
