### ISSUE TITLE
[Feature Request] Mute Dragonwrath quest rp in the city (Cataclysm Classic)

### ISSUE THREAD

**Issue by puydomgulat** [leatrix/leatrix-plus#240]
### Issue

Request to add an option to mute the Dragronwrath legendary quest rp in Orgrimmar and/or Stormwind. Similar to the option to mute Rhonin's Ulduar quest rp in Dalaran from WotLK.

### Game version

Cataclysm Classic

**Comment by leatrix** [comment]
Are these the lines you want me to mute?

Kalecgos says: Welcome, friend. We've been expecting you.
Kalecgos says: You're to be congratulated for your success in the Firelands.
Kalecgos says: But praise alone won't suffice.
Kalecgos says: We owe you a great deal for the part you've played in the destiny of our flight.
Kalecgos says: Present me your staff that we may endow it with great power.
Kalecgos says: Finally. Tarecgosa, our beloved sister whose essence you've generously born, has chosen this staff as her permanent home.
Kalecgos says: May her presence be a source of comfort and companionship to you.
Kalecgos says: We thank you, Friend of the Blue Dragonflight.

Any more lines than that?

**Comment by leatrix** [comment]
> 4.0.39.alpha.1 - 12th December 2024
> - For 'Mute game sounds', you can now mute the speech made by Kalecgos at the Dragonwrath ceremony.

It will mute the following:

Kalecgos says: Welcome, friend. We've been expecting you.
Kalecgos says: You're to be congratulated for your success in the Firelands.
Kalecgos says: But praise alone won't suffice.
Kalecgos says: We owe you a great deal for the part you've played in the destiny of our flight.
Kalecgos says: Present me your staff that we may endow it with great power.
Kalecgos says: Finally. Tarecgosa, our beloved sister whose essence you've generously born, has chosen this staff as her permanent home.
Kalecgos says: May her presence be a source of comfort and companionship to you.
Kalecgos says: We thank you, Friend of the Blue Dragonflight.

It will be included in the weekly update (typically Wednesday).
