### ISSUE TITLE
Missing button feature (Classic Era)

### ISSUE THREAD

**Issue by SamuraiParakeet** [leatrix/leatrix-plus#242]
### Issue

I've watched a youtube video of a gentleman using leatrix plus to extend his UI to allow for dual monitor usage on WoW classic. The feature was listed under "system" and labeled "enable viewpoint". Link to the video in question. https://www.youtube.com/watch?v=9McEBO_-iv4

### Game version

Classic Era

**Comment by leatrix** [comment]
https://github.com/leatrix/leatrix-plus/issues/231
