### ISSUE TITLE
[Feature request] Scrolling the pages in the Spellbook (Classic Anniversary)

### ISSUE THREAD

**Issue by m4gnify** [leatrix/leatrix-plus#243]
### Issue

Hi!
This is for Classic Era/Anniversary.
In for example the shops, you can scroll the pages with the scroll wheel.
I wish that was also possible in the Spellbook, as right now you have to click the left and right arrows in the Spellbook to switch pages.
Thanks!

### Game version

Classic Anniversary

**Comment by leatrix** [comment]
It's not possible to add this.
