### ISSUE TITLE
This is 1.15.5 addon Simplified Chinese(zhCN) improved translation file，thank you.  (Classic Era)

### ISSUE THREAD

**Issue by JosephineYusunuxiang** [leatrix/leatrix-plus#245]
### Issue

[https://github.com/JosephineYusunuxiang/Leatrix_Plus_Locale-classicera-zhCN/blob/main/Leatrix_Plus_Locale.lua](url)

### Game version

Classic Era

**Comment by leatrix** [comment]
Thank you for the files.  I have sent you a message on CurseForge about this.
