### ISSUE TITLE
Skeletal Warhorse The sound of running? (Classic Era)

### ISSUE THREAD

**Issue by WuVenus** [leatrix/leatrix-plus#247]
### Issue

Skeletal Warhorse The sound of running?
Thank you

### Game version

Classic Era

**Comment by leatrix** [comment]
In next week's release, there is a new setting in 'Mute game sounds' that will allow you to mute horse footstep sounds.  This includes the Skeletal Warhorse.

If you want to mute the summon sounds, you can add these IDs (from Leatrix Sounds) to 'Mute custom sounds'.

"sound/creature/horseundead/horseundeadattacka.ogg#552097",
"sound/creature/horseundead/horseundeadattackb.ogg#552096",
"sound/creature/horseundead/horseundeadattackc.ogg#552095",

**Comment by WuVenus** [comment]
It's in snow run there will be again Sound of horse hooves,
AV snow the same problem arises

**Comment by leatrix** [comment]
Thanks for the report.  This is fixed in 1.15.74.alpha.x.
