### ISSUE TITLE
Hide/Show unit nameplates automation

### ISSUE THREAD

**Issue by Gumika** [leatrix/leatrix-plus#25]
Hello Leatrix Team,

I ran into an issue with leatrix-plus where the enemy nameplates automatically turn of when out of combat, even though in the normal nameplate settings it's set to "Always show nameplates" and there doesn't seem to be an option for it in the addon.
I'd hate to cobble some other addons together for my preferences since leatrix is such a useful and great collection of addons I would otherwise use.

Thank you for your Support

**Comment by leatrix** [comment]
Did you enable the 'Combat plates' option ('System')?

**Comment by Gumika** [comment]
Yes it was enabled, and now it's fixed. I feel dumb for not seeing.
Thank you for helping!
