### ISSUE TITLE
Is it possible to add hide team group ! (Classic Era)

### ISSUE THREAD

**Issue by WuVenus** [leatrix/leatrix-plus#251]
### Issue

Player above and team group
![image](https://github.com/user-attachments/assets/9f171f14-7469-4b34-8e5e-0aaa5eaff6f7)
![image](https://github.com/user-attachments/assets/00ec98a1-57c6-49f9-b19b-68f1aa596480)
Look forward to
Thank you

### Game version

Classic Era

**Comment by leatrix** [comment]
For the player frame group indicator and the group labels displayed above the pullout raid frames, try 1.15.69.alpha.4.  There is a new option 'Hide raid group labels' ('Text').  You can switch CurseForge App to alpha releases by right-clicking the addon in your addon listing and changing the release type.  Let me know how you go on with it.

**Comment by WuVenus** [comment]
> For the player frame group indicator and the group labels displayed above the pullout raid frames, try 1.15.69.alpha.4. There is a new option 'Hide raid group labels' ('Text'). You can switch CurseForge App to alpha releases by right-clicking the addon in your addon listing and changing the release type. Let me know how you go on with it.

Work 
Very good
Love this feature
Thank you for your help

**Comment by WuVenus** [comment]
> For the player frame group indicator and the group labels displayed above the pullout raid frames, try 1.15.69.alpha.4. There is a new option 'Hide raid group labels' ('Text'). You can switch CurseForge App to alpha releases by right-clicking the addon in your addon listing and changing the release type. Let me know how you go on with it.

![image](https://github.com/user-attachments/assets/5b302a65-65f6-4666-9cd9-8403ebfb4afb)
no work

**Comment by WuVenus** [comment]
Player work

**Comment by leatrix** [comment]
Show a full screenshot.  Disable all addons except Leatrix Plus to see if its another addon.

**Comment by WuVenus** [comment]
> Show a full screenshot. Disable all addons except Leatrix Plus to see if its another addon.

![image](https://github.com/user-attachments/assets/ab16d966-bd6b-4c5b-9ea0-ff21de2acad6)
I disable all plugins

**Comment by WuVenus** [comment]
![image](https://github.com/user-attachments/assets/ff8d0c6c-736d-49ca-9686-3327adc265c8)
This is using the plugin

**Comment by leatrix** [comment]
Please try 1.15.69.alpha.5.  This now applies to the player frame group indicator and the group labels displayed above the compact raid frames and the pullout raid frames.

**Comment by WuVenus** [comment]
work Seems perfect I'll let you know if there's a problem later
Thank you very much for your help
<3
