### ISSUE TITLE
Show cooldowns is not working in Leatrix Plus

### ISSUE THREAD

**Issue by danplows** [leatrix/leatrix-plus#27]
Is there an issue whereby show cooldowns is not working? I cannot get them to show above my own/my targets frame. I'm on the latest version from Curse.

**Comment by leatrix** [comment]
If you wish to see cooldowns above your target frame, go into 'Show cooldowns' settings and ensure that 'Show cooldowns above the player frame' is unchecked.  Also ensure you are not showing buffs above your target frame already (right-click target frame > Move frame > Buffs on top should be unchecked).
Failing that, disable all other addons.  Does it work with other addons disabled?
