### ISSUE TITLE
Focus Frame movement

### ISSUE THREAD

**Issue by Fethbita** [leatrix/leatrix-plus#3]
Adding move and rescale options for focus frame could be good. That way focus frame position could be saved across characters.

**Comment by TheAmbition** [comment]
I'd love this as well. Thought it was weird that I was able to move and scale the player and target but not the focus frame.

**Comment by addonaddict** [comment]
I second this. Would be a great feature
A mover, scale, and reset buttons is all thats needed imo
Reset especially since default UI does not provide reset... unless you go to a text file and delete the stored location.. so weird

**Comment by leatrix** [comment]
Feedback appreciated.

**Comment by leatrix** [comment]
In Leatrix Plus 9.0.21, there is a new option to move and scale the focus frame.
