### ISSUE TITLE
FEATURE REQUEST: Add Darkmoon Dirigible for mount noice mute

### ISSUE THREAD

**Issue by Thom9521** [leatrix/leatrix-plus#32]
I love the Darkmoon Dirigible but the noice is so annoying, so it would be great if the mount could be added in the options for muting mounts.

**Comment by leatrix** [comment]
In 9.1.02.alpha.x, there are new settings for airships and zeppelins.  Zeppelins should do what you want but I have only tested it with game sounds (not the actual mount).
https://www.curseforge.com/wow/addons/leatrix-plus/files/all

**Comment by Thom9521** [comment]
It works. Thanks for the fast adjustement
