### ISSUE TITLE
Title and Target windows not unlockable now

### ISSUE THREAD

**Issue by devekrehbiel** [leatrix/leatrix-plus#33]
Not sure what you call them, but the two windows, one that displays your name, avatar, health, mana, etc and the target icon that shows the enemy or your targets health, hp, etc are not unlockable or moveable in your latest version. I like to have them nearer the center of the screen, but they are now cemented in the upper left corner. Checked this by disabling Leatrix Plus in the addon section (only) with all other addons Dominos, Handynotes, Recount, SexyMap, TomTom enabled. That fixes it. I want my Leatrix Plus back! Thank you! Great and very important addon!

**Comment by leatrix** [comment]
If disabling LTP alone fixes it, you have a conflict between 'Manage frames' and another one of your addons.

Disable all addons except Leatrix Plus.  Keep LTP enabled.  Does it work?  Enable other addons again gradually until you find the conflicting addon.

**Comment by devekrehbiel** [comment]
It does not work with LTP enabled and all other addons disabled. I like compactness in my addons, so I only have the ones listed above. Happy to help troubleshoot this problem. Thank you!

**Comment by leatrix** [comment]
If you want to use Manage frames (Frames) in LTP to save your Player frame and Target frame account wide:

- Disable all addons except LTP.
- Enable 'Manage frames' (Frames) in LTP and reload if prompted.
- Drag the player frame and target frame to where you want them to be.
- Reload your UI (/reload).  The frames should stay where you dragged them to.
- Enable your other addons gradually.  The frames should still stay where you dragged them to.
- With Manage frames enabled, the position of the player and target frames will be saved account-wide in LTP so you don't need to set them per character.

If you don't want to use 'Manage frames' and you would prefer Wow to save the frames to your character instead...

- Disable 'Manage frames' (Frames) in LTP and reload if prompted.
- Right-click each frame (player frame and target frame) and click > Move frame > Unlock frame (if it already says Unlock, just leave it at that).
- You can now drag the unlocked player frame and target frame to where you want them to be.
- When you reload, the frames should remain in the position you dragged them to.  If they do not, another addon is moving them.
- Note that frame positions set this way (without Manage frames) will be saved to your character by Wow.  They won't be saved account-wide.

**Comment by leatrix** [comment]
It sounds like you enabled Manage frames in LTP without realising that you then need to use LTP to move the frames.  So either use the Manage frames configuration panel to move the frames and have them be saved account-wide, or, don't use Manage frames and unlock and drag the frames manually per character.

**Comment by devekrehbiel** [comment]
YES! Thank you! I like this addon a lot. Keep up the great work. Sorry to bother you.
