### ISSUE TITLE
Feature Request: Move the crowd control display

### ISSUE THREAD

**Issue by JPortegijs** [leatrix/leatrix-plus#36]
Would love to be able to move the crowd control display, as it is in the middle of my screen.

Thanks in advance, love your work!

**Comment by leatrix** [comment]
Added to 9.1.06.alpha.3.  New option called 'Manage control' ('Frames').  If enabled, you can position and scale the loss of control frame.
https://www.curseforge.com/wow/addons/leatrix-plus/files/all

**Comment by JPortegijs** [comment]
That's amazing, thank you!

**Comment by wetleaftv** [comment]
Having a "Bottom Right Bar" to main bar option would be so awesome. I would love to stack 3 action bars in the center.
I love this addon and recommend it to everyone. Great work !!
