### ISSUE TITLE
Feature Request: Main Action Bar Option

### ISSUE THREAD

**Issue by wetleaftv** [leatrix/leatrix-plus#39]
Having a "Bottom Right Bar" to main bar option would be so awesome. I would love to stack 3 action bars in the center.
Thanks in advance. I love this addon and recommend it to everyone. Great work !!

**Comment by leatrix** [comment]
This is better handled by an addon such as [Bartender](https://www.curseforge.com/wow/addons/bartender4).  You can create 10 bars and position and scale them as you wish.

**Comment by wetleaftv** [comment]
I understand. Thanks.
