### ISSUE TITLE
Player/Target Frames slight offset on login

### ISSUE THREAD

**Issue by Seajams** [leatrix/leatrix-plus#4]
I've been having issues with Player/Target Frames not keeping the correct scaling or placement after a log in or a UI reload. They either don't scale up (target frame) or will be slightly out of place (player frame) from where I placed the frames on my UI. 
Opening the frame config menu will instantly and automatically scale and move the frames to where I have them set. Just a small annoyance having to open the config menu on log in to get everything into place.

**Comment by leatrix** [comment]
Another addon is moving the frames after Leatrix Plus positions and scales them.  Disable all other addons.  The problem should be solved.  Enable other addons gradually until you find the addon causing the problem.
