### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by suicidalkatt** [leatrix/leatrix-plus#40]
Got a rather distressing issue when downloading the latest version.

![image](https://user-images.githubusercontent.com/2445234/129984153-56005fa7-8620-4724-a23b-7d7b333dfccb.png)

**Comment by leatrix** [comment]
https://github.com/leatrix/leatrix-plus-bcc/issues/55

**Comment by leatrix** [comment]
Addons have now been updated (where needed).  The latest updates should no longer show false positives in Windows Defender.

If you still encounter issues, please use the thread above.
