### ISSUE TITLE
Addon doesn't let skip Korthia campaign.

### ISSUE THREAD

**Issue by UnoneTV** [leatrix/leatrix-plus#42]
This is a major issue that shouldn't even work that way in game, but EVEN IF YOU PRESS <SKIP THE CAMPAIGN> GOSSIP, TAKING NEXT QUEST MAKES IT REAL, THE SKIP DOESN'T GO OFF.

**Comment by leatrix** [comment]
9.1.10.alpha.1 - 6th September 2021
- Quests from Highlord Bolvar Fordragon (Oribos) will no longer be selected, accepted and turned-in automatically.  This allows for the Korthia campaign skip to be selected.

https://www.curseforge.com/wow/addons/leatrix-plus/files/all

Untested but this should fix it I imagine.  Thanks for the report.
