### ISSUE TITLE
Quest Frame afterimage with immersion

### ISSUE THREAD

**Issue by hsleedevelop** [leatrix/leatrix-plus#46]
Leatrix Plus (Shadowlands) - 9.1.09
Immersion - 1.3.7 retail 

Quest Frame loaded when afterimage remained, very often or always
https://www.curseforge.com/wow/addons/immersion?comment=1045

check above link plz.

**Comment by leatrix** [comment]
The immersion fix from 9.1.06 is removed in 9.1.10.alpha.2.
https://www.curseforge.com/wow/addons/leatrix-plus/files/all

**Comment by leatrix** [comment]
Immersion fix is removed in 9.1.10 too.

9.1.10 - 16th September 2021
- Removed the Immersion addon fix from 9.1.06.  The Immersion addon breaks key Blizzard quest events which can prevent 'Automate quests' from working properly.  If you want to use the full functionality of 'Automate quests', you should remove the Immersion addon.
