### ISSUE TITLE
Blood elf Paladin Female shout

### ISSUE THREAD

**Issue by blecaplol** [leatrix/leatrix-plus#47]
Hi not sure why but this update broke it I can still hear the shout or attackshout whenever I attack a mob.  For Shadowlands.

**Comment by leatrix** [comment]
Is the sound played in response to a casting a specific spell?  I am not able to tell the difference.  Perhaps you could share a video?

For blood elf female, the following sounds are muted by LTP:
sound/character/bloodelffemalepc/vo_bloodelffemale_main_battleshoutlarge_01.ogg#1385124
sound/character/bloodelffemalepc/vo_bloodelffemale_main_battleshoutlarge_02.ogg#1385125
sound/character/bloodelffemalepc/vo_bloodelffemale_main_battleshoutlarge_03.ogg#1385126
sound/character/bloodelffemalepc/vo_bloodelffemale_main_battleshoutlarge_04.ogg#1385127
sound/character/bloodelffemalepc/vo_bloodelffemale_main_battleshoutlarge_05.ogg#1385128
sound/character/bloodelffemalepc/vo_bloodelffemale_main_battleshoutlarge_06.ogg#1385129

If you have Leatrix Sounds installed, you can search for this sound file pattern to hear them all:
vo_bloodelffemale_main_battleshoutlarge

Obviously, the sounds will be muted in LTS if you have 'Shouts' enabled in LTP.

I'm not sure that battleshoutlarge sounds are even used by the game anymore as I didn't notice any difference with 'Shouts' checked on or off for a few classes and races.  So it maybe that the 'Shouts' checkbox will be removed.

LTP has never muted the general attacking sounds such as grunts.  It only muted the overly long and wailing battleshoutlarge sounds.

**Comment by leatrix** [comment]
The 'Shouts' checkbox is removed in LTP 9.1.10 as the sounds that it muted don't appear to be used by the game anymore.

**Comment by blecaplol** [comment]
> The 'Shouts' checkbox is removed in LTP 9.1.10 as the sounds that it muted don't appear to be used by the game anymore.

There's 2 kind of shout I noticed one where it isn't really a shout more like it came out when Blood elfs were a playable race. That was the default sound where it's sounded "soft". 
The second one is the new retail kind I think where it shouts each time U use a spell or something. It sound stupid.  So, it can't be muted anymore? Because I swear it was muted before.

**Comment by leatrix** [comment]
When I tested female blood elf paladin, all I heard were the occasional grunts that have always been there along with a couple of new, very short grunts.  I didn't hear a shout every time I cast a spell.  I no longer heard battleshoutlarge at all and that's the only sound that was muted with the 'Shouts' setting.  If you can share a video, that would help.

**Comment by blecaplol** [comment]
Okay here's a short clip:
[https://streamable.com/ua88kx](url)

Pretty sure those are battleshoutlarge and almost everytime I press some skill it just did those shouts.

**Comment by leatrix** [comment]
It's interesting.  They don't appear to be battleshoutlarge.  Comparing Leatrix Sounds data between game version 9.1.0.40120 (current game version) and 9.1.0.39804 (a month ago), there are a lot of changes but they're all related to music and the new Hearthstone Wow mount.  I also checked back to 9.1.0.39427 (27th July 2021) but found no changes relating to character combat sounds.  Unless the files aren't in the listing yet (listing uses publically available data since Blizzard don't support filenames anymore).

If you want to help search, install [Leatrix Sounds](https://www.curseforge.com/wow/addons/leatrix-sounds), enter /lts, ensure the dropdown is set to Sound Files then enter some search criteria.

You can enter up to 10 keywords (in any order), such as 'blood elf female' and you can include words such as 'charge', 'attack', 'shout', etc.  While a track is selected, press W and S to traverse the listing quickly (makes searching for sounds much faster).

A lot of the wailing combat sounds have vo_ in the filename so you can add that to your search if you wish.

As I said though, Leatrix Sounds can only list tracks that are publically known about.

**Comment by blecaplol** [comment]
Oh you're right they are not battelshoutlarge (they sounded really nearly the same). So I found out they are the meleewindup

vo_bloodelffemale_main_meleewindup_01.ogg#1385146 so on until 10.ogg, there are 10 sounds of it. Wondering are you able to mute them?

**Comment by leatrix** [comment]
Doesn't appear to be.  I tried muting these:

```
"sound/character/bloodelffemalepc/vo_bloodelffemale_main_meleewindup_01.ogg#1385146",
"sound/character/bloodelffemalepc/vo_bloodelffemale_main_meleewindup_02.ogg#1385115",
"sound/character/bloodelffemalepc/vo_bloodelffemale_main_meleewindup_03.ogg#1385116",
"sound/character/bloodelffemalepc/vo_bloodelffemale_main_meleewindup_04.ogg#1385117",
"sound/character/bloodelffemalepc/vo_bloodelffemale_main_meleewindup_05.ogg#1385118",
"sound/character/bloodelffemalepc/vo_bloodelffemale_main_meleewindup_06.ogg#1385119",
"sound/character/bloodelffemalepc/vo_bloodelffemale_main_meleewindup_07.ogg#1385120",
"sound/character/bloodelffemalepc/vo_bloodelffemale_main_meleewindup_08.ogg#1385121",
"sound/character/bloodelffemalepc/vo_bloodelffemale_main_meleewindup_09.ogg#1385122",
"sound/character/bloodelffemalepc/vo_bloodelffemale_main_meleewindup_10.ogg#1385123",
```
But the sounds were still there when tanking with a female blood elf protection paladin.

If you want to test muting sounds, open Leatrix_Plus.lua with a text editor (I recommend [Notepad++](https://notepad-plus-plus.org/downloads/)) and add this to the end of the file:

`MuteSoundFile(1385146)`

where 1385146 is the file ID shown in Leatrix Sounds after the #.  When you mute sounds this way, they remain muted until you relaunch the game client (logging out and in is not enough).  So if you want to unmute the sound after muting it, without relaunching the game client, you need to run this:

`UnmuteSoundFile(1385146)`

Instead of editing Leatrix_Plus.lua, you can just prefix either command with /run and enter it in the chat window if you prefer (though you might forget what you have muted this way):

```
/run MuteSoundFile(1385146)
/run UnmuteSoundFile(1385146)
```

If you find the sound files, I can add a checkbox to mute them.  That's if they exist in the publically available data yet.

**Comment by blecaplol** [comment]
I think I found the problem to the issue. I too tried and it doesn't mute for this command 1-10.ogg
**"sound/character/bloodelffemalepc/vo_bloodelffemale_main_meleewindup_01.ogg#1385146"**

and then I continued listening on /LTS for the filename and then muted these 1-10.ogg

**"sound/character/pcdhbloodelffemale/vo_dhbloodelffemale_meleewindup_01.ogg#1389830** 

These are just for female and I also did not mute Metamorphosis form meleewindup for DH just fyi.

It stated as DH though not sure but it affect both DH and Paladin female Blood elf. It's mostly quiet now except for the occasional grunt and weirdly now I'm seeing another bunch of filename containing "generic" lol this is a headache to pinpoint every single melee windup.

Also I'm not completely perfect muting everything cause it is tedious to search the # from every .ogg filename and then put it into the script. I search keyword as suggested by you and go from there I will surely missed out a few sound.
Is there a way to speed it up? Like copy pasting the filename shown in /lts into notepad, etc?

Lastly, if this can be an option for the future patch of LTP? It'd be great! But it may take some work for you to fnd every melee windup, attack sound for every class, race and yea you get me. Just a request and I understand if it takes too much time to implement.

**Comment by leatrix** [comment]
I actually discovered this at the same time you did (though not by the same means, I just muted blocks of sound IDs until the relevant sounds no longer played).

So the filenames are indeed:

sound/character/pcdhbloodelffemale/vo_dhbloodelffemale_meleewindup_01.ogg#1389830
sound/character/pcdhbloodelffemale/vo_dhbloodelffemale_meleewindup_02.ogg#1389831
sound/character/pcdhbloodelffemale/vo_dhbloodelffemale_meleewindup_03.ogg#1389832
sound/character/pcdhbloodelffemale/vo_dhbloodelffemale_meleewindup_04.ogg#1389833
sound/character/pcdhbloodelffemale/vo_dhbloodelffemale_meleewindup_05.ogg#1389834
sound/character/pcdhbloodelffemale/vo_dhbloodelffemale_meleewindup_06.ogg#1389835
sound/character/pcdhbloodelffemale/vo_dhbloodelffemale_meleewindup_07.ogg#1389836
sound/character/pcdhbloodelffemale/vo_dhbloodelffemale_meleewindup_08.ogg#1389837
sound/character/pcdhbloodelffemale/vo_dhbloodelffemale_meleewindup_09.ogg#1389838
sound/character/pcdhbloodelffemale/vo_dhbloodelffemale_meleewindup_010.ogg#1389839

So it seems Blizzard used demon hunter sound files for paladin too.  I'll look at adding a checkbox although it will include a lot of sound files.  But then, they are rather annoying.

Read the Help button tooltip in LTS to find out how to do copy/paste.  To put a track into the chat editbox, hold shift and right-click it.  Then you can press CTRL/C to copy and CTRL/V to paste it into Notepad.

If you want to copy a selection of tracks, you can do it with 'Recent chat window' ('Chat') in LTP (enable it if you haven't already).  SHIFT-left click on the tracks you want to copy.  They will be printed in the chat window.  Now CTRL/left-click the chat tab to open the recent chat window.  The tracks will be shown in the recent chat window.  Now you can drag and CTRL/C to copy them and CTRL/V to paste into Notepad.

**Comment by leatrix** [comment]
In 9.11.alpha.1, there is a new setting called 'Windup (Melee Combat') in 'Mute sound files' ('System').  If enabled, melee combat windup sounds for all races will be muted.

**Comment by blecaplol** [comment]
Sweet! For now I will temporary paste those into the lua file as suggested above. Cant wait for the new version! Thank u!

**Comment by blecaplol** [comment]
Hi Leatrix if its not a problem for you, in general, battleshoutslarge can they be have an option or be together same option for windup melee to be muted with a single click? 
Just happened to play my undead male war and thought the battleshoutlarge were muted but they aren't for a reason.
Male:
sound/character/playerexertions/undeadmalefinal/vo_undeadmale_main_battleshoutlarge_03.ogg#1383691
sound/character/playerexertions/undeadmalefinal/vo_undeadmale_main_battleshoutlarge_03.ogg#1383692
sound/character/playerexertions/undeadmalefinal/vo_undeadmale_main_battleshoutlarge_03.ogg#1383693
sound/character/playerexertions/undeadmalefinal/vo_undeadmale_main_battleshoutlarge_04.ogg#1383694
sound/character/playerexertions/undeadmalefinal/vo_undeadmale_main_battleshoutlarge_05.ogg#1383695
sound/character/playerexertions/undeadmalefinal/vo_undeadmale_main_battleshoutlarge_06.ogg#1383696
sound/character/playerexertions/undeadmalefinal/vo_undeadmale_main_battleshoutlarge_07.ogg#1383697
sound/character/playerexertions/undeadmalefinal/vo_undeadmale_main_battleshoutlarge_08.ogg#1383698
sound/character/playerexertions/undeadmalefinal/vo_undeadmale_main_battleshoutlarge_09.ogg#1383699

sound/character/playerexertions/undeadmalefinal/vo_undeadmale_main_charge_01.ogg#1383706
sound/character/playerexertions/undeadmalefinal/vo_undeadmale_main_charge_02.ogg#1383707
sound/character/playerexertions/undeadmalefinal/vo_undeadmale_main_charge_03.ogg#1383708
sound/character/playerexertions/undeadmalefinal/vo_undeadmale_main_charge_04.ogg#1383709
sound/character/playerexertions/undeadmalefinal/vo_undeadmale_main_charge_05.ogg#1383710
sound/character/playerexertions/undeadmalefinal/vo_undeadmale_main_charge_06.ogg#1383711
sound/character/playerexertions/undeadmalefinal/vo_undeadmale_main_charge_07.ogg#1383712

**Comment by leatrix** [comment]
Good idea.  In 9.1.11.alpha.2, the 'Shouts' checkbox is back and now mutes MeleeWindup, BattleShoutLarge and Charge for all races.  If you hear any shouts and wails after installing this update, just let me know race/class/spec.

https://www.curseforge.com/wow/addons/leatrix-plus/files/all

**Comment by blecaplol** [comment]
Will do that and thank you a lot again!
