### ISSUE TITLE
Problem with the Auto Release

### ISSUE THREAD

**Issue by xprepaidx** [leatrix/leatrix-plus#48]
I believe its with this addon, but when the Auto Release spirit happens, sometimes i literally cant click anything on the screen with my mouse. Not sure why. Maybe it auto releases too fast? When it happens, whatever my last action was (like moving forward) my character will keep moving forward and not stop. Only fixed by relogging.

**Comment by leatrix** [comment]
Just want to make sure - is this with Shadowlands, BCC or Classic Era?

**Comment by xprepaidx** [comment]
Sorry, this is with Shadowlands

**Comment by leatrix** [comment]
This issue was reported for Classic quite a long time ago so a 200ms delay was added (just for BCC and Classic Era) before the release button is automatically clicked.  That helped but I'm not sure if that completely resolved it.  There haven't been any reports of it happening since though.

Shadowlands auto release code works differently to Classic though and there have been no reports of this issue in Shadowlands so the 200ms delay was not added to Shadowlands.

To rule out other addons, if you uncheck 'Release in PvP' in Leatrix Plus, does your character still automatically release or does it remain dead?

**Comment by xprepaidx** [comment]
With it unchecked, i do not autorelease when dying and when its checked, auto releases instantly

**Comment by xprepaidx** [comment]
I wouldnt mind trying out a change if you want to apply that MS change or anything. It's a really great addon. That one feature i might not be able to use if it is the culprit

**Comment by leatrix** [comment]
Try 9.1.13.alpha.3 or higher.
https://www.curseforge.com/wow/addons/leatrix-plus/files/all

It has a 200ms delay before your character respawns.  I don't know if it will help though.  If it doesn't, you can try larger delays if you wish.  Open Leatrix_Plus.lua in Notepad++, search for `if InstStat and InstType == "pvp" then` (it's around line 9115) and change the 0.2 value below it to a larger value (0.2 is 200ms, 0.5 would be 500ms, etc).  If you're testing in a world PvP zone, there is a second 0.2 value that you need to change a few lines below.  You can see what happens with a really large value such as 3000 if you wish (that's 3 seconds, just remember to wait for the automatic release).

Which battleground are you in when it happens?  How often does it happen?  How long has it been happening?

**Comment by xprepaidx** [comment]
It was in Kotmogu and Gilneas at least. I'd say about a few weeks that i've noticed but i havent played much the past month or 2 months. Im playing more so i may notice more. I play in the evening for a few hours or so and it usually has been happening at least once a day to once every 3 days. So it's not something that happens every time.

**Comment by xprepaidx** [comment]
Ive downloaded the alpha and will keep a watch for you

**Comment by xprepaidx** [comment]
Ill try to change the MS for next time im on and report back. It happened with the 200ms you added. So next i'll probably make it say, 300MS and see what happens and let you know

**Comment by leatrix** [comment]
You should probably try around 1000 at least to see if there's a difference.  It will be quicker to jump to a higher number now than it would be to start at a lower number and gradually go higher.  I'm not even sure that the timing is the problem so start at a high number (at least 1000) and see if it still does it.

**Comment by xprepaidx** [comment]
Sure will. Also noticed i can just do a /reload to fix it once it happens.

**Comment by xprepaidx** [comment]
Thanks! Also so far, the 1 second delay seems to be okay for testing half of today

**Comment by xprepaidx** [comment]
Sure will. Ill start with 400 then 600 and should be able to let you know the result sometime tomorrow or sunday

**Comment by xprepaidx** [comment]
Well, i was trying to use the Slider, and when i put it at 300-400, it wasnt auto releasing. So maybe the slider doesnt work entirely correctly. Just an FYI. Auto Release in the config file manually setting it was working fine at 500MS. Sorry i haven't responded back recently

**Comment by xprepaidx** [comment]
small update. the slider doesnt work at 300MS or 200MS

**Comment by xprepaidx** [comment]
But it does work at 500MS+ so far that ive noticed

**Comment by xprepaidx** [comment]
Also ever since i set my auto release to be at 500, the glitch hasnt happened again with the screen being where i cant click until i logout or /reloadui

I'm now trying at 400MS. Seems to auto release, not sure if the non-clickable screen will happen yet.

**Comment by xprepaidx** [comment]
Last update i think for the day. 400ms seems to be a hit/miss with auto release. Not sure why. Sometimes it works sometimes it doesnt. I dont think i had that problem with 500+

**Comment by leatrix** [comment]
Interesting.  You said that adding 0.5 to the config file manually worked.  But did you try adding 0.2 or 0.3 to the config file manually?

I tested it by moving the slider (in the panel) to 200ms, 300ms, 400ms and 500ms and it works fine every time.  Are you sure that (a) you didn't have any of the exclude battleground settings checked, (b) another addon wasn't conflicting and (c) your character didn't have a means to self-resurrect (such as soulstone, reincarnation, Brazier of Awakening, etc)?  Or maybe that particular section of the battleground prevented a release?  How many times did it fail at 200ms/300ms?

If you want to test it outside of a battleground, comment out the lines:

`if InstStat and InstType == "pvp" then`
... and it's matching `end` statement 17 lines lower (it's the line after the end) statement)

... and reload (to comment out, just prefix the lines with --).  You should then auto release everywhere.  To test it, bank of all your equipped items, fly upwards and dismount leading to death, it should auto release, talk to the spirit healer to resurrect there on the spot then repeat (fly up, dismount, die, auto release, talk to spirit healer).

Obviously, this won't be any use for testing the non-clickable UI in battlegrounds but it will let you test the delay settings perhaps more conveniently and at your own pace.

**Comment by xprepaidx** [comment]
I have not tried manually inputting in the config file to be .2/.3/.4. Is it possible that upon the auto release clicking the button that during combat, your character might still be in the midst of some attack stopping the auto release? Earlier in the 3-cart bg (cant think of the name), when i was getting attacked by basically half the team, it wouldnt auto release upon death. although I think i saw the UI of the release option flicker. which was when it was set to 400MS with the slider. Maybe it was a small glitch or something.

When you tested the slider from 200-500, was in you in multiple bgs or just doing it outside when falling to your death?

A) I do not have any exclude options
B) I dont believe i have any other addons conflicting, or at least i saw no other LUA errors popping up.
C) Nope, no other means to resurrect except to release.

It failed every time in bgs when it was set to 200-300 (i had it set to 200 or 300 for days and it would never auto release for me). but it seems to halfwork at 400. Maybe its just me, which is fine and i'd hate for you to spend so much time on something that's just directed at me.

**Comment by leatrix** [comment]
Try disabling other addons to make sure.  Don't rely on the lack of a Lua error to prove its working fine - another addon could still interfere with it.

If possible, try the PvE die and instant res method I explained above and see if that works at 200ms and 300ms.

The only time I have seen the release button not working instantly is when a graveyard has just been taken or something like that preventing res there.

**Comment by xprepaidx** [comment]
Sorry, havent had time to test this out. i will soon!

**Comment by AlexFolland** [comment]
This bug sounds like it stems from using RepopMe instead of post-hooking the StaticPopupDialogs["DEATH"] OnUpdate function.  My addon, BattlegroundSpiritReleaser, has no issue like this because it is guaranteed to happen only when the StaticPopupDialogs["DEATH"] dialog is visible and updating.

Here's the main hook in my addon, in case you get inspired to change how this works in Leatrix Plus, to avoid all unexpected timing issues.

```lua
--the main functionality; post-hook for death StaticPopup
hooksecurefunc(StaticPopupDialogs["DEATH"],"OnUpdate",function(self)
	if InActiveBattlefield() and not IsActiveBattlefieldArena() then
		if HasSoulstone() and BattlegroundSpiritReleaserDB.UseSoulstone ~= nil and BattlegroundSpiritReleaserDB.UseSoulstone == true then
			if BattlegroundSpiritReleaserSoulstoneDelayStartTime ~= nil and self.button2:IsEnabled() and GetTime() >= BattlegroundSpiritReleaserSoulstoneDelayStartTime + BattlegroundSpiritReleaserDB.SoulstoneDelay then
				self.button2:Click()
				print("BattlegroundSpiritReleaser: Soulstone used"..(BattlegroundSpiritReleaserDB.SoulstoneDelay == 0 and "" or " after a delay of "..tostring(BattlegroundSpiritReleaserDB.SoulstoneDelay).." second"..(BattlegroundSpiritReleaserDB.SoulstoneDelay == 1 and "" or "s"))..". You can toggle this functionality with \"/bsr soulstone\".")
			end
		elseif self.button1:IsEnabled() and BattlegroundSpiritReleaserDB.Enabled ~= nil and BattlegroundSpiritReleaserDB.Enabled == true then
			self.button1:Click()
		end
	end
end)
```

**Comment by leatrix** [comment]
Many thanks, Alex.  Added the OnUpdate hook to alpha.12 for testing.

**Comment by AlexFolland** [comment]
I reviewed your code change and it looks great!  Hopefully someone can test it.
