### ISSUE TITLE
Feature Request: Hide minibar + bags

### ISSUE THREAD

**Issue by JPortegijs** [leatrix/leatrix-plus#49]
Would be awesome to have this option in Leatrix, makes me not have to install Bartender or such. Could go under Frames > Visibilty, I suppose?

**Comment by plopek** [comment]
This^ Would love that ption.

**Comment by leatrix** [comment]
Added to 9.1.25.alpha.4.  A new option called 'Hide bags and micro' ('Frames').
https://www.curseforge.com/wow/addons/leatrix-plus/files/all
