### ISSUE TITLE
Feature Request: Moveable durability, vehicle bar, and boss-frames below map

### ISSUE THREAD

**Issue by addonaddict** [leatrix/leatrix-plus#5]
Hello,

First of all LOVE the addon, thank you for keeping it going
I would really enjoy it if you could add option to scale and move vehicle bar, durability frame, and boss-frames (similar to player buffs and debuffs)
A lot of people use custom minimap addons or objective trackers like Kaliel's tracker, but the downfall of that is having these frames sit on top of the minimap/tracker (depending on size and location)
Your moveable auras fixes that, but everything else would require yet another over-kill addon like MoveAnything, for just moving few frames around

I hope you'd find this worth implementing
Thanks and have a good day :)

**Comment by leatrix** [comment]
Feedback appreciated.
