### ISSUE TITLE
Hide Tooltip in combat even if shift button pressed?

### ISSUE THREAD

**Issue by Keksecute** [leatrix/leatrix-plus#51]
Hi!, typically I've used the Tip Tac addon but wanted to convert to Leatrix since I use it for many other things. Could you please add a setting to hide tooltips in combat despite the shift button being pressed or not?

Thanks!

**Comment by leatrix** [comment]
Is it because you have spells bound to shift modified keys?  What if the override key was set to the control key instead of shift?

**Comment by Keksecute** [comment]
> Is it because you have spells bound to shift modified keys? What if the override key was set to the control key instead of shift?

Yes I use a shift modifier for every key bound, but I also use control for some. Having the option to toggle visibility with control would be better than only shift, but having the option to turn it off in combat entirely would be preferable!

**Comment by Swordart25** [comment]
yoo is it possible ?

**Comment by leatrix** [comment]
In the latest alpha, there is a setting to toggle the shift override for hidden tooltips.

**Comment by Swordart25** [comment]
thank you!
