### ISSUE TITLE
Feature Request: Several suggestions

### ISSUE THREAD

**Issue by atralolz** [leatrix/leatrix-plus#53]
Hi.
Thank you for awesome addon.
I have some code for personal use, but maybe you modify and add that functions.
1. Add field with nick name for change name on player frame, target of target and other where showing player nick name.
2. Spec icon on target & focus portrait (in PvP).
3. Coloring spell icons in red if out of range and blue if out of mana.
4. Short format for numeric values on player, targer & focus frames. Something like that:
![image](https://user-images.githubusercontent.com/42596339/140290924-0f20ec4c-1fcb-4de3-934c-f1907835a2b8.png)
5. Hide text for macros and binds on panels.

My code: https://github.com/atralolz/custom

**Comment by leatrix** [comment]
This is for BCC or Classic Era?

**Comment by atralolz** [comment]
This is for Shadowlands.

**Comment by leatrix** [comment]
Thanks for the suggestions and code samples.  Added 'Hide action button text' ('Text') for now.
