### ISSUE TITLE
Enhance Tooltip Issue

### ISSUE THREAD

**Issue by fr-ank** [leatrix/leatrix-plus#54]
Enhance Tooltip no longer changes the tooltip appearance in 9.1.5.

**Comment by leatrix** [comment]
It works fine for me.  Disable other addons and try again.

**Comment by fr-ank** [comment]
I have disabled all addons, deleted WTF, Cache, and Interface but the tooltip background color/border doesn't change when using Enhanced Tooltip like it used to.  Resizing and moving the anchor works, just not the appearance change for me.

**Comment by leatrix** [comment]
You should keep your addons up to date.  [CurseForge App](https://download.curseforge.com/) is good for that.  You can see the change log in the app too.

From the LTP change log:
9.1.09 - 6th September 2021
- Updated for game version 9.1.5 (currently on PTR).
- Removed the tooltip backdrop color option from 'Enhance tooltip' ('Interface').

Blizzard completely changed how tooltip backdrop colors work in 9.1.5 so the setting was removed for the time being.
