### ISSUE TITLE
Hide hotkeys, macro text, class colored name backdrop in frames

### ISSUE THREAD

**Issue by plopek** [leatrix/leatrix-plus#55]
I really miss those things in Leatrix. Would love to see them implemented. Would literally spare me using 3 different addons.

**Comment by leatrix** [comment]
Enable 'Hide action button text' ('Text') to hide hotkey text and macro text on action buttons.  It was added recently so be sure to keep Leatrix Plus updated.

Enable 'Class colored frames' ('Frames') for class colored name backdrop in frames.
