### ISSUE TITLE
Please add the new Sunwarmed Furline mount the the mute list 

### ISSUE THREAD

**Issue by amzeus1976** [leatrix/leatrix-plus#56]
the ids are 3598611,3598625

cant go to capital cities at the moment for people spamming the mount and special sounds

**Comment by leatrix** [comment]
Added to the latest alpha (at least 9.1.23.alpha.1).  New setting called 'Furlines'.
https://www.curseforge.com/wow/addons/leatrix-plus/files/all

**Comment by amzeus1976** [comment]
massive thanks :)
