### ISSUE TITLE
window management

### ISSUE THREAD

**Issue by Roberto-22** [leatrix/leatrix-plus#57]
window management no longer works since patch 9.15 the character window keeps moving back to the default setting
dont know why? have you an answer for this?

**Comment by leatrix** [comment]
Do you mean PlayerFrame resets/bugs when you enter a vehicle.  It's nothing to do with LTP.  It's a bug with the default UI that was introduced in patch 9.1.5.  Happens without any addons installed too.

For the time being and if you're using 'Manage frames' ('Frames'), if PlayerFrame resets/bugs after you exit a vehicle, just reload your UI (/rl) and it should put PlayerFrame back to where it was before.  This is better than the default UI at least.
https://github.com/leatrix/leatrix-plus/issues/52

**Comment by leatrix** [comment]
I'll close this so there's only one open ticket about this issue.  If you want to add anything, please use https://github.com/leatrix/leatrix-plus/issues/52.

**Comment by leatrix** [comment]
Blizzard still haven't fixed the bug (yet) so I added a temporary fix in 9.1.23.alpha.11 (or higher). To use the temporary fix, you need to have 'Manage frames' ('Frames') enabled. When entering or exiting a vehicle, the player frame will be restored to your chosen location as soon as you leave combat. This temporary fix will be removed once Blizzard fix the bug with the player frame and vehicles.
https://www.curseforge.com/wow/addons/leatrix-plus/files/all
