### ISSUE TITLE
Player frame

### ISSUE THREAD

**Issue by Phatmoose** [leatrix/leatrix-plus#58]
My player frame keeps resetting to default location when I load into dungeons or my avatar changes. I am not sure if it changes anymore then that It has been happening since 9.1.5 update, also I have not tested since todays release.

**Comment by leatrix** [comment]
It's a bug in the default UI that was introduced in 9.1.5.  It happens without any addons enabled.  It's nothing to do with Leatrix Plus.  It's affecting a large number of people.

While waiting for Blizzard to fix it, you have two options:

If you don't mind having your player frame in the default position, enable 'Manage frames' ('Frames'), open the configuration panel for 'Manage frames' and click the 'Reset' button.  The player frame will be reset to the top-left corner.  Keep it there until Blizzard fix the bug.  Don't try to move it.  You can move the target frame if you wish though as there's no issue with that.  This is the preferred option.

Alternatively, enable 'Manage frames' ('Frames') and move the player frame to wherever you wish.  When exiting a vehicle, if the player frame has reset to the top-left, just reload your UI (/rl).  The player frame should be back to where you want it.  Don't reload while you're actually on a vehicle.  Wait until you exit the vehicle first.

https://github.com/leatrix/leatrix-plus/issues/52

**Comment by leatrix** [comment]
Blizzard still haven't fixed the bug (yet) so I added a temporary fix in 9.1.23.alpha.11 (or higher).  To use the temporary fix, you need to have 'Manage frames' ('Frames') enabled.  When entering or exiting a vehicle, the player frame will be restored to your chosen location as soon as you leave combat.  This temporary fix will be removed once Blizzard fix the bug with the player frame and vehicles.
https://www.curseforge.com/wow/addons/leatrix-plus/files/all

**Comment by leatrix** [comment]
https://github.com/leatrix/leatrix-plus/issues/52
