### ISSUE TITLE
Feature Request: Book & Mute Rockets(Mounts)

### ISSUE THREAD

**Issue by Plusader** [leatrix/leatrix-plus#6]
**Turning book pages**
Are you able to implement a feature that allows book sites to be turned using the mouse-wheel? I'd would be much more comfortable to read/skip through one by just scrolling down.

**Rocket Sounds**
I've newly discovered the possibility to mute mounts, like the bikes, which is always used during early leveling and in comparison to other mounts gets annoying quite fast due to its sound characteristics.
I'd like to see that mechanism work for rockets as well. Especially the one named "X-53 Touring Rocket" from the recruit a friend programm(2-seater, which is relatively small).

**Comment by leatrix** [comment]
'Rockets' added to 'Mute game sounds' ('System') in 9.0.13.alpha.1.
https://www.curseforge.com/wow/addons/leatrix-plus/files/all

**Comment by Plusader** [comment]
Thanks. That went fast. Installting it by default when it's released.
While checking if the "turn-book-pages-by-mousewheel" option is eventually already implemented I have spotted the following:

In the "Interface" section in "Extras" there is an option called "Show Wowhead links". 
These links are also shown for quests in the quest log, which isn't mentioned in the tooltip yet.

Best Regards

**Comment by leatrix** [comment]
When you click on a quest in the quest log, the Wowhead link is shown in the world map frame.  That's what the option tooltip says.
With the books, many book pages require scrolling with the mousewheel to see the entire page.

**Comment by Plusader** [comment]
Well then, thanks for your support!
