### ISSUE TITLE
buff bar acting weird in 9.1.25.alpha.6

### ISSUE THREAD

**Issue by hewozuoai** [leatrix/leatrix-plus#61]
Tracked down the buff bar (default near minimap) acting weird in this commit (https://github.com/leatrix/leatrix-plus/commit/d3bda5d1474f257fb2d3637f783bf1a47f47e995)

alpha.5 (d5bd4b779faae9178a47083b4234e081be493999)
![image](https://user-images.githubusercontent.com/5726207/144346417-d1ef046c-71af-408c-b5bc-9e7e79ff48ec.png)

alpha.6
![image](https://user-images.githubusercontent.com/5726207/144346523-e0b78735-567d-4143-9e38-660354c367a6.png)

**Comment by leatrix** [comment]
Install 9.1.26.  The problem is fixed.  Sorry about that.  You can now move the minimap anywhere you like and it will scale independently of the action bars and buff frame.

https://github.com/leatrix/leatrix-plus-classic/issues/26

**Comment by hewozuoai** [comment]
:+1:
