### ISSUE TITLE
Ability to mute Dusklight Razorwing

### ISSUE THREAD

**Issue by taylorlanglopez** [leatrix/leatrix-plus#62]
Can you please add the ability to mute the mount Dusklight Razorwing, please and thank you, it also has an annoying chirp just like the Furline mount and it's quite annoying <3

**Comment by leatrix** [comment]
Added to 9.1.27.alpha.8.  Untested though.
https://www.curseforge.com/wow/addons/leatrix-plus/files/all

> 9.1.27.alpha.8 - 2nd December 2021
> - Added 'Razorwings' to 'Mute game sounds' ('System').

**Comment by leatrix** [comment]
And in 9.1.36.alpha.2, the 'Razowings' setting actually works too!
Sorry about that.  The database that I extracted the sound data from is linking the mount model to the monster sounds which is incorrect.  It should be linked to the mount sounds.  I have updated the data in the addon and now the mount is being correctly muted.  Well, I did say that it was untested.  You can still reply to closed tickets to let me know if something doesn't work.
