### ISSUE TITLE
Make the original GarrisonLandingPageMinimapButton an option

### ISSUE THREAD

**Issue by LudiusMaximus** [leatrix/leatrix-plus#65]
Since the latest retail version LeatrixPlus replaces the GarrisonLandingPageMinimapButton with its own version thereof. I'm still not sure whether I like this or not. I could not find an option to toggle this. Would be great if such a toggle existed. Thanks! :-)

**Comment by leatrix** [comment]
Are you using the square or round minimap?

**Comment by LudiusMaximus** [comment]
The round minimap.

**Comment by leatrix** [comment]
Added to 9.1.31.alpha.4 (or higher).
https://www.curseforge.com/wow/addons/leatrix-plus/files/all

There is a new setting (disabled by default) that lets you choose whether you want to use the new covenant button for the round minimap.  So if you want the classic look, you can now choose that.  The square minimap will always use the new covenant button regardless of this new setting.

**Comment by LudiusMaximus** [comment]
Great, thanks a lot for the immediate reaction!! :-)
