### ISSUE TITLE
A True conflict

### ISSUE THREAD

**Issue by cjdug66** [leatrix/leatrix-plus#67]
![leatrix plus](https://user-images.githubusercontent.com/96155079/146104178-80aff7e4-c1a7-4ccd-93b4-a3534467a2ed.jpg)
 as you can see in the image, Leatrix plus is truly preventing me from having the icon on my mini map to open my covenant renown.  Hope you can fix this as each time I want to open it I have to disable leatrix plus first. I love this add on by the way.
Julia

**Comment by leatrix** [comment]
Hi Julia,

I think you're saying that there is no covenant button anymore for you to click on?

With 'Enhance minimap' ('Interface') enabled, the large covenant button is replaced by a standard purple button.  You can see it there in your screenshot.  Did you try to click it?  It opens your covenant report window with renown, etc just as the original button did.

If you prefer to have the original covenant button back, install the latest alpha. There is a new setting under 'Enhance minimap' ('Interface') called 'Show new covenant button'.  Uncheck that and reload.  The original button will return.

Both buttons do the same thing though.  In fact, the new purple button is actually the large original button underneath but with a new texture and scaled down slightly.
