### ISSUE TITLE
[Feature Request] Disband whole raid/party command

### ISSUE THREAD

**Issue by zeenk** [leatrix/leatrix-plus#72]
Is this something that could possibly make it into Leatrix plus? Have a keyword like /ltp disband or something like that. I know Method raid tools got this feature in their addon but don't really wanna add another heavy addon to my list.

I've been trying to just make a macro for this but can't get it to work properly for both raid and party in 1 macro and also it doesn't kick if there's more than 1 alt with same name but different realm in the group :(
/run for i=1,GetNumGroupMembers() do if UnitName("raid"..i) ~= UnitName("player") then UninviteUnit("raid"..i, "reason") end end

Would be very useful to have for me at least when I'm done summoning my alts to places and want to quickly kick all my alts from the group :)

**Comment by leatrix** [comment]
Try 9.1.37.alpha.1.
/ltp dis - Disband group
/ltp reinv - Disband and reinvite group
Only tested briefly with a 3 player group.

**Comment by zeenk** [comment]
You are truly amazing at what you do, works perfectly and just the way I wanted it to, thanks!:) happy new year

**Comment by leatrix** [comment]
Awesome.  I'll add a restriction that the commands can't be used while you are queued or in a group finder dungeon (because of votekick, invite confirmations while in the queue, etc).  Can't see any problem with that.

**Comment by leatrix** [comment]
Would you like me to replace the disband code with the macro you posted today?  I can do that if you prefer.

**Comment by zeenk** [comment]
> 

Did you see my post on wowinterface.com? o.o or which macro are you talking about?

**Comment by leatrix** [comment]
Yes the macro in the last post you made there.

**Comment by zeenk** [comment]
The macro they helped me with works great so do what you want with the addon feature, (if you want it to push it to main version or not) because it could be used by others to troll disband groups or something like that unless there's some restriction on the usage of it. Feel kinda bad now that you put the work in to get it into the addon so it's up to you really if you wanna use it or not in the addon, but if not the macro does the job just fine for me.
