### ISSUE TITLE
Leatrix - Enhance minimap

### ISSUE THREAD

**Issue by Plusader** [leatrix/leatrix-plus#76]
When enabling this option the minimap moves a bit to the top of the screen.
The "Zone-Text Area/Field" positioned above it looks like that (screenshot) then.

![2022-01-08 23-08-28](https://user-images.githubusercontent.com/35087629/148661588-0a45db29-5536-42fa-8a21-c006bf1a7b51.png)

I think that this replacement should only be active when "Hide Zone-Text Area/Field" is selected by the user.

**Comment by leatrix** [comment]
Now that you can freely move the minimap, the minimap no longer moves by itself when you toggle the zone text bar.  So just hold alt and drag the minimap down a bit to make room for the zone text bar.

**Comment by Plusader** [comment]
Thanks
