### ISSUE TITLE
Suggestion: Allow us to custom set Automation override keybind

### ISSUE THREAD

**Issue by SuperTziva** [leatrix/leatrix-plus#79]
This is a suggestion to please allow us to select which modifier to use in the settings to override question automation instead of defaulting to 'shift'.

Context for this issue: I have some characters for which shift+click is bound to an ability, which means I cast that ability instead when I try to override the quest automation.  On these characters, I am forced to manual disable and reenable the automation each time I need to access a quest giver's vendor menu or select specific quests only.  It would be nice if I could change it to cntrl or alt or even a custom keybind.

Thanks!

**Comment by leatrix** [comment]
In 9.1.40.alpha.1 (and in the latest alphas for BCC and Classic Era/SoM), you can set the override key to be shift, alt or control.
