### ISSUE TITLE
Profiles for alts functionality?

### ISSUE THREAD

**Issue by Swordart25** [leatrix/leatrix-plus#83]
Can you pleas add option for profiles with different settings saved in them ?

**Comment by leatrix** [comment]
It's account wide settings only.  If you want to save frame positions per character, disable 'Manage frames' and reload, right-click the player frame and select Move frame > Unlock frame (if it isn't already unlocked) then you can drag the player frame and Wow will save its position per character.  You can do the same for the target frame too.

**Comment by Swordart25** [comment]
I wanted to have new hold ctrl+ space to use mount special animation on specific chars since i have it as keybind for ability on different character.

**Comment by leatrix** [comment]
Okay but all Leatrix addons are always account-wide settings so you can set it and forget it and having only one settings file makes it much easier to manage.
