### ISSUE TITLE
Feature request - Object tracker fixed height

### ISSUE THREAD

**Issue by mjakobsen** [leatrix/leatrix-plus#86]
Hello,
I'm really sorry if you have a place for this I couldn't find.
I was wondering if it was possible to add a section to add a fixed height and scroll to the object tracker. It would be even better if one could add a background to the frame as well.

**Comment by leatrix** [comment]
This is the right place and I value all feedback.  There won't be any settings that touch the objective tracker though.  Not unless Blizzard fixes all the problems with it in Dragonflight.

**Comment by mjakobsen** [comment]
Was afraid it wasn't an easy thing. Have been looking for some time and I can only find complete overhaul where they make a new frame, and hook into all the tracker events. I've landed on !KalielsTracker, but there's quite a lot of problems with the enrage button in Thorghast and other small stuff.
It's also annoying to have a complete overhaul when all I want is a set height and a scroll bar, all the other stuff I just want standard.

I haven't done any LUA and wow addon developing, I am a developer by trade thou so I could probably hack something that finds the frame and tries to set a height, do you have any experience trying this, is it a lost cause? I get you don't want to do it with Leatrix as you need to support it through updates and all that, but could it work for a hacky not shared thing ?

With that said thanks for the addon, been using it for some years now, and have replaced a lot of small addons for different things, keep it up!

**Comment by leatrix** [comment]
It's old but you might find Xrystal's post at the end of this thread useful:
https://www.wowinterface.com/forums/showthread.php?p=302526

**Comment by mjakobsen** [comment]
Ahh I guess there's good reason noone have made a "just set a height and scroll" addon so far. Think ill see if they do anything for 10.0, and if they don't look into if I can make something work for me :). Again keep up the good work!
