### ISSUE TITLE
Settings not saving + request

### ISSUE THREAD

**Issue by skjetne** [leatrix/leatrix-plus#87]
Hey,

Leatrix SL v.9.2.21
WoW SL v.9.2.5.44908

**Request**

1. Would it be able to add the objectives frame to the addon as improvement. I would love to be able to use it to move and scale this. by default it's very large. 

2. Can we get the possibility to disable the new covenant button when using square map? It actually makes it harder to quickly check which covenant you are, and just having it as the covenant would be easier.

**Issue**
Leatrix is not saving settings with other addons. 

Lua Error
```2x Leatrix_Plus\Leatrix_Plus-9.2.21.lua:8238: Usage: HookScript(object, method, [handler]): 'object' - nil or table expected got string
[string "=[C]"]: ?
[string "@Ace3\AceHook-3.0\AceHook-3.0-9.lua"]:130: in function <Ace3\AceHook-3.0\AceHook-3.0.lua:118>
[string "@Ace3\AceHook-3.0\AceHook-3.0-9.lua"]:367: in function `HookScript'
[string "@Leatrix_Plus\Leatrix_Plus-9.2.21.lua"]:8238: in function `HighlightTabs'
[string "@Leatrix_Plus\Leatrix_Plus-9.2.21.lua"]:8251: in function `?'
[string "@Leatrix_Plus\Leatrix_Plus-9.2.21.lua"]:11651: in function <Leatrix_Plus\Leatrix_Plus.lua:11189>

Locals:
(*temporary) = "Usage: HookScript(object, method, [handler]): 'object' - nil or table expected got string" ```

To save now, I have to disable all addons, make my changes, then enable again, making this wonderful addon very hard to use.

**Comment by leatrix** [comment]
LTP isn't saving settings correctly because the addon isn't loading correctly due to a conflict with another addon that you have installed.

Disable all other addons.  You should find that LTP works correctly.  Enable other addons gradually until you find the addon causing the problem.

You can then either disable that addon or disable the setting in LTP that conflicts with it.  LTP is modular so there is no need to disable LTP.

From the error you included, it looks like it could be a conflict with the 'Hide chat buttons' ('Chat') setting.  So in the first instance, try disabling 'Hide chat buttons' and see if that fixes the problem.  If you want to keep using 'Hide chat buttons', disable the addon that conflicts with it.

**Comment by leatrix** [comment]
For 'Enhance minimap' covenant button texture, try 9.2.22.alpha.4.  The button needs to be small and ring-shaped to fit neatly inside the square minimap but this update will use the original button texture so you will see your covenant choice inside it.

In CurseForge App, you can switch to alpha releases by right-clicking the addon in your addon list and changing release type to alpha.  You can always change it back to release later.  Or you can download the alpha from [CurseForge](https://www.curseforge.com/wow/addons/leatrix-plus/files/all).

**Comment by skjetne** [comment]
> From the error you included, it looks like it could be a conflict with the 'Hide chat buttons' ('Chat') setting. So in the first instance, try disabling 'Hide chat buttons' and see if that fixes the problem. If you want to keep using 'Hide chat buttons', disable the addon that conflicts with it.

Thank you, disabling this resolved my issue with the addon not saving 👍 The addon I use for chat is [Glass](https://www.curseforge.com/wow/addons/glass), and disabling Glass allows me to have the setting enabled with the rest saving as normal. 

Tried 9.2.22.alpha.4, and while it does ofc show the covenant better, it also looks a bit weird with anyone other than NF ofc. Can't you just display the covenant icon stand alone without the circle around it? Ofc I understand if you don't want to put to much work into this now though that SL is nearing the end.  Thank you for being so responsive 🙌

**Comment by leatrix** [comment]
It will have to keep the ring for the time being and we will see what happens in Dragonflight [when I get access](https://github.com/leatrix/leatrix-plus/issues/89).
