### ISSUE TITLE
Cooldown Tracker

### ISSUE THREAD

**Issue by sdinerstein** [leatrix/leatrix-plus#9]
Is it possible to have an option for one of the 5 slots to track whatever trinket proc is equipped? For example in PVP sometimes I wear a Battlemasters trinket and then swap to Badge, and I'd like to track whichever one is currently equipped.

**Comment by leatrix** [comment]
The option just tracks buffs, that's all.  You will need to enter the spell ID of the buff from each trinket in two separate boxes.
