### ISSUE TITLE
Feature Request: Announce Trades (Gold, Enchants, Items) to Chat.

### ISSUE THREAD

**Issue by denumerable** [leatrix/leatrix-plus#90]
Leatrix Plus is the FIRST addon I install for QoL. Thank you for the great work.

I have other addons that announce trade, but it would be so nice if LTP could do this as well so I could get rid of said addons (Gargul, TradeLog Unlimited, Gogoloot).

Cheers.

**Comment by Brian853** [comment]
+1
maybe can whisper my trading object on trading successfully
