### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by zeenk** [leatrix/leatrix-plus#91]
Pops up if you invite your alts a bit too early while they are still on the loading screen but the character has come online.
I have auto accepting invites from friends/community on.

Message: Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:480: bad argument #2 to 'strsplit' (string expected, got nil)
Time: Tue Aug 30 01:21:41 2022
Count: 1
Stack: Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:480: bad argument #2 to 'strsplit' (string expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: in function `strsplit'
[string "@Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua"]:480: in function `FriendCheck'
[string "@Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua"]:11184: in function <Interface\AddOns\Leatrix_Plus\Leatrix_Plus.lua:11102>

Locals:

**Comment by leatrix** [comment]
I wasn't able to replicate it but I added a couple more checks to the code in 9.2.27.alpha.9 to address the error in your report.  That should resolve it.  Thank you for reporting.

**Comment by zeenk** [comment]
Seems to be fixed now with the latest alpha build 👍
