### ISSUE TITLE
Automate quests for darkmoon faire dailies is not working

### ISSUE THREAD

**Issue by zeenk** [leatrix/leatrix-plus#92]
Is there something I'm missing in my settings to make make the addon auto take and turn in the DMF dailiy quests? 🤔 

![2022-09-04_20-44-02](https://user-images.githubusercontent.com/68170439/188328757-55c05ad1-fefd-47ad-b6fc-1a82ce15ebe0.png)

**Comment by leatrix** [comment]
In 3.0.04.alpha.1, Darkmoon Faire daily repeatable quests should be automated for English game clients if you have the required materials in your bag.  Quests from Gelvas Grimegate are excluded.

In CurseForge App, you can switch to alpha releases by right-clicking Leatrix Plus in your Wrath addons listing and changing release type to alpha.

**Comment by zeenk** [comment]
I should had mentioned I was talking about retail wow, doesn't work for me even if I have game tokens in my bag, doesn't auto accept quests whenever I talk with the daily npcs

**Comment by leatrix** [comment]
My apologies.  This should be fixed for Shadowlands and Dragonflight in 9.2.28.alpha.20.

**Comment by zeenk** [comment]
Thanks, works 😄
