### ISSUE TITLE
rotate minimap

### ISSUE THREAD

**Issue by Warbreeder** [leatrix/leatrix-plus#93]
if i activate the square minimap from the addon and rotate minimap in interface options-> display after reload the option is disabled

**Comment by leatrix** [comment]
It's intended.  You can enable the rotate minimap setting in the game options panel temporarily to see that a rotating minimap doesn't work with a square minimap shape.  It's much the same with other minimap replacement addons that offer a square minimap shape.  So if you enable square minimap, LTP just makes sure that the rotate minimap setting is unchecked when you login, that's all.

**Comment by Warbreeder** [comment]
can i disable that option to uncheck it because for me it always worked and i always used it with your and sexymap before you added the square map option and i never had problem it always rotated the map so its annoyng that i have to enable the option everytime i logon

**Comment by leatrix** [comment]
If it worked for you before then sure, okay.  Install 9.2.34.alpha.3.
