### ISSUE TITLE
Feature Request: keep chat history 

### ISSUE THREAD

**Issue by geezerbahl** [leatrix/leatrix-plus#94]
One of the nice features of Prat is when if I reload UI my chat history is still there.  With Leatrix Plus if I reload it wipes out my history.  Any chance of adding something like this (or is it there and I'm clueless)?

**Comment by leatrix** [comment]
The only way this could be added is in a very minimal way.  Such as only restoring the last 128 lines (the default chat history length), only restoring one character at a time and possibly only restoring the general chat window (the main chat window).

So if you /reload or relog to the same character, the last 128 lines of the general chat window would be restored.  If you relog to a different character, the chat would start fresh.

Would that be too restrictive for you?

**Comment by geezerbahl** [comment]
That would work... but I'm more interested in Guild chat (which I have in a separate tab).  Would this include that as well?

Have you see how Prat works/does this?

**Comment by leatrix** [comment]
Try 9.2.35.alpha.1 (or higher).  There is a new option called 'Restore chat messages' ('Chat').  If enabled, the last 128 lines of chat will be restored when you reload or relog to the same character.  The option is designed to be minimalist but multiple chat windows are supported.  Let me know if you find this useful or if you have any issues with it.
