### ISSUE TITLE
Feature requests: Selective quest automation and dialog automation

### ISSUE THREAD

**Issue by jamesbearclaw** [leatrix/leatrix-plus#96]
For selective quest automation, having the ability to shift-click to open the quest giver, right click on the quest to add/remove it from the automation.  That way we could have automation without everything being automated.  I used another addon for this feature, but it's no longer being supported and I've moved most of my features to LTP.

For selective dialog automation, it would be the same thing, open an NPC and right click on any dialog to have it automatically selected the next time you open that NPC.  You could have it show something next to the option that is automated (just in case someone opens the NPC with shift held to disable the dialog with another right click).

**Comment by leatrix** [comment]
Feedback appreciated.  This isn't something I'm looking to add at the moment.
