### ISSUE TITLE
[BUG] HIDE ERROR MESSAGES 9.2.37 NOT WORKING ( DF BETA )

### ISSUE THREAD

**Issue by lloskka** [leatrix/leatrix-plus#98]
Morning.

With the latest update of leatrix plus to version 9.2.37 , Hide Error Messages ( under text menu ) has broke.

Rolling back to version 9.2.36 , and voila its working again.

Cheers!

**Comment by leatrix** [comment]
Please try 9.2.38 and let me know if that's ok for you now.

Blizzard made some changes to the focus frame game code in Dragonflight Beta 10.0.2.45779 which may have caused the addon to not load correctly.
