### ISSUE TITLE
[Bug] Automate quests

### ISSUE THREAD

**Issue by zeenk** [leatrix/leatrix-plus#99]
I've started to notice that automate quest sometimes does not work on npcs that also has dialog options available, this quest from Pocopoc in zereth morthis for example does not work.

![2022-09-30_02-51-23](https://user-images.githubusercontent.com/68170439/193167144-504d1b25-a544-47fd-b7a3-6b4d31d70f5f.png)

**Comment by leatrix** [comment]
That particular gossip frame text contains a < symbol which usually denotes an action.  LTP tries to avoid automating quests for gossip frames that include actions because the action could be important (such as allowing the player to skip content or teleport, etc).

**Comment by zeenk** [comment]
Ah okay, I see. Closing this issue then ^^
